### ISSUE TITLE
Import pojavlauncher controls or Better control customization 

### ISSUE THREAD

**Issue by yBrunoDev** [FCL-Team/FoldCraftLauncher#101]
### Description

i would be good to import pojavlauncher controls into the FCL i dont know if it is possible, or customize ur controls like pojavlauncher that u can add borders
sorry abt my english im portuguese.

### Why

some people would like it (like me)

**Comment by didntpenguin** [comment]
do u know,fcl control have alot different with pojav? then no ask about cross launcher control support,if u like pojav control,then use pojav,stop request gey features
