### ISSUE TITLE
UI、文本问题

### ISSUE THREAD

**Issue by BallonAirr** [FCL-Team/FoldCraftLauncher#104]
### Launcher Version

1.0.0至今

### Device Information

OPPOA93S,Android11,arm64

### Problem Description

见图 并无实际影响
![Screenshot_2023-08-27-13-48-24-27_c8a66bc90793a73eafa5773962b202df](https://github.com/FCL-Team/FoldCraftLauncher/assets/142641076/2eac97c7-41f9-4907-a56a-efb7cb5512b1)
![Screenshot_2023-08-27-13-48-24-27_c8a66bc90793a73eafa5773962b202df](https://github.com/FCL-Team/FoldCraftLauncher/assets/142641076/0653f800-f968-406a-b81a-0034c16eab79)

### Java

～

### Renderer

～

### Game Version

～

### Modifications Made to the Game

～

**Comment by ShirosakiMio** [comment]
![image](https://github.com/FCL-Team/FoldCraftLauncher/assets/19233890/8c2beaa5-8ce6-4090-ba03-51d45bbcf8f5)
修了
