### ISSUE TITLE
无法进行微软账号登录

### ISSUE THREAD

**Issue by yizhimengxin2233** [FCL-Team/FoldCraftLauncher#106]
### Launcher Version

1.0.7

### Device Information

Samsung Tab S8+,Android13,arm64

### Problem Description

在登录进入最后一步，显示授权界面时，无论点击授权还是取消都只会多出现选中的框与蓝色特效，与正常网页中点击网页链接效果一致，但无法跳转至任何界面。此时若返回退出，点击fcl中弹出的取消按钮之类都无效，只能重启软件。
（重启软件后似乎log会被清空？）

**Comment by zkitefly** [comment]
听起来是网络问题

**Comment by yizhimengxin2233** [comment]
> 听起来是网络问题

真的是啊，开个加速器立马好了（
