### ISSUE TITLE
Optiforge crashing when creating world

### ISSUE THREAD

**Issue by IamDaiKioo** [FCL-Team/FoldCraftLauncher#112]
### Launcher Version

FCL-release-1.0.7.apk

### Device Information

realme c12

### Problem Description

when im making world its crashing

### Java

Java 17

### Renderer

Holy-GL4Es

### Game Version

1.20.10

### Modifications Made to the Game

optifine hd_u_g9

### Game Crash Report

optiforge is crashing when creating world

### Launcher Crash Report

.

### Launcher Log File

.

**Comment by root-S7** [comment]
Please send crash file

**Comment by IamDaiKioo** [comment]
![Screenshot_2023-09-05-20-19-20-60_c8a66bc90793a73eafa5773962b202df](https://github.com/FCL-Team/FoldCraftLauncher/assets/144022142/6968064d-da17-4996-ab91-ba1ab8ef4865)
![Screenshot_2023-09-05-20-19-14-34_c8a66bc90793a73eafa5773962b202df](https://github.com/FCL-Team/FoldCraftLauncher/assets/144022142/60de7f7c-5af4-4eb2-aa0a-d59e6e2caaf9)
![Screenshot_2023-09-05-20-19-08-10_c8a66bc90793a73eafa5773962b202df](https://github.com/FCL-Team/FoldCraftLauncher/assets/144022142/dbfb7e16-87b6-4973-8d04-a9348a604a8d)
![Screenshot_2023-09-05-20-19-02-04_c8a66bc90793a73eafa5773962b202df](https://github.com/FCL-Team/FoldCraftLauncher/assets/144022142/8cfb2c24-0417-4404-beea-7b25d63ea975)
