### ISSUE TITLE
导入键位同时导入键位中的按键样式

### ISSUE THREAD

**Issue by block13566** [FCL-Team/FoldCraftLauncher#115]
### Description

导入键位时同时导入键位中的按键样式

### Why

方便二次修改键位

**Comment by Vera-Firefly** [comment]
你可以联系键位的作者修改,或者自己创建一个键位

**Comment by block13566** [comment]
> 你可以联系键位的作者修改,或者自己创建一个键位

二改就是给我自己用的啊，因为作者的有些小地方不舒服，如果我联系作者反复修改岂不是显得很烦人，另外，我如果有自己创建一个键位的时间我为什么不自己弄

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/7971656085
