### ISSUE TITLE
I cant enter the game

### ISSUE THREAD

**Issue by herescomethesun** [FCL-Team/FoldCraftLauncher#117]
### Launcher Version

1.0.7

### Device Information

Samsung a12

### Problem Description

I can't accept and continue, it says that I don't have internet, but I do have internet, I have tried disconnecting the wifi and connecting it again and it is still the same, I hope it will be solved soon, what can I do?

### Java

I cant enter the game

### Renderer

I cant enter the game

### Game Version

I cant enter the game

### Modifications Made to the Game

I cant enter the game

### Game Crash Report

![Screenshot_20230913_012253_Fold Craft Launcher](https://github.com/FCL-Team/FoldCraftLauncher/assets/143905667/943ece43-3d1f-458e-a57e-ef5dd10c6670)
It appears like this

### Launcher Crash Report

It appears like this for hours

### Launcher Log File

I dint have a log file

**Comment by root-S7** [comment]
Some countries can not to connect the Chinese internet

**Comment by herescomethesun** [comment]
> Some countries can not to connect the Chinese internet

I see, what i should do? Because, it used to work, but i uninstall it and now just dont work,
I will try to use an vpn

**Comment by herescomethesun** [comment]
I use a vpn and problem solved
