### ISSUE TITLE
1.20.2 doesnt launch

### ISSUE THREAD

**Issue by LegacyGamerHD** [FCL-Team/FoldCraftLauncher#122]
### Launcher Version

1.0.7-patch1

### Device Information

google pixel 7

### Problem Description

just crasshes

### Java

17

### Renderer

any

### Game Version

1.202

### Modifications Made to the Game

none

**Comment by LegacyGamerHD** [comment]
@ShirosakiMio are aware of this

**Comment by 1mmaDickhead** [comment]
@LegacyGamerHD the creator of FCL Is already working on this. I posted about this on the discord server

**Comment by LegacyGamerHD** [comment]
> @LegacyGamerHD the creator of FCL Is already working on this. I posted about this on the discord server

can you tell me there discord tag

**Comment by 1mmaDickhead** [comment]
It's @artDev

**Comment by 1mmaDickhead** [comment]
I think

**Comment by 1mmaDickhead** [comment]
I don't really know if he is the creator of what

**Comment by 1mmaDickhead** [comment]
I think he is

**Comment by ShirosakiMio** [comment]
1.20.2 needs newer lwjgl. There are a lot work to do to make lwjgl work on the FCL. Tungsten doesn't have enough time to do this.

**Comment by 1mmaDickhead** [comment]
It has been fixed on PojavLauncher

**Comment by 1mmaDickhead** [comment]
So I think they are working on it

**Comment by Ihdhehdhdhd83ue** [comment]
How download

**Comment by 1mmaDickhead** [comment]
How to download what?

**Comment by ShirosakiMio** [comment]
fixed
