### ISSUE TITLE
1.20.1渲染箱子会出现问题

### ISSUE THREAD

**Issue by JackieJK** [FCL-Team/FoldCraftLauncher#126]
### Launcher Version

1.0.7

### Device Information

xiaomi12s

### Problem Description

箱子会出现渲染错误

### Java

17

### Renderer

holy

### Game Version

1.20.1

### Modifications Made to the Game

fabric机械动力

**Comment by JackieJK** [comment]
![Screenshot_2023-09-28-21-10-53-484_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/10346889/04ee88fb-fdf9-4528-b826-e79da0a3e65a)

**Comment by ShirosakiMio** [comment]
flywheel

**Comment by block13566** [comment]
机械动力的话/flywheel backend off就行了
