### ISSUE TITLE
release date of foldcraft launcher android with controls

### ISSUE THREAD

**Issue by LithuanianBoi41** [FCL-Team/FoldCraftLauncher#13]
Tugsten work for fold craft launcher please and release the apks with controls

**Comment by Doorpol** [comment]
Can't wait

**Comment by tigerbrocode** [comment]
💀

**Comment by HEROBRINE31853** [comment]
**bro...**

**Comment by LegacyGamerHD** [comment]
> Tugsten work for fold craft launcher please and release the apks with controls

Not gone happen it's not even close to being finished

**Comment by AwitaYT** [comment]
No tampoco
