### ISSUE TITLE
Swipeable

### ISSUE THREAD

**Issue by Matiffi** [FCL-Team/FoldCraftLauncher#132]
### Description

Add an item in the control settings swipeable
![Screenshot_2023-10-13-18-33-53-595_net kdt pojavlaunch](https://github.com/FCL-Team/FoldCraftLauncher/assets/147846045/4d9d248e-66f6-46f0-bf47-fdba07aa89cb)
![Screenshot_2023-10-13-18-35-39-985_com mojang minecraftpe](https://github.com/FCL-Team/FoldCraftLauncher/assets/147846045/51c69cc9-f9b2-4ef1-9e4c-a0734986b82d)

### Why

You can run and jump with one finger
It's lighter and suitable for pvp

**Comment by Matiffi** [comment]
> ### Description
> Add an item in the control settings swipeable
![Screenshot_2023-10-13-18-37-27-186_net kdt pojavlaunch](https://github.com/FCL-Team/FoldCraftLauncher/assets/147846045/f9163f24-28f8-4a55-ace0-381344611eb7)
 ![Screenshot_2023-10-13-18-35-39-985_com mojang minecraftpe](https://user-images.githubusercontent.com/147846045/274947168-51c69cc9-f9b2-4ef1-9e4c-a0734986b82d.png)
> 
> ### Why
> You can run and jump with one finger It's lighter and suitable for pvp

**Comment by Tungstend** [comment]
Set sneak keycode to space and disable center double click

**Comment by Tungstend** [comment]
![Screenshot_2023-10-16-10-22-53-39_c8a66bc90793a73eafa5773962b202df](https://github.com/FCL-Team/FoldCraftLauncher/assets/74163103/b07b580e-92c4-4f0e-8a37-248961548d50)
