### ISSUE TITLE
Authentication sever

### ISSUE THREAD

**Issue by Spidergoku9001** [FCL-Team/FoldCraftLauncher#135]
### Description

What is this?
What is it used for ?
What can it do ?
Just tell me what ever you know.

### Why

![Uploading IMG_20231015_165114.jpg…]()

**Comment by zhangjing-GitHub-Code** [comment]
Hey bro, you submited this issue before your image was uploaded, so we can't see what picture it is.
Please edit your issue, then reupload image.
