### ISSUE TITLE
Crash forge 1.20.1 lastest

### ISSUE THREAD

**Issue by DoriteLover** [FCL-Team/FoldCraftLauncher#137]
### Launcher Version

Lastest

### Device Information

Samsung tab s6 lite wifi

### Problem Description

[latest.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13039611/latest.log)

### Java

Jre 17

### Renderer

Holygles opengl2.1

### Game Version

1.20.1

### Modifications Made to the Game

Forge optifine

### Game Crash Report

![Screenshot_20231019_144113_Fold Craft Launcher](https://github.com/FCL-Team/FoldCraftLauncher/assets/148433928/cf724d77-f239-480d-952c-2132198104b9)

### Launcher Crash Report

Nope

### Launcher Log File

[fcl-exported-logs-2023-10-19T14-58-31.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13039660/fcl-exported-logs-2023-10-19T14-58-31.log)

**Comment by DoriteLover** [comment]
Device edit: samsung tab s6 lite WiFi android 13 one ui 5.1.1

**Comment by ShirosakiMio** [comment]
use optfine I6_pre6

**Comment by DoriteLover** [comment]
there is only one version and im using it

> use optfine I6_pre6

**Comment by zkitefly** [comment]
> there is only one version and im using it
> 
> > use optfine I6_pre6
> 
> 

![Screenshot_2023-10-21-16-14-10-56_c8a66bc90793a73eafa5773962b202df.jpg](https://github.com/FCL-Team/FoldCraftLauncher/assets/64117916/ae914a72-70bd-4983-970d-1e1a5a089e08)

**Comment by DoriteLover** [comment]
Still same issue, or I have to lower the forge version

**Comment by zkitefly** [comment]
![image](https://github.com/FCL-Team/FoldCraftLauncher/assets/64117916/45148462-65e7-4eae-9e7a-64ce164682d6)

**Comment by zkitefly** [comment]
> Still same issue, or I have to lower the forge version

Upload new log
