### ISSUE TITLE
Android 7.0

### ISSUE THREAD

**Issue by kjjjjjjjjjjjj** [FCL-Team/FoldCraftLauncher#138]
### Description

Create this app for Android 7.0

### Why

Create this app for Android 7.0 please I wish you should do this better please don't reject like hmcl pe please create or this project  is a failure because most of the people have Android 7.0 version 4 Android 5.0 version most of the people have this Android versions hope you should do this

**Comment by ShirosakiMio** [comment]
impossible. Lots of feature works only on Android 8+

**Comment by kjjjjjjjjjjjj** [comment]
Please do this please do a future project like this
