### ISSUE TITLE
服务器不显示正版皮肤

### ISSUE THREAD

**Issue by zhangjiajin112** [FCL-Team/FoldCraftLauncher#139]
### Launcher Version

1.1.0

### Device Information

小米11青春活力版

### Problem Description

正版服务器不显示皮肤，离线服有加插件，服务端核心是mohist

### Java

Java8

### Renderer

GL4ES

### Game Version

1.16.5

### Modifications Made to the Game

高清修复加forge，都是最新版

**Comment by BallonAirr** [comment]
使用万用皮肤补丁

**Comment by zhangjiajin112** [comment]
> 使用万用皮肤补丁

一样的
