### ISSUE TITLE
mod过多的闪退问题//too much mods case crash

### ISSUE THREAD

**Issue by Zhusiyuan354** [FCL-Team/FoldCraftLauncher#140]
### Launcher Version

1.1.0

### Device Information

Redmi K60,MIUI 14,Android 13,Snapdragon 8+

### Problem Description

虽然我知道这个比较可能不太对，但是我还是想说一下：我本来是使用的1.19.2版本，在HMCL上启动66个模组，没有丝毫问题，再将同样的模组装载至fcl上就不行了

### Java

Java 17

### Renderer

Holy-GL4ES

### Game Version

1.19.2

### Modifications Made to the Game

Null

**Comment by zkitefly** [comment]
请上传日志
