### ISSUE TITLE
Open4Es shader crash Game on Holy renderer

### ISSUE THREAD

**Issue by itzMe79** [FCL-Team/FoldCraftLauncher#141]
### Launcher Version

1.1.0

### Device Information

Redmi note 9s, Snapdragon 720G,6 ram, Android 12 , miui 14,arm 64

### Problem Description

When choosing the shader Open4es ( Holy renderer ) the mojang screen loading then the game crash and taking me out to the menu without showing the crash or anything in the launcher But its working on Zink renderer but with a lot of lag also in pojav launcher Holy renderer the shader working without any problems 

### Java

17

### Renderer

Holy-GL4ES

### Game Version

1.20.1

### Modifications Made to the Game

Optifine HD_U_I5

https://github.com/FCL-Team/FoldCraftLauncher/assets/149435109/613dade9-4f33-479a-b773-17a8f41d1a70

### Launcher Log File

[latest.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13209949/latest.log)

**Comment by LegacyGamerHD** [comment]
As expected

**Comment by itzMe79** [comment]
> As expected 

Wdym??
