### ISSUE TITLE
可否支持jre21

### ISSUE THREAD

**Issue by REYXTE** [FCL-Team/FoldCraftLauncher#148]
### Description

能不能考虑一下支持jre21或者类似pojavlauncher的导入java。

### Why

jre21较为流畅，并且jre21.0.1已经完全支持模组运行

**Comment by root-S7** [comment]
java21只是用来应对mojang作死又强制要求最低java版本的。还有就是不要过于太迷信高版本java一定会优化很好。不是所有mod支持用java21，有可能小白会用java21启动1.7.10forge端这种迷惑行为。

**Comment by root-S7** [comment]
导入可以考虑，但要加警告弹窗

**Comment by REYXTE** [comment]
> java21只是用来应对mojang作死又强制要求最低java版本的。还有就是不要过于太迷信高版本java一定会优化很好。不是所有mod支持用java21，有可能小白会用java21启动1.7.10forge端这种迷惑行为。

首先Java21就是比Java17流畅你可以自己试试，现在Java21所有模组都支持，Java21启动1.7.10你们可以在Java名称(可用版本)，还有我建议把1.16.5用Java17显示错误的Java版本删了。

**Comment by root-S7** [comment]
> > java21只是用来应对mojang作死又强制要求最低java版本的。还有就是不要过于太迷信高版本java一定会优化很好。不是所有mod支持用java21，有可能小白会用java21启动1.7.10forge端这种迷惑行为。
> 
> 首先Java21就是比Java17流畅你可以自己试试，现在Java21所有模组都支持，Java21启动1.7.10你们可以在Java名称(可用版本)，还有我建议把1.16.5用Java17显示错误的Java版本删了。

这句话我否定，你如果觉得java版本能对游戏影响很大。那根隔壁腐竹群研究Java+启动参数对服务器性能影响没什么区别。反正我现在觉得我以前研究启动参数+Java版本对服务器优化真是个很奇怪行为。

只能说可能会有一些提升，但没实际意义

**Comment by root-S7** [comment]
> 1.16.5 ➕ Forge 使用 Java17 启动会导致游戏崩溃

日志文件

**Comment by 8MiYile** [comment]
> > 1.16.5 ➕ Forge 使用 Java17 启动会导致游戏崩溃
> 
> 日志文件

forge本身就对java版本很敏感，超出版本范围不给启动你是一点也不提

**Comment by REYXTE** [comment]
关闭......
