### ISSUE TITLE
请补充 HMCL 版权声明

### ISSUE THREAD

**Issue by burningtnt** [FCL-Team/FoldCraftLauncher#154]
依照 https://github.com/huanghongxun/HMCL/?tab=readme-ov-file#additional-terms-under-gplv3-section-7 ，该开源项目不得移除源代码中每个文件头的版权声明，请补充。

**Comment by Tungstend** [comment]
抱歉，之前没时间，最近会补上

**Comment by Tungstend** [comment]
已添加

**Comment by Tungstend** [comment]
> 依照 https://github.com/huanghongxun/HMCL/?tab=readme-ov-file#additional-terms-under-gplv3-section-7 ，该开源项目不得移除源代码中每个文件头的版权声明，请补充。

今日看到阁下在 HMCL 群再次说到该问题，并称我“人品差”，我想我应该做一些说明，因为我觉得你可能对我有些误解，当然如果你仍然保持你的想法我也没办法。
首先，你说的如果复制文件不会删除版权申明，我确实不是复制文件，我直接复制了代码，因为我需要理清 HMCLCore 中的源码都是在写什么，然后删掉一些不必要的，修改一些不合适的，我不太懂 gpl 协议什么的，总之确实没加上版权申明，如果给 HMCL 的各位带来什么不便，那我只能说抱歉，现在加了。
第二，你说我一直不改这个问题，直到你发 DMCA 我才改，这并不是因为你发 DMCA 我才改，我确实是没看到，因为当时忙别的事，很长一段时间没更新，一直到12月底才恢复更新，你的 DMCA 12月初就发了，我压根没看到，我看到该 issue 后当天就改了。并不是刻意拖着不改，所有记录都是可以查的，能够看到时间。
第三，你说我每次同步 HMCLCore 的时候都是重新 commit 而不是 Merge，因为 FCLCore 本身不是 fork HMCL，我不知道有什么办法能 Merge 你们的更新，如果可以我倒是宁可直接 Merge，毕竟这更方便，但 FCL 确实不可能直接 fork HMCL。
第四，你以 neoforge 的 bug 为例说我只会抄你的，且不经测试，FCLCore 本来就是以同步 HMCLCore 的功能为目的，说抄也没啥问题，且本人时间精力能力本来就有限，FCL 也没有像 HMCL 这样强大的社区，我不可能像你们一样把你们写的每一行代码都测试一遍，而且出了什么问题我完全可以修改后让用户下载最新的 action。
总之，我不想得罪任何一位 HMCL 的开发者，如果你或者其他人认为我做错了什么，那么我随时欢迎你们向我提出问题，当然我并不经常看 GitHub 的 issue，因此也可以通过 QQ 这类手段联系我。

**Comment by burningtnt** [comment]
> 首先，你说的如果复制文件不会删除版权申明，我确实不是复制文件，我直接复制了代码，因为我需要理清 HMCLCore 中的源码都是在写什么，然后删掉一些不必要的，修改一些不合适的，我不太懂 gpl 协议什么的，总之确实没加上版权申明，如果给 HMCL 的各位带来什么不便，那我只能说抱歉，现在加了。

如果你直接复制代码，那么 —— 版权声明也会被复制过来
我只想说这么多。至于对于版权的问题，我觉得你倒也不至于罪大恶极，APP 内的版权信息是一直有的，并且 README 也标明

**Comment by Tungstend** [comment]
> > 首先，你说的如果复制文件不会删除版权申明，我确实不是复制文件，我直接复制了代码，因为我需要理清 HMCLCore 中的源码都是在写什么，然后删掉一些不必要的，修改一些不合适的，我不太懂 gpl 协议什么的，总之确实没加上版权申明，如果给 HMCL 的各位带来什么不便，那我只能说抱歉，现在加了。
> 
> 如果你直接复制代码，那么 —— 版权声明也会被复制过来 我只想说这么多。至于对于版权的问题，我觉得你倒也不至于罪大恶极：审查过 git commit，APP 内的版权信息是一直有的，并且 README 也标明
> 
> 除此之外，第二、第三、第四都是我们的共识，我始终同意

所以就是没有复制版权申明让你觉得我“人品差”吗

**Comment by burningtnt** [comment]
是的。HMCL 群内后续也有人问是不是对方完全没有遵循版权声明，我也做了反驳，并支持缺失的只有源码头上的版权声明。

**Comment by burningtnt** [comment]
好的我理解了

**Comment by Tungstend** [comment]
感谢你的理解，那这个话题到此为止，如果后续你对 FCL 有任何修改建议或者觉得我哪里做得不妥，都可以和我说，如果github上我没看到那就qq说

**Comment by Tungstend** [comment]
> 好的我理解了

这样吧，我今天又想了一下，我感觉就这么嘴上说说恐怕也难以消除你的误会，毕竟确实是我的问题，现在解释多少有点马后炮，不如来点实在的，我先去给黄鱼赞助一波，钱虽然不一定会到你手里，但反正你维的也是黄鱼的权，如果你觉得我还应该做些什么，你也可以和我讲，以表诚意，只要我能做到我都尽量做。

**Comment by Tungstend** [comment]
![C9Z AF82 9U2BQ~9L6T`N_T_tmb](https://github.com/FCL-Team/FoldCraftLauncher/assets/74163103/39e3759f-1c39-4a00-b8ab-c1c65a9dd47d)

**Comment by FrostNovaHD** [comment]
Whats this about
