### ISSUE TITLE
模组运行异常

### ISSUE THREAD

**Issue by BallonAirr** [FCL-Team/FoldCraftLauncher#155]
### Launcher Version

1.0.0至今

### Device Information

OPPOA93S arm64 Android11

### Problem Description

![Screenshot_2023-12-02-16-20-39-95_c8a66bc90793a73eafa5773962b202df](https://github.com/FCL-Team/FoldCraftLauncher/assets/142641076/05d4e71b-3ee2-442b-a9ed-89be19be963e)

### Java

Java8,17

### Renderer

all

### Game Version

all

### Modifications Made to the Game

部分模组

### Game Crash Report

见上

**Comment by root-S7** [comment]
请发日志文件，而不是闭眼问问题

**Comment by BallonAirr** [comment]
好的
[crash-2023-12-02_16.20.21-client.txt](https://github.com/FCL-Team/FoldCraftLauncher/files/13533863/crash-2023-12-02_16.20.21-client.txt)
[latest_game.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13533864/latest_game.log)

**Comment by root-S7** [comment]
还有就是Could not initialize class com.sum.jna.native可不是启动器问题，这有可能是你用的mod调用的C/C++的so动态链接库，但这些动态链接库并没有考虑到Android平台兼容性G了

**Comment by root-S7** [comment]
> 好的 [crash-2023-12-02_16.20.21-client.txt](https://github.com/FCL-Team/FoldCraftLauncher/files/13533863/crash-2023-12-02_16.20.21-client.txt) [latest_game.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13533864/latest_game.log)

xaero.map.exception.OpenGLException: OpenGL error: 1282
	at xaero.map.exception.OpenGLException.checkGLError(OpenGLException.java:16)
其实你大概看到OpenGL也猜到是为啥了

**Comment by root-S7** [comment]
XaerosWorldMap这个mod的问题，看上去是无法读取Xaero Icon集发生了崩溃
