### ISSUE TITLE
it wont install forge for 1.16.5

### ISSUE THREAD

**Issue by HighMonkey123** [FCL-Team/FoldCraftLauncher#156]
### Launcher Version

latest

### Device Information

Oppo a5w

### Problem Description

It won't install forge, even when i download it from the forge page itself.
It says code 1, and also it won't run at all if i use java 8.

### Java

java 17

### Renderer

default

### Game Version

1.16.5

### Launcher Log File

[fcl-exported-logs-2023-12-02T21-09-12.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13536360/fcl-exported-logs-2023-12-02T21-09-12.log)

**Comment by HighMonkey123** [comment]
*A5s

**Comment by LegacyGamerHD** [comment]
Not the full log

**Comment by LegacyGamerHD** [comment]
Also try changing your mirror
