### ISSUE TITLE
兼容Cleanroom?

### ISSUE THREAD

**Issue by REYXTE** [FCL-Team/FoldCraftLauncher#158]
### Description

是否能兼容Cleanroom(https://www.mcmod.cn/class/9689.html)?

### Why

Cleanroom可以让1.12.2版本使用Java21和LWJGL3运行。

**Comment by root-S7** [comment]
![Screenshot_20231206_113904_QQ.jpg](https://github.com/FCL-Team/FoldCraftLauncher/assets/110681414/6ece5542-6d24-4d89-a1c6-ad457012ede8)

其实我也搞不懂改了lwjgl3会有什么卵用，反而会影响老mod兼容性

**Comment by REYXTE** [comment]
> ![Screenshot_20231206_113904_QQ.jpg](https://private-user-images.githubusercontent.com/110681414/288273471-6ece5542-6d24-4d89-a1c6-ad457012ede8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NjE3ODksIm5iZiI6MTcwMTg2MTQ4OSwicGF0aCI6Ii8xMTA2ODE0MTQvMjg4MjczNDcxLTZlY2U1NTQyLTZkMjQtNGQ4OS1hMWM2LWFkNDU3MDEyZWRlOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxMTE4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmYxN2ExZjFiYjI4YzRlMzViZWRmZmQ1ZjA3YTMxZjVhNjE1ZjQ2YmM1Y2Q2YzdkYmI2ZDcwNDIzNjA0MzI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vhVV8oN84ViNgRtNqaWIc8FF1iGkE1KGjCcVBHYMSU0)
> 
> 其实我也搞不懂改了lwjgl3会有什么卵用，反而会影响老mod兼容性

虽然但是能不能看看https://github.com/FCL-Team/FoldCraftLauncher/issues/148

**Comment by REYXTE** [comment]
> ![Screenshot_20231206_113904_QQ.jpg](https://private-user-images.githubusercontent.com/110681414/288273471-6ece5542-6d24-4d89-a1c6-ad457012ede8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NjE3ODksIm5iZiI6MTcwMTg2MTQ4OSwicGF0aCI6Ii8xMTA2ODE0MTQvMjg4MjczNDcxLTZlY2U1NTQyLTZkMjQtNGQ4OS1hMWM2LWFkNDU3MDEyZWRlOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxMTE4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmYxN2ExZjFiYjI4YzRlMzViZWRmZmQ1ZjA3YTMxZjVhNjE1ZjQ2YmM1Y2Q2YzdkYmI2ZDcwNDIzNjA0MzI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vhVV8oN84ViNgRtNqaWIc8FF1iGkE1KGjCcVBHYMSU0)
> 
> 其实我也搞不懂改了lwjgl3会有什么卵用，反而会影响老mod兼容性

另外Cleanroom是Forge分支，还有那个是Java21，Java高版本的性能提示不会还不知道吧.....最主要的是kappa_maintainer说了目前测试只有HMCL(PC)能启动，因为其他启动器都自作聪明地装了lwjgl2或者检测了什么兼容性
