### ISSUE TITLE
just a feature request

### ISSUE THREAD

**Issue by ImaDoor2785** [FCL-Team/FoldCraftLauncher#16]
the launcher runs amazing btw i wasnt expecting much but this is impressive
can you pls add otg keyboard and mouse support

**Comment by LegacyGamerHD** [comment]
> the launcher runs amazing btw i wasnt expecting much but this is impressive can you pls add otg keyboard and mouse support

There aren't controls rn u believe so how do you play

**Comment by ImaDoor2785** [comment]
i wasn't playing yet what i meant where the load times and ui were great

amd i was just ingame

**Comment by Tiger56c** [comment]
What date is foldcraft launcher gonna release??

**Comment by ImaDoor2785** [comment]
i don't think anyone knows yet 
im gonna close this now
