### ISSUE TITLE
无法运行旧版本的任何模组加载器

### ISSUE THREAD

**Issue by REYXTE** [FCL-Team/FoldCraftLauncher#160]
### Launcher Version

1.1.0

### Device Information

Android12

### Problem Description

在我的世界b1.7.3-1.5.2如果装载Forge.Legacy Fabric或是Risugami's ModLoader那么只有1.2.5可以进入，剩下的版本都无法进入，我真的搞不懂为什么进不去，Pojavlauncher也是一样，无限的卡加载虽然你可能会说，玩什么老版本之类的但是还是想体验一下旧版..........比如BTW(比狼好)。

### Java

Java8

### Renderer

holy

### Game Version

b1.7-1.5.2

### Modifications Made to the Game

Forge,Legacy Fabric,Risugami's ModLoader

**Comment by REYXTE** [comment]
删除

**Comment by root-S7** [comment]
https://www.mcmod.cn/class/8621.html

**Comment by REYXTE** [comment]
> https://www.mcmod.cn/class/8621.html

这个东西无用，我删这个是因为Forge的事我解决了剩下的也不玩了。
