### ISSUE TITLE
未知原因崩溃

### ISSUE THREAD

**Issue by BallonAirr** [FCL-Team/FoldCraftLauncher#161]
### Launcher Version

1.1.0

### Device Information

OPPOA93S,Android11,arm64

### Problem Description

[crash-2023-12-09_13.04.04-client.txt](https://github.com/FCL-Team/FoldCraftLauncher/files/13622751/crash-2023-12-09_13.04.04-client.txt)
[latest_game.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13622752/latest_game.log)

### Java

Java8

### Renderer

holygl

### Game Version

1.16.5

### Modifications Made to the Game

forge 18mod

### Launcher Crash Report

[latest_game.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13622755/latest_game.log)

### Launcher Log File

[latest_game.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13622756/latest_game.log)

**Comment by root-S7** [comment]
尝试一下使用离线账户是否崩溃呢？
