### ISSUE TITLE
关于下载完整合包后，整合包文件是否存在的问题

### ISSUE THREAD

**Issue by deep-dark-forest** [FCL-Team/FoldCraftLauncher#163]
下载整合包以后不是会先有一个.zip文件然后再去安装吗，这个东西它是会在安装完以后自动删除，还是怎么样？如果我在下载完以后，安装之前，退出了启动器，那么这个整合包文件还存在吗

**Comment by deep-dark-forest** [comment]
Emm拜托咱整个discussion吧

**Comment by ShirosakiMio** [comment]
/data/user/0/com.tungsten.fcl/cache/
