### ISSUE TITLE
启动1.20.1整合包崩溃

### ISSUE THREAD

**Issue by xiaoniangaoh** [FCL-Team/FoldCraftLauncher#166]
### Launcher Version

1.1.0

### Device Information

Could not initialize classcom .sun .jna.Native

### Problem Description

下载完整合包启动就崩溃了
![Screenshot_20231214_113342_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/112637370/1c680db6-7540-4ff1-b7a2-d9e8dac1ffa9)

### Java

java 17

### Renderer

实测所有渲染器都会崩不过我现在用的是open gl 4.6仅支持1.17+的这个也会崩溃

### Game Version

1.20.1

### Modifications Made to the Game

Forge

### Game Crash Report

[fcl-latest7960990380575964594.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13668114/fcl-latest7960990380575964594.log)

### Launcher Log File

[fcl-exported-logs-2023-12-14T11-49-14.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13668126/fcl-exported-logs-2023-12-14T11-49-14.log)

**Comment by xiaoniangaoh** [comment]
整合包模组是这些
•[Vampirism - Become a vampire! (by maxanier)](https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire)
•[Werewolves - Become a Beast! (by Cheaterpaul)](https://www.curseforge.com/minecraft/mc-mods/werewolves-become-a-beast)
•[Create : Armory (by Chilllliii)](https://www.curseforge.com/minecraft/mc-mods/create-armory)
•[Chisels & Bits - For Forge (by AlgorithmX2)](https://www.curseforge.com/minecraft/mc-mods/chisels-bits)
•[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
•[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
•[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
•[Create: Diesel Generators (by george8188262)](https://www.curseforge.com/minecraft/mc-mods/create-diesel-generators)
•[Applied Energistics 2 (by thetechnici4n)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
•[Create Stuff & Additions (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions)
•[SlashBlade (by flammpfeil)](https://www.curseforge.com/minecraft/mc-mods/slashblade)
•[Create: New Age (by nilBlade)](https://www.curseforge.com/minecraft/mc-mods/create-new-age)
•[Avaritia Lite (by bullfighter2009)](https://www.curseforge.com/minecraft/mc-mods/avaritia-lite)
•[Create: Steam 'n' Rails (by mattentosh)](https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails)
•[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
•[Create Enchantment Industry (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry)
•[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
•[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
•[Botarium (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/botarium)
•[Avaritia Continued (by Ocle_42)](https://www.curseforge.com/minecraft/mc-mods/avaritia-continued)
•[Create Sabers (by Leroidesafk)](https://www.curseforge.com/minecraft/mc-mods/create-sabers)
•[Age of Weapons (by XxRexRaptorxX)](https://www.curseforge.com/minecraft/mc-mods/age-of-weapons)
•[Mekanism (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism)

**Comment by VexroGitHub** [comment]
I don't think Create supports fold craft.
Check with staff

**Comment by xiaoniangaoh** [comment]
> I don't think foldcraft supports the create mod我不认为 foldcraft 支持 create mod Check with staff 请与工作人员联系

没有加机械动力附属是支持的

**Comment by blmulang** [comment]
我也这样，不知道啥原因，加入服务器和进入本地游戏都这样
启动器是最新的1.1.1
游戏版本是：1.20.2
崩溃日志：[fcl-latest5238041666051431117.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13781597/fcl-latest5238041666051431117.log)
崩溃图片：
![1](https://github.com/FCL-Team/FoldCraftLauncher/assets/48040829/89a668a4-7097-4dda-aab4-ad6e5a907cb5)

**Comment by root-S7** [comment]
> 我也这样，不知道啥原因，加入服务器和进入本地游戏都这样
> 启动器是最新的1.1.1
> 游戏版本是：1.20.2
> 崩溃日志：[fcl-latest5238041666051431117.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13781597/fcl-latest5238041666051431117.log)
> 崩溃图片：
> ![1](https://github.com/FCL-Team/FoldCraftLauncher/assets/48040829/89a668a4-7097-4dda-aab4-ad6e5a907cb5)
> mod列表：
> ![Screenshot_20231228_051805](https://github.com/FCL-Team/FoldCraftLauncher/assets/48040829/3dd5289a-dd44-45b3-a5cd-4370a329d198)
> 

不要加钠呀，说了几遍了，还有就是但凡你看下日志文件也不至于来问了

**Comment by root-S7** [comment]
> ### Launcher Version
> 
> 1.1.0
> 
> ### Device Information
> 
> Could not initialize classcom .sun .jna.Native
> 
> ### Problem Description
> 
> 下载完整合包启动就崩溃了
> ![Screenshot_20231214_113342_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/112637370/1c680db6-7540-4ff1-b7a2-d9e8dac1ffa9)
> 
> 
> ### Java
> 
> java 17
> 
> ### Renderer
> 
> 实测所有渲染器都会崩不过我现在用的是open gl 4.6仅支持1.17+的这个也会崩溃
> 
> ### Game Version
> 
> 1.20.1
> 
> ### Modifications Made to the Game
> 
> Forge
> 
> ### Game Crash Report
> 
> [fcl-latest7960990380575964594.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13668114/fcl-latest7960990380575964594.log)
> 
> 
> ### Launcher Crash Report
> 
> _No response_
> 
> ### Launcher Log File
> 
> [fcl-exported-logs-2023-12-14T11-49-14.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13668126/fcl-exported-logs-2023-12-14T11-49-14.log)
> 

非高通平台请使用修复版机械动力，这句话我也不知道说了几遍了(意思是只要不是高通平台都要使用修复版mod)

**Comment by xiaoniangaoh** [comment]
> 我也这样，不知道啥原因，加入服务器和进入本地游戏都这样 启动器是最新的1.1.1 游戏版本是：1.20.2 崩溃日志：[fcl-latest5238041666051431117.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13781597/fcl-latest5238041666051431117.log) 崩溃图片： ![1](https://private-user-images.githubusercontent.com/48040829/293099352-89a668a4-7097-4dda-aab4-ad6e5a907cb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3Njc0MTUsIm5iZiI6MTcwMzc2NzExNSwicGF0aCI6Ii80ODA0MDgyOS8yOTMwOTkzNTItODlhNjY4YTQtNzA5Ny00ZGRhLWFhYjQtYWQ2ZTVhOTA3Y2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDEyMzgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2OTg0NjgzY2E2ZDg3N2Q3MTJjN2MzNDkzMTg4MTUzZDU3MGUyNTYxZWFhNjY2ZDllMDQwNGQ0MDQ4OGZlMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XVRhGep1W2gi3celL7sE0sGJB1saXGKRBCzd1CMaw-c) mod列表： ![Screenshot_20231228_051805](https://private-user-images.githubusercontent.com/48040829/293101125-3dd5289a-dd44-45b3-a5cd-4370a329d198.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3Njc0MTUsIm5iZiI6MTcwMzc2NzExNSwicGF0aCI6Ii80ODA0MDgyOS8yOTMxMDExMjUtM2RkNTI4OWEtZGQ0NC00NWIzLWE1Y2QtNDM3MGEzMjlkMTk4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDEyMzgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYzE4ZjRiNjI3MmFjMDlhYzYzMDJmZGI3ZGFlYjBmNjEyMzkyMmViYmY0ZmQ2NGMyMmUwNDQzYWE3ZDQ4ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dRIHMDykPpjcZVXqDfKkKM-h1KBbT-VYT1XBfNd4ZMc)

有没有解决方法？

**Comment by blmulang** [comment]
> > 我也这样，不知道啥原因，加入服务器并进入本地游戏都这样启动器是最新的1.1.1游戏版本是：1.20.2崩溃日志：[fcl-latest5238041666051431117.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13781597/fcl-latest5238041666051431117.log)图片：![1](https://private-user-images.githubusercontent.com/48040829/293099352-89a668a4-7097-4dda-aab4-ad6e5a907cb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3Njc0MTUsIm5iZiI6MTcwMzc2NzExNSwicGF0aCI6Ii80ODA0MDgyOS8yOTMwOTkzNTItODlhNjY4YTQtNzA5Ny00ZGRhLWFhYjQtYWQ2ZTVhOTA3Y2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDEyMzgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2OTg0NjgzY2E2ZDg3N2Q3MTJjN2MzNDkzMTg4MTUzZDU3MGUyNTYxZWFhNjY2ZDllMDQwNGQ0MDQ4OGZlMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XVRhGep1W2gi3celL7sE0sGJB1saXGKRBCzd1CMaw-c)mod崩溃列表：![截图_20231228_051805](https://private-user-images.githubusercontent.com/48040829/293101125-3dd5289a-dd44-45b3-a5cd-4370a329d198.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3Njc0MTUsIm5iZiI6MTcwMzc2NzExNSwicGF0aCI6Ii80ODA0MDgyOS8yOTMxMDExMjUtM2RkNTI4OWEtZGQ0NC00NWIzLWE1Y2QtNDM3MGEzMjlkMTk4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDEyMzgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYzE4ZjRiNjI3MmFjMDlhYzYzMDJmZGI3ZGFlYjBmNjEyMzkyMmViYmY0ZmQ2NGMyMmUwNDQzYWE3ZDQ4ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dRIHMDykPpjcZVXqDfKkKM-h1KBbT-VYT1XBfNd4ZMc)
> 
> 有没有解决方法？

就按楼上这个root-S7  老哥说的 去掉 iris、sodium这两个就进去了
