### ISSUE TITLE
FCL新图标

### ISSUE THREAD

**Issue by 2022001111** [FCL-Team/FoldCraftLauncher#167]

**Comment by root-S7** [comment]
?

**Comment by 2022001111** [comment]
有人啊，我想发个图，但是发不了

**Comment by 2022001111** [comment]
GitHub手机端

**Comment by 2022001111** [comment]
![1701493348397](https://github.com/FCL-Team/FoldCraftLauncher/assets/153972627/4467f03f-5591-4c68-9335-ddc18c76fbbd)
好吧换网页
