### ISSUE TITLE
能否给键位单独弄个文件夹，我的设备无法分享键位和导出日志

### ISSUE THREAD

**Issue by mingzizhijie** [FCL-Team/FoldCraftLauncher#170]
### Description

键位单独文件夹，可以直接用文件管理器等直接找到，我的设备无法导出键位和导出日志

### Why

设备无法分享键位，和导出键位

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/7554328594
