### ISSUE TITLE
渲染器貌似未能正确被修改

### ISSUE THREAD

**Issue by nanmulifeng** [FCL-Team/FoldCraftLauncher#176]
### Launcher Version

1.1.1

### Device Information

vivo Y33s,android 12,arm64

### Problem Description

_在全局设置中更改渲染器为Vulkan Zink(其他渲染器一样),后启动游戏崩溃,崩溃后日志显示渲染器仍为Holy GL4ES_

### Java

java8

### Renderer

Holy GL4ES

### Game Version

1.16.5

### Modifications Made to the Game

fabric 0.14.21,Sodium 0.2.0+build.4

**Comment by zkitefly** [comment]
确定不是在全局游戏设置修改，然后该版本打开了特定游戏设置所导致的？

**Comment by nanmulifeng** [comment]
> 确定不是在全局游戏设置修改，然后该版本打开了特定游戏设置所导致的？
特定游戏设置为什么是默认打开的?我都没有打开过
