### ISSUE TITLE
fold craft launcher Crash

### ISSUE THREAD

**Issue by Rakib12345yb** [FCL-Team/FoldCraftLauncher#177]
### Launcher Version

1.1.1

### Device Information

samsung galaxy A13,android 13,armeabi-v7a

### Problem Description

i am Launching forge fold craft launcher Crash

### Java

17

### Renderer

Holy-GL4ES

### Game Version

1.20.1

### Modifications Made to the Game

FORGE 47.2.19,OPTIFINE HD_U_I6

### Launcher Log File

[latest.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13802392/latest.log)

**Comment by FrostNovaHD** [comment]
User eror check log on own a dublicated mod

**Comment by Rakib12345yb** [comment]
Launcher Crash Report
[fcl-latest173708456144537105.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13802440/fcl-latest173708456144537105.log)

**Comment by Rakib12345yb** [comment]
> User eror check log on own a dublicated mod

again Launcher Crash
