### ISSUE TITLE
forge not launch 

### ISSUE THREAD

**Issue by Rakib12345yb** [FCL-Team/FoldCraftLauncher#178]
### Launcher Version

1.1.1

### Device Information

samsung galaxy A13,android 13,armeabi-v7a

### Problem Description

forge game not launch 
Launcher Crash

### Java

17

### Renderer

Holy-GL4ES

### Game Version

1.20.1

### Modifications Made to the Game

FORGE 47.2.19

### Game Crash Report

[latest_game.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13802496/latest_game.log)

### Launcher Crash Report

[fcl-latest7056520152781508565.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13802497/fcl-latest7056520152781508565.log)

### Launcher Log File

[latest.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13802498/latest.log)

**Comment by root-S7** [comment]
”DistantHorizons-2.0.1-a-1.20.1.jar“ can not run with "OpenGL ES"
