### ISSUE TITLE
Extract release date

### ISSUE THREAD

**Issue by LithuanianBoi41** [FCL-Team/FoldCraftLauncher#18]
Extract release date of Launcher

**Comment by LegacyGamerHD** [comment]
No release date

**Comment by Tiger56c** [comment]
> No release date

Wdym no release date??

**Comment by Tiger56c** [comment]
He said when is the release date and im asking that to so when is the release date?

**Comment by LegacyGamerHD** [comment]
> He said when is the release date and im asking that to so when is the release date?

there is no release date yet

**Comment by Tiger56c** [comment]
?
