### ISSUE TITLE
Neoforge自动安装无法安装

### ISSUE THREAD

**Issue by REYXTE** [FCL-Team/FoldCraftLauncher#184]
### Launcher Version

1.1.2

### Device Information

Android12 Arm64

### Problem Description

如果用Neoforge自动安装会出现这种情况
![Screenshot_2024_0109_192254_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/139873242/c1cf1eae-82c0-4af4-9b46-c1dfb8ae63c9)
下载源都试了都一样

### Java

这个似乎不需要)

### Renderer

holy

### Game Version

1.20.1

### Modifications Made to the Game

无

**Comment by zkitefly** [comment]
该问题为 BMCLAPI 问题，已上报给作者，稍后应该就能修复

**Comment by bangbang93** [comment]
![image](https://github.com/FCL-Team/FoldCraftLauncher/assets/3430784/78a6ecce-601e-40f7-b5d8-369e792e4517)
neoforge修改了版本号规则导致识别异常，先临时补丁用着

**Comment by 8MiYile** [comment]
issue label
invaid; bmclapi-bug
