### ISSUE TITLE
increase sensitivity.

### ISSUE THREAD

**Issue by MDEmonY** [FCL-Team/FoldCraftLauncher#185]
### Description

sensitivity of fold craft launcher is too much low you should increase it.

### Why

For better pvp, gameplay, experience.....etc.

**Comment by ShirosakiMio** [comment]
the default sensitivity is enough for me

**Comment by MDEmonY** [comment]
> the default sensitivity is enough for me

i've set sensitivity to max but not enough for pvp...

**Comment by ShirosakiMio** [comment]
In fact, you can increase mouse sensitivity in the FCL game menu

**Comment by MDEmonY** [comment]
> In fact, you can increase mouse sensitivity in the FCL game menu

I'm not saying about mouse sensitivity, I'm saying about sensitivity. it's too low and if i decrease resolution then the sensitivity is too much low ( not playable for pvp or etc.

**Comment by ShirosakiMio** [comment]
the mouse sensitivity  in FCL game muenu is also useful for touch

**Comment by ShirosakiMio** [comment]
if decrease resolution ... you can tyr this.
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/7554328594

**Comment by ShirosakiMio** [comment]
I fixed

**Comment by MDEmonY** [comment]
> if decrease resolution ... you can tyr this. https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/7554328594

ok, THANKS
