### ISSUE TITLE
Game crash when allocation a ram

### ISSUE THREAD

**Issue by DevLOL243** [FCL-Team/FoldCraftLauncher#186]
### Launcher Version

1.1.2

### Device Information

Samsung F13, Android 13, 32 bit

### Problem Description

I set my memory allocation in 2070 in holy render and in the loading phase launcher crash continuously. I try everything but nothing work.
This same thing happened in version 1.1.0 version of Fold Craft Launcher 

### Java

Java 17

### Renderer

Holy -GL4ES

### Game Version

1.20.1

### Modifications Made to the Game

Sodium

### Game Crash Report

There is no crash report only game crash.

### Launcher Log File

[Uploading latest_game.log…]()

**Comment by ShirosakiMio** [comment]
no log no help
