### ISSUE TITLE
When will the beta version be released?

### ISSUE THREAD

**Issue by HopiHopy** [FCL-Team/FoldCraftLauncher#19]
I can't wait to experience the beta version.
When will the beta version be released?

**Comment by didntpenguin** [comment]
> 

check out youtube...

**Comment by MoonKnightBhai** [comment]
> I can't wait to experience the beta version. When will the beta version be released?

Tungsten is working on the Launcher wait little more coz controls  haven't been added yet so even if he release the apk u will not be able to move wait till for all the basic stuff gets added i think then he will release a playable version
