### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MDEmonY** [FCL-Team/FoldCraftLauncher#193]
### Launcher Version

1.1.2

### Device Information

Redmi A1+, Android 12, 32 bit

### Problem Description

crashing everytime when i tap on settings or launch..

### Java

Java 8

### Renderer

Holy render

### Game Version

1.16.5

### Modifications Made to the Game

fabric (sodium)

### Launcher Crash Report

[crash_report9117321796059777918.txt](https://github.com/FCL-Team/FoldCraftLauncher/files/13897105/crash_report9117321796059777918.txt)

### Launcher Log File

[fcl-exported-logs-2024-01-11T09-51-21.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13897109/fcl-exported-logs-2024-01-11T09-51-21.log)

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/7484449433

**Comment by MDEmonY** [comment]
> https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/7484449433

what to do with this

**Comment by MDEmonY** [comment]
![Uploading Screenshot_20240111-151126.png…]()
