### ISSUE TITLE
JDK

### ISSUE THREAD

**Issue by ManyullynSword** [FCL-Team/FoldCraftLauncher#194]
### Description

可否支持手动在启动器中安装 PojavLauncher 的高新 JDK？

### Why

首先，FCL 可以使用 Pojav 的 JDK（也有可能本来就是其修改），其次 Pojav 的 JDK 一直在更新，如果支持手动导入就无需在安装包中改包，且可以根据情况选择不同的 JDK。

**Comment by Tungstend** [comment]
已更新支持jre11，jre21
