### ISSUE TITLE
【小BUG】Luncher crashed when execute a jar which dont have method main(String[] args)

### ISSUE THREAD

**Issue by EnderLight3336** [FCL-Team/FoldCraftLauncher#196]
### Launcher Version

1.1.2

### Device Information

华为畅享9plus， hmOS2.1.0，  aarch64

### Problem Description

Hi, I'm bug finder
当运行jar时，运行一个不含main方法的jar会使启动器崩溃
建议：启动前检查是否具有main方法

### Launcher Crash Report

[fcl-latest2250625094413424591.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13905137/fcl-latest2250625094413424591.log)

**Comment by ShirosakiMio** [comment]
检查不了一点
