### ISSUE TITLE
Everything is normal on the computer, Android cannot start

### ISSUE THREAD

**Issue by w15736776759** [FCL-Team/FoldCraftLauncher#197]
### Launcher Version

1.1.2

### Device Information

OnePlus 6T

### Problem Description

I put the Java game integration package of my computer on Android and it couldn't start,Everything is normal on the computer

### Java

JAVA17

### Renderer

Holy-GL4ES

### Game Version

1.20.1

### Modifications Made to the Game

fabric

### Launcher Log File

[fcl-latest4939401205990666003.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13918475/fcl-latest4939401205990666003.log)

**Comment by zkitefly** [comment]
切换成其他渲染器再启动游戏

**Comment by root-S7** [comment]
at io.github.reserveword.imblocker.IMManager.<clinit>(IMManager.java:21)
为啥不能访问你就看图片吧
![image](https://github.com/FCL-Team/FoldCraftLauncher/assets/110681414/fb74c4b7-98ac-4183-90b6-120a330f1ef7)


简单来说这mod是给windows平台用的，咋可能给其他平台用呢

**Comment by root-S7** [comment]
你如果要用这个mod那么只能去下wine，然后在wine内跑

**Comment by w15736776759** [comment]
> 你如果要用这个mod那么只能去下wine，然后在wine内跑
我直接删了,进去了,然后创建世界又崩了..
[fcl-latest1393601121089215566.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13918921/fcl-latest1393601121089215566.log)

**Comment by root-S7** [comment]
> > 你如果要用这个mod那么只能去下wine，然后在wine内跑
> 
> 我直接删了,可以进到主界面了,然后创建世界又崩了.. [fcl-latest1393601121089215566.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13918921/fcl-latest1393601121089215566.log)

at dynamic_fps.impl.DynamicFPSMod.isLevelCoveredByScreen(DynamicFPSMod.java:142)

DynamicFPSMod

**Comment by w15736776759** [comment]
> > > 你如果要用这个mod那么只能去下wine，然后在wine内跑
> > 
> > 
> > 我直接删了,可以进到主界面了,然后创建世界又崩了.. [fcl-latest1393601121089215566.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13918921/fcl-latest1393601121089215566.log)
> 
> at dynamic_fps.impl.DynamicFPSMod.isLevelCoveredByScreen(DynamicFPSMod.java:142)
> 
> DynamicFPSMod

删了,进世界还是崩溃...

**Comment by w15736776759** [comment]
> 继续发日志文件，还有，不是所有mod都能在手机上能跑的。只要是跟平台绑定的MOD，JE上渲染类MOD（各种优化类MOD）都存在兼容性问题

[fcl-latest7103962458933670411.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13919818/fcl-latest7103962458933670411.log)

**Comment by root-S7** [comment]
钠最新版肯定不能在手机上使用的

**Comment by w15736776759** [comment]
> 钠最新版肯定不能在手机上使用的

那还有其他的吗?

**Comment by root-S7** [comment]
> > 钠最新版肯定不能在手机上使用的
> 
> 那还有其他的吗?

.我怎么知道还有啥呢，这是你运行到这里日志文件的崩溃
