### ISSUE TITLE
Adding Render

### ISSUE THREAD

**Issue by MDEmonY** [FCL-Team/FoldCraftLauncher#198]
### Description

Actually i want to add jre 17 on fold craft launcher like PojavLauncher, because i want to sodium but it's not running i saw videos on youtube and on those videos i saw they have used jre 17. So, I think you should add it...

### Why

To get best experience on fold craft launcher like PojavLauncher.

**Comment by ShirosakiMio** [comment]
> ### Description
> Actually i want to add jre 17 on fold craft launcher like PojavLauncher, because i want to sodium but it's not running i saw videos on youtube and on those videos i saw they have used jre 17. So, I think you should add it...
> 
> ### Why
> To get best experience on fold craft launcher like PojavLauncher.

jre 17 is needed to run 1.17+. So it's already added. Sodium is not running caused by the OpenGL. No way to fix as I konw. Also crash with pojav since sodium updated to 0.5

**Comment by MDEmonY** [comment]
> > ### Description
> > Actually i want to add jre 17 on fold craft launcher like PojavLauncher, because i want to sodium but it's not running i saw videos on youtube and on those videos i saw they have used jre 17. So, I think you should add it...
> > ### Why
> > To get best experience on fold craft launcher like PojavLauncher.
> 
> jre 17 is needed to run 1.17+. So it's already added. Sodium is not running caused by the OpenGL. No way to fix as I konw. Also crash with pojav since sodium updated to 0.5

do you know how to fix this problem in fold craft launcher..?

**Comment by MDEmonY** [comment]
> > ### Description
> > Actually i want to add jre 17 on fold craft launcher like PojavLauncher, because i want to sodium but it's not running i saw videos on youtube and on those videos i saw they have used jre 17. So, I think you should add it...
> > ### Why
> > To get best experience on fold craft launcher like PojavLauncher.
> 
> jre 17 is needed to run 1.17+. So it's already added. Sodium is not running caused by the OpenGL. No way to fix as I konw. Also crash with pojav since sodium updated to 0.5

do you know how to fix this problem in fold craft launcher..?

**Comment by ShirosakiMio** [comment]
> > > ### Description
> > > Actually i want to add jre 17 on fold craft launcher like PojavLauncher, because i want to sodium but it's not running i saw videos on youtube and on those videos i saw they have used jre 17. So, I think you should add it...
> > > ### Why
> > > To get best experience on fold craft launcher like PojavLauncher.
> > 
> > 
> > jre 17 is needed to run 1.17+. So it's already added. Sodium is not running caused by the OpenGL. No way to fix as I konw. Also crash with pojav since sodium updated to 0.5
> 
> do you know how to fix this problem in fold craft launcher..?

don't use sodium 0.5+
