### ISSUE TITLE
[较严重][游戏体验BUG]屏幕画面与实际点击位置不符合

### ISSUE THREAD

**Issue by EnderLight3336** [FCL-Team/FoldCraftLauncher#199]
### Launcher Version

1.1.2

### Device Information

华为畅享9plus， hmOS2.1.0， aarch64

### Problem Description

Hi, I'm bug finder, I come back again!
描述：当打开键盘时，会造成游戏画面跟随键盘上移，但可以点击的位置不会，会造成点击想要点的位置，程序实际点击到该位置上面的位置

https://github.com/FCL-Team/FoldCraftLauncher/assets/95128322/69a4fab2-46fd-4939-9775-044873867965

### Java

default

### Renderer

Holy-GL4ES

### Game Version

1.8.9(tested) 1.12.2(tested)  seem all version?

### Modifications Made to the Game

1.8.9(optfine HD_U_M5) 1.12.2(optfine HD_U_G5) 1.12.2(with nothing)

**Comment by EnderLight3336** [comment]
建议：部分借鉴pojav代码

**Comment by root-S7** [comment]
可能作者只是单纯为了实现你聊天栏能输入内容，没考虑那么多

**Comment by ShirosakiMio** [comment]
问题是，为什么一定要开着软键盘去点游戏内容

**Comment by Vera-Firefly** [comment]
这并不是启动器造成的,你可以开启游戏键盘解决
