### ISSUE TITLE
定义参数jar启动器

### ISSUE THREAD

**Issue by hyplant** [FCL-Team/FoldCraftLauncher#201]
### Description

添加一个可以像pojav那样以自定义参数启动jar文件的功能。
建议通过长按执行jar按钮打开。
下图为pojav中的自定义参数jar启动功能
![Screenshot_20240113-115733_PojavLauncher (Minecraft Java Edition fer Android)](https://github.com/FCL-Team/FoldCraftLauncher/assets/86937725/87f80536-ce8c-4c73-8f67-75326b8b86fd)

### Why

运行一些模组安装器时，可添加某些额外的参数来实现一些功能，例如不要自动清除临时文件。

**Comment by ShirosakiMio** [comment]
加上了
