### ISSUE TITLE
[Feature] 添加《从互联网下载布局》功能

### ISSUE THREAD

**Issue by zkitefly** [FCL-Team/FoldCraftLauncher#203]
### Description

RT

### Why

这样可以减少找文件的难度，快速安装，对小白很友好

**Comment by Tungstend** [comment]
真有人会上传么，除非此人正好有一台可用的服务器，或者我们自己运营一个仓库，还得有有人负责筛选

**Comment by zkitefly** [comment]
这个功能就像《从互联网下载整合包》功能一样，输入下载直链后启动器直接安装，可以省去找文件的步骤，对小白很友好

关于服务器，可以放到 gitcode 等托管平台

**Comment by 2022001111** [comment]
这个好

**Comment by DSY-xiaoluo** [comment]
关闭吧，已经有了
