### ISSUE TITLE
分开原生库或只留arm64v8a原生库减少安装包体积？

### ISSUE THREAD

**Issue by Emperormummy** [FCL-Team/FoldCraftLauncher#204]
可否分开成几个安装包（同时保留含全部原生库的版本）

**Comment by ShirosakiMio** [comment]
似乎只能自动分开lib里包含的架构，无法自动分开assets里的java，这样做实际上减少的体积并没有多少
![image](https://github.com/FCL-Team/FoldCraftLauncher/assets/19233890/de619629-72a8-44ce-88f2-cde5dd33aa4b)

**Comment by root-S7** [comment]
> 似乎只能自动分开lib里包含的架构，无法自动分开assets里的java，这样做实际上减少的体积并没有多少 ![image](https://private-user-images.githubusercontent.com/19233890/296530644-de619629-72a8-44ce-88f2-cde5dd33aa4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMDkxNDUsIm5iZiI6MTcwNTIwODg0NSwicGF0aCI6Ii8xOTIzMzg5MC8yOTY1MzA2NDQtZGU2MTk2MjktNzJhOC00NGNlLTg4ZjItY2RlNWRkMzNhYTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDA1MDcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlM2EwNjk1MzgzNGE3ZmUwMGU5ODQ4NjM2M2FkYTc1OTE5ZTRjNzczOGFlZmY1ZGY0MzQ2MmIyYThhNjMyNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xqyFihb7AKlFX9WN9xKt-KWTctLVmwnrfimzD9Hu144)

其实可以减少很多，这是我打包的：
![image](https://github.com/FCL-Team/FoldCraftLauncher/assets/110681414/6d9676e7-ca24-4401-9b5e-432aa932307e)

如果只打包armv8的lib和java环境实际上可以做到60MB左右大小
![image](https://github.com/FCL-Team/FoldCraftLauncher/assets/110681414/f327f47a-8826-47e3-ab8c-73a5ed602553)

**Comment by root-S7** [comment]
但是java的话每次打包只能先把非arm8平台的放到回收站，然后打完包在拖回项目

**Comment by root-S7** [comment]
我觉的吧，java环境只需要armv7，armv8环境就好了
Android X86平台我觉得除了AVD可能会用以外，应该没人在电脑上模拟器跑吧

**Comment by ShirosakiMio** [comment]
ChromeOS：？

**Comment by ShirosakiMio** [comment]
不能自动化操作的话太麻烦

**Comment by ShirosakiMio** [comment]
仅仅分开lib下的so减少的大小收益并不值得分包全部上传

**Comment by ShirosakiMio** [comment]
![image](https://github.com/FCL-Team/FoldCraftLauncher/assets/19233890/529da7be-76d2-4bb8-8cbb-7e712ac2a34b)
