### ISSUE TITLE
twitch-platformer-X.XX.jar No Installed

### ISSUE THREAD

**Issue by LucasLiveVault** [FCL-Team/FoldCraftLauncher#205]
### Launcher Version

1.1.3

### Device Information

Motorola G9 Power, Android 11, aarch64, 4 RAM, 128 ROM

### Problem Description

Twitch Platformer It does not install causing the game to not run or crashes (screenshot expanded for more details)
![Screenshot_20240113-130042](https://github.com/FCL-Team/FoldCraftLauncher/assets/156531774/ee036322-2604-499c-bcc8-29899419f30b)

### Java

Auto

### Renderer

Default

### Game Version

All Versions

### Modifications Made to the Game

Nothing

### Game Crash Report

No Crashes

### Launcher Crash Report

No Crash Report

### Launcher Log File

No Log File

**Comment by ShirosakiMio** [comment]
![Screenshot_2024-01-14-08-15-23-619_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/19233890/3619083f-bb28-4557-baf0-61545a1ebd4d)
Just open the "Do not check the game integrity"

**Comment by LucasLiveVault** [comment]
Thanks!

**Comment by LucasLiveVault** [comment]
Thanks!
