### ISSUE TITLE
希望有使用自定义JAVA的功能。

### ISSUE THREAD

**Issue by Merak-xing** [FCL-Team/FoldCraftLauncher#206]
### Description

希望能够实现自己下载三方JAVA，在软件上使用的功能

### Why

官方JAVA吃内存比较大，三方的有些时候手机优化比较好

**Comment by Tungstend** [comment]
哪有适配Android的第三方Java

**Comment by root-S7** [comment]
哪能像电脑上那么自由呢。Android这边网上下的linux aarch64的jdk没办法创建symlink的(意思是非根用户别想了)。你现在在安卓平台上能跑的这些java运行环境都是把符号链接改成普通文件了的

**Comment by root-S7** [comment]
用java写的项目就别考虑内存占用大问题了。你这么想节约内存可以在启动参数加个禁用jit。不过这样运行效率会爆炸(但起到了省内存目的)
![Screenshot_20240114_233819_QQ](https://github.com/FCL-Team/FoldCraftLauncher/assets/110681414/6dc9300e-113d-4358-a27a-9d4201b2fe8c)

**Comment by ShirosakiMio** [comment]
没有第三方给安卓提供java
