### ISSUE TITLE
owo-lib causing a crash on FoldCraftLauncher when exiting the creative 

### ISSUE THREAD

**Issue by RoomAlex68** [FCL-Team/FoldCraftLauncher#207]
### Launcher Version

1.1.3

### Device Information

Samsung Galaxy 22

### Problem Description

So when I have owo-lib installed when playing minecraft on Foldcraft launcher. When I create a world and Open the Creative Menu and Exit out of it. It freezes for a Bit and Crashes with no crash log but It gives me the latest Log of what happened. Note the Crash normally happens on Holy GL4ES and when I was using Zink 

### Java

17

### Renderer

Zink(Can Also happen on Holy GL4ES)

### Game Version

1.20.1

### Modifications Made to the Game

Fabric 

### Game Crash Report

Latest Log:
[ezyzip (1).zip](https://github.com/FCL-Team/FoldCraftLauncher/files/13932606/ezyzip.1.zip)

Video MP4:
https://github.com/FCL-Team/FoldCraftLauncher/assets/85209177/e7b4d398-6611-413d-be39-bc04607376ad

**Comment by RoomAlex68** [comment]
Owo-lib doesn't crash when Exiting the Creative Menu on PojavLauncher

**Comment by ShirosakiMio** [comment]
I know. But there's no crash log. It's hard to fix

**Comment by ShirosakiMio** [comment]
Oh, I found the crash info on 1.20.3.

**Comment by ShirosakiMio** [comment]
download here
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/7523703011

**Comment by RoomAlex68** [comment]
Does the Patch apply for all OWO-LIB versions?
