### ISSUE TITLE
有关控制器的几个建议

### ISSUE THREAD

**Issue by hyplant** [FCL-Team/FoldCraftLauncher#208]
### Description

**1. 编辑按键和摇杆样式** √
    目前按键和摇杆样式一但的创建就无法编辑，希望可以提供编辑功能。
**2. 内部存储中的按键布局文件夹**  √
    把按键布局文件夹移动到内部存储，例如`/sdcard/FCL/controller`，以便使用文本编辑器进行进一步编辑。
**3. 更好的按键删除**  √
    目前删除按键时对长按的要求极高，手指不能有任何抖动。其实可以直接在点击按钮弹出的编辑页面中添加一个删除按钮，这样可以更便捷的删除按钮。
**4. 快速发送自定义键码** √
    在控制器材当中添加一个类似 _快捷输入_ 的功能，点击后将显示类似于 _编辑按键时选择键码_ 的页面，点击一个按钮以发送自定义键码。甚至还可以做得更好，例如长按任一个按键进入多选，可选择多个按键以模拟同时按下这些键。
**5. 快速切换鼠标模式** √
    为控制器按键添加一个新功能，可以切换鼠标模式为点击或拖动。
**6. 精简布局文件中的按键样式** √
    目前的按键布局文件中保留了每个按键的按键样式。其实可以将样式保存在一起，然后为每个按键添加一个属性，定义它使用了哪个样式。因为很多情况下，这些按键会使用重复的样式，将样式保存在一起可以减小文件体积。
**7. 更好的打开键盘功能**
    之前在使用 limbo 时，发现它的打开键盘功能再次点击不会关闭键盘，并且键盘上有一个回车键，而不是完成按钮。回车键可以按多次而不关闭键盘，完成按钮会直接关闭键盘。如果 fcl 中的打开键盘功能可以实现这种效果，使用键盘会更加便捷。其实不用考虑关闭键盘功能，因为键盘通常会自带一个关闭按钮，系统导航栏的返回键也可以直接关闭键盘。
**8. 控制器菜单按钮置于最顶层** √
    目前如果有按钮与控制器菜单按钮重叠，控制器菜单会无法被点击或拖动。应当将控制器菜单按钮置于其他控制器按钮之上，以避免这种情况。

**Comment by ShirosakiMio** [comment]
2/8已实现

**Comment by ShirosakiMio** [comment]
长按删除是大于400ms且x,y坐标移动不能大于1，确实判断的太严格

**Comment by hyplant** [comment]
根据目前使用下来的情况，长按删除摇杆和游戏内长按按钮发送键码的触发似乎仍存在问题，对长按的判定仍然很严格
