### ISSUE TITLE
Sesntivity

### ISSUE THREAD

**Issue by FrostNovaHD** [FCL-Team/FoldCraftLauncher#211]
### Launcher Version

1.1.3

### Device Information

Google Pixel 7 pro android 14 (qpr2)

### Problem Description

When lowering the resolution the sensitivity of moving around will be decreased

### Java

Doesnt matter

### Renderer

All

### Game Version

All

### Modifications Made to the Game

Doesnt matter

**Comment by ShirosakiMio** [comment]
fixed
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/7554328594
