### ISSUE TITLE
1.20.2以上版本无法运行

### ISSUE THREAD

**Issue by HalfShadow111** [FCL-Team/FoldCraftLauncher#213]
### Launcher Version

1.1.3

### Device Information

IQOO Z5, Android 13 arm64

### Problem Description

1.20.2以上版本（不包括1.20.2）都不能进入世界，一旦进入世界游戏会崩溃

### Java

Java 17

### Renderer

Holy-GL4ES

### Game Version

1.20.4

### Modifications Made to the Game

没有

### Game Crash Report

[crash-2024-01-19_01.11.56-client.txt](https://github.com/FCL-Team/FoldCraftLauncher/files/13979753/crash-2024-01-19_01.11.56-client.txt)

### Launcher Log File

[fcl-latest2069703245910681922.log](https://github.com/FCL-Team/FoldCraftLauncher/files/13979772/fcl-latest2069703245910681922.log)

**Comment by ShirosakiMio** [comment]
从这里下一个最新的看看
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/7554328594
