### ISSUE TITLE
Servers Down?, not loading

### ISSUE THREAD

**Issue by LucasLiveVault** [FCL-Team/FoldCraftLauncher#216]
### Launcher Version

1.1.3

### Device Information

Motorola G9 Power, Android 11, aarch64

### Problem Description

Is not loading the version page, forge download and more

https://github.com/FCL-Team/FoldCraftLauncher/assets/156531774/f31d7f9c-354c-4e40-ad5b-47aa104ac74a

### Java

Default

### Renderer

Default

### Game Version

All Versions

### Modifications Made to the Game

Nothing

**Comment by FrostNovaHD** [comment]
Change your download mirror

**Comment by FrostNovaHD** [comment]
T
