### ISSUE TITLE
Error in fold craft launcher versions of minecraft

### ISSUE THREAD

**Issue by Levy892** [FCL-Team/FoldCraftLauncher#218]
### Launcher Version

1.1.3

### Device Information

Samsung m53 5g 

### Problem Description

![Screenshot_20240125_123236_Fold Craft Launcher](https://github.com/FCL-Team/FoldCraftLauncher/assets/157727298/273a3f76-2532-43da-93b5-14ab0ed20e03)
In my fold craft the minecraft versions are not loading and I have used fold craft before and did not have this bug I need help

### Java

Auto

### Renderer

Holy GL4ES (opengl 2.1)

**Comment by FrostNovaHD** [comment]
change your mirror we cant do anyting about it
