### ISSUE TITLE
使用little skin登录，不能进入游戏

### ISSUE THREAD

**Issue by sherkent** [FCL-Team/FoldCraftLauncher#220]
### Launcher Version

1.1.3

### Device Information

redmi note12turbo 安卓13 Arm64

### Problem Description

使用little skin登录，不能进入游戏，弹出窗口中点击跳过仍显示错误。使用离线账户时正常

### Java

java17

### Renderer

holy-gl4es

### Game Version

1.20.4

### Modifications Made to the Game

optifine HD_U_17_pre2

**Comment by zkitefly** [comment]
麻烦截个图

**Comment by sherkent** [comment]
> 麻烦提供个日志和截个图

[fcl-exported-logs-2024-01-26T12-20-46.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14065953/fcl-exported-logs-2024-01-26T12-20-46.log)

![Screenshot_2024-01-26-22-22-12-712_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/103788342/9c6d2960-874f-48df-a85e-77375ca03871)

点击跳过后弹出错误提示
![Screenshot_2024-01-26-22-22-18-088_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/103788342/6a9ae03d-56b0-4f02-8c58-e00d98f14f69)

使用离线账户登录正常进入游戏

**Comment by yassengaming1423** [comment]
skin موراضي يشتغل يتلع اول خطى في صورة

**Comment by zkitefly** [comment]
你试试将该账户删除重新登录再试试？

**Comment by sherkent** [comment]
> 你试试将该账户删除重新登录再试试？

不行，我都卸载重装过了也不行

**Comment by yassengaming1423** [comment]
![Screenshot_20240128_093828_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/154661285/abadcfce-4481-4499-846b-c74bc898b5f2)
تي مشكلة

**Comment by yassengaming1423** [comment]
مسحت الحساب كثيراً ولم يشتخل

**Comment by root-S7** [comment]
mcbbs下载源挂了导致AuthlibInjector插件更新检查失效

**Comment by yassengaming1423** [comment]
Okay, thank you

**Comment by zkitefly** [comment]
> > mcbbs下载源挂了导致AuthlibInjector插件更新检查失效
> 
> 那我应该怎么做

在启动器设置关闭自动选择下载源，并选择官方源

**Comment by sherkent** [comment]
> > > mcbbs下载源挂了导致AuthlibInjector插件更新检查失效
> > 
> > 那我应该怎么做
> 
> 在启动器设置关闭自动选择下载源，并选择官方源

ok，可以了，感谢

**Comment by yassengaming1423** [comment]
طيب من فين ينفع صور

**Comment by yassengaming1423** [comment]
ماشي من اعدادات بس من فين

**Comment by yassengaming1423** [comment]
عملت نفس كل اللي انت قلته وما اشتغلش ايه الحل
