### ISSUE TITLE
无法使用ipv6链接到mc服务器

### ISSUE THREAD

**Issue by Four-way-Xeon** [FCL-Team/FoldCraftLauncher#226]
### Launcher Version

1.1.3

### Device Information

redmi note12 tpro 12+256

### Problem Description

可以使用ipv4加入服务器但无法使用ipv6，无论是局域网还是公网都不行

### Java

java17

### Game Version

1.20.1

**Comment by ShirosakiMio** [comment]
菜，就多练（

**Comment by ShirosakiMio** [comment]
![qq_pic_merged_1706956925270](https://github.com/FCL-Team/FoldCraftLauncher/assets/19233890/3deed05e-6749-4e12-aa9a-3e19a6368fad)
![{BA9C09C1-305E-49a9-8710-D6090D4CA43B}](https://github.com/FCL-Team/FoldCraftLauncher/assets/19233890/2224b1ce-a003-425b-bbad-b9434e6228db)
![Screenshot_2024-02-03-18-39-13-900_com tungsten f](https://github.com/FCL-Team/FoldCraftLauncher/assets/19233890/71fea0c6-2a73-424b-8e2f-f809534e765b)
![Screenshot_2024-02-03-18-40-24-667_com tungsten f](https://github.com/FCL-Team/FoldCraftLauncher/assets/19233890/e8f2e692-129a-4812-b608-e500b81d5413)

**Comment by Four-way-Xeon** [comment]
> 菜，就多练（

![Screenshot_2024-02-03-22-25-18-819_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/98648088/7bdc5d37-695c-450f-9b74-4a78bba26b4b)
p1 直接输入域名
![Screenshot_2024-02-03-22-25-29-410_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/98648088/ebda8935-067a-4d0d-b089-e9437b3b4215)
p2直接输连接错误图片
![Screenshot_2024-02-03-22-28-14-821_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/98648088/b42b8889-8689-4d5a-b308-b13f6425c90a)
p3 看着我的ipv6
![Screenshot_2024-02-03-22-31-01-276_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/98648088/0b2ea916-f305-414f-878b-5eeb74406506)
p4 直接输piv6
![Screenshot_2024-02-03-22-31-05-289_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/98648088/15c37a16-7435-487d-ab2d-9362ab54ed5a)
p5 直接输ipv6的错误
![Screenshot_2024-02-03-22-31-14-421_com mmbox xbrowser pro](https://github.com/FCL-Team/FoldCraftLauncher/assets/98648088/0b24c4f3-57f1-4926-89c2-340d8fd6fc29)
p6 服务器

在此环境下已经使用ftp,Win10 je，rdp,webdav验证了连通性

**Comment by ShirosakiMio** [comment]
我反正是测试过了，1.12.2正常，1.20.1也是正常

**Comment by ShirosakiMio** [comment]
电脑使用宽带的ipv6作为主机，手机使用流量连接，都能连上。启动器层面肯定没问题

**Comment by Mooling0602** [comment]
> 电脑使用宽带的ipv6作为主机，手机使用流量连接，都能连上。启动器层面肯定没问题

我这里也是IPv6不能连接，并且我截取到了报错日志
[latest.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14235659/latest.log)

**Comment by DGHOSTI** [comment]
> 电脑使用宽带的ipv6作为主机，手机使用流量连接，都能连上。启动器层面肯定没问题

你有配置啥其他东西吗，我pc端能连，手机启动器这个就不行

**Comment by DGHOSTI** [comment]
> > 菜，就多练（
> 
> ![Screenshot_2024-02-03-22-25-18-819_com tungsten fcl](https://private-user-images.githubusercontent.com/98648088/302041946-7bdc5d37-695c-450f-9b74-4a78bba26b4b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDA1NjAsIm5iZiI6MTcwOTE0MDI2MCwicGF0aCI6Ii85ODY0ODA4OC8zMDIwNDE5NDYtN2JkYzVkMzctNjk1Yy00NTBmLTliNzQtNGE3OGJiYTI2YjRiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE3MTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMjA5OTA2Njg1YmJkYTFmN2Q5ODljZjI5MzgwZjM2MzI4ODNhY2EzNTJmMWM4YjA2Yzc1NTk2N2U2MGVkYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZhpJB-8qw2RaKYr6FeR3nA2nEzueSTsZghv3_edDtAA) p1 直接输入域名 ![Screenshot_2024-02-03-22-25-29-410_com tungsten fcl](https://private-user-images.githubusercontent.com/98648088/302041965-ebda8935-067a-4d0d-b089-e9437b3b4215.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDA1NjAsIm5iZiI6MTcwOTE0MDI2MCwicGF0aCI6Ii85ODY0ODA4OC8zMDIwNDE5NjUtZWJkYTg5MzUtMDY3YS00ZDBkLWIwODktZTk0MzdiM2I0MjE1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE3MTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMzE2YmQwYThkNDVmYmY4ZDA5MmMxZTRiZmRiN2FlODIzZGE0OTliMTQxZDAzMTBlZjEyODU0NWFlZGI2MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OzLM5bjmFzFjYwIPKjv-9hEBQW5fKNkc25MT65mTpe4) p2直接输连接错误图片 ![Screenshot_2024-02-03-22-28-14-821_com tungsten fcl](https://private-user-images.githubusercontent.com/98648088/302041984-b42b8889-8689-4d5a-b308-b13f6425c90a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDA1NjAsIm5iZiI6MTcwOTE0MDI2MCwicGF0aCI6Ii85ODY0ODA4OC8zMDIwNDE5ODQtYjQyYjg4ODktODY4OS00ZDVhLWIzMDgtYjEzZjY0MjVjOTBhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE3MTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxMjljNjY5ZjhkZmM2NDk0YjE0ODNjZGI5YWY5YzgxYTY0OGUyOWFmZWQ4NzhlMTEwM2MxMTg4MDM3YmJiNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CJ-4iNr3WXEgiQxOEglp44ff6ZZfWl50cV6OM_o75Dk) p3 看着我的ipv6 ![Screenshot_2024-02-03-22-31-01-276_com tungsten fcl](https://private-user-images.githubusercontent.com/98648088/302042091-0b2ea916-f305-414f-878b-5eeb74406506.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDA1NjAsIm5iZiI6MTcwOTE0MDI2MCwicGF0aCI6Ii85ODY0ODA4OC8zMDIwNDIwOTEtMGIyZWE5MTYtZjMwNS00MTRmLTg3OGItNWVlYjc0NDA2NTA2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE3MTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MmM1MDYxN2Q0ZjhmNzM2MDg4MDFiZGRhNDJhZGZmMDRiZjA0ZTNkODBkMGI4MmYyZjVhNmExMGFjN2EzNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WRcKpbXUPJmQ5abExAkraJjS6N9rrCkIJPQX-g6_c-A) p4 直接输piv6 ![Screenshot_2024-02-03-22-31-05-289_com tungsten fcl](https://private-user-images.githubusercontent.com/98648088/302042117-15c37a16-7435-487d-ab2d-9362ab54ed5a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDA1NjAsIm5iZiI6MTcwOTE0MDI2MCwicGF0aCI6Ii85ODY0ODA4OC8zMDIwNDIxMTctMTVjMzdhMTYtNzQzNS00ODdkLWFiMmQtOTM2MmFiNTRlZDVhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE3MTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YmJlN2VlMjFmM2Q4NWY1ZmZjMjY3Yjk0MzdjZDZhYWMwNzRlYjNhOTRjNWM2ZGU1NTgxODRlZmJiZTRjY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S19pg1-4-E916Uqd6jtUZsDILWvHDBZ8HYF2dogZyxE) p5 直接输ipv6的错误 ![Screenshot_2024-02-03-22-31-14-421_com mmbox xbrowser pro](https://private-user-images.githubusercontent.com/98648088/302042139-0b24c4f3-57f1-4926-89c2-340d8fd6fc29.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDA1NjAsIm5iZiI6MTcwOTE0MDI2MCwicGF0aCI6Ii85ODY0ODA4OC8zMDIwNDIxMzktMGIyNGM0ZjMtNTdmMS00OTI2LTg5YzItMzQwZDhmZDZmYzI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE3MTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2YzZlMGY0NGQwZjQ0NzBmMDUyNDc5MzhmZWVmOWJkMTc2ZWNlNGM2NWVjODJlNWFkMmFhNjFlMTk0Mzc4YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6HIubfT6gR2TYpNy5-G_5CM11-M3DW8Dj51hfmfyfWQ) p6 服务器
> 
> 在此环境下已经使用ftp,Win10 je，rdp,webdav验证了连通性

解决了吗哥们

**Comment by Mooling0602** [comment]
> > > 菜，就多练（
> > 
> > 
> > ![Screenshot_2024-02-03-22-25-18-819_com tungsten fcl](https://private-user-images.githubusercontent.com/98648088/302041946-7bdc5d37-695c-450f-9b74-4a78bba26b4b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDA1NjAsIm5iZiI6MTcwOTE0MDI2MCwicGF0aCI6Ii85ODY0ODA4OC8zMDIwNDE5NDYtN2JkYzVkMzctNjk1Yy00NTBmLTliNzQtNGE3OGJiYTI2YjRiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE3MTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMjA5OTA2Njg1YmJkYTFmN2Q5ODljZjI5MzgwZjM2MzI4ODNhY2EzNTJmMWM4YjA2Yzc1NTk2N2U2MGVkYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZhpJB-8qw2RaKYr6FeR3nA2nEzueSTsZghv3_edDtAA) p1 直接输入域名 ![Screenshot_2024-02-03-22-25-29-410_com tungsten fcl](https://private-user-images.githubusercontent.com/98648088/302041965-ebda8935-067a-4d0d-b089-e9437b3b4215.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDA1NjAsIm5iZiI6MTcwOTE0MDI2MCwicGF0aCI6Ii85ODY0ODA4OC8zMDIwNDE5NjUtZWJkYTg5MzUtMDY3YS00ZDBkLWIwODktZTk0MzdiM2I0MjE1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE3MTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMzE2YmQwYThkNDVmYmY4ZDA5MmMxZTRiZmRiN2FlODIzZGE0OTliMTQxZDAzMTBlZjEyODU0NWFlZGI2MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OzLM5bjmFzFjYwIPKjv-9hEBQW5fKNkc25MT65mTpe4) p2直接输连接错误图片 ![Screenshot_2024-02-03-22-28-14-821_com tungsten fcl](https://private-user-images.githubusercontent.com/98648088/302041984-b42b8889-8689-4d5a-b308-b13f6425c90a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDA1NjAsIm5iZiI6MTcwOTE0MDI2MCwicGF0aCI6Ii85ODY0ODA4OC8zMDIwNDE5ODQtYjQyYjg4ODktODY4OS00ZDVhLWIzMDgtYjEzZjY0MjVjOTBhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE3MTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxMjljNjY5ZjhkZmM2NDk0YjE0ODNjZGI5YWY5YzgxYTY0OGUyOWFmZWQ4NzhlMTEwM2MxMTg4MDM3YmJiNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CJ-4iNr3WXEgiQxOEglp44ff6ZZfWl50cV6OM_o75Dk) p3 看着我的ipv6 ![Screenshot_2024-02-03-22-31-01-276_com tungsten fcl](https://private-user-images.githubusercontent.com/98648088/302042091-0b2ea916-f305-414f-878b-5eeb74406506.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDA1NjAsIm5iZiI6MTcwOTE0MDI2MCwicGF0aCI6Ii85ODY0ODA4OC8zMDIwNDIwOTEtMGIyZWE5MTYtZjMwNS00MTRmLTg3OGItNWVlYjc0NDA2NTA2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE3MTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MmM1MDYxN2Q0ZjhmNzM2MDg4MDFiZGRhNDJhZGZmMDRiZjA0ZTNkODBkMGI4MmYyZjVhNmExMGFjN2EzNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WRcKpbXUPJmQ5abExAkraJjS6N9rrCkIJPQX-g6_c-A) p4 直接输piv6 ![Screenshot_2024-02-03-22-31-05-289_com tungsten fcl](https://private-user-images.githubusercontent.com/98648088/302042117-15c37a16-7435-487d-ab2d-9362ab54ed5a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDA1NjAsIm5iZiI6MTcwOTE0MDI2MCwicGF0aCI6Ii85ODY0ODA4OC8zMDIwNDIxMTctMTVjMzdhMTYtNzQzNS00ODdkLWFiMmQtOTM2MmFiNTRlZDVhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE3MTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YmJlN2VlMjFmM2Q4NWY1ZmZjMjY3Yjk0MzdjZDZhYWMwNzRlYjNhOTRjNWM2ZGU1NTgxODRlZmJiZTRjY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S19pg1-4-E916Uqd6jtUZsDILWvHDBZ8HYF2dogZyxE) p5 直接输ipv6的错误 ![Screenshot_2024-02-03-22-31-14-421_com mmbox xbrowser pro](https://private-user-images.githubusercontent.com/98648088/302042139-0b24c4f3-57f1-4926-89c2-340d8fd6fc29.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDA1NjAsIm5iZiI6MTcwOTE0MDI2MCwicGF0aCI6Ii85ODY0ODA4OC8zMDIwNDIxMzktMGIyNGM0ZjMtNTdmMS00OTI2LTg5YzItMzQwZDhmZDZmYzI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE3MTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2YzZlMGY0NGQwZjQ0NzBmMDUyNDc5MzhmZWVmOWJkMTc2ZWNlNGM2NWVjODJlNWFkMmFhNjFlMTk0Mzc4YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6HIubfT6gR2TYpNy5-G_5CM11-M3DW8Dj51hfmfyfWQ) p6 服务器
> > 在此环境下已经使用ftp,Win10 je，rdp,webdav验证了连通性
> 
> 解决了吗哥们

解决个屁，我报错日志都给他发了，还直接把issue关了，摆明了不想给你解决
