### ISSUE TITLE
Crash Report 

### ISSUE THREAD

**Issue by Baturax** [FCL-Team/FoldCraftLauncher#231]
### Launcher Version

Latest action build

### Device Information

Redmi note 8, android 13, arm64, lineageos

### Problem Description

Game crashed after entering world with fabric

### Java

auto selected

### Renderer

golygl 4es opengl 2.1

### Game Version

1.20.4

### Modifications Made to the Game

latest fabric and fabric api

### Game Crash Report

[Uploading fcl-latest6847975445142805057.log…]()

**Comment by Tungstend** [comment]
The log file was not uploaded successfully
