### ISSUE TITLE
从游戏内界面切换到UI界面会打断按压

### ISSUE THREAD

**Issue by block13566** [FCL-Team/FoldCraftLauncher#235]
### Launcher Version

1.1.3

### Device Information

MI9 Android11 arm64

### Problem Description

例如游戏模式切换器，按住F3后按F4，弹出游戏模式切换器界面时F3的按压操作会被取消（已经打开总是显示）

**Comment by ShirosakiMio** [comment]
1.1.4应该已经修复了这个问题
