### ISSUE TITLE
释放文件时多释放了一次

### ISSUE THREAD

**Issue by root-S7** [FCL-Team/FoldCraftLauncher#241]
### Launcher Version

1.1.3

### Device Information

SM-G9910

### Problem Description

![image](https://github.com/FCL-Team/FoldCraftLauncher/assets/110681414/c10a7c7d-f7ce-41e1-bac3-5886420ed5b4)

也许是写重复了吧

### Java

Nothing

### Renderer

Nothing

### Game Version

Nothing

### Modifications Made to the Game

Nothing

### Game Crash Report

Nothing

### Launcher Crash Report

Nothing

### Launcher Log File

Nothing

**Comment by root-S7** [comment]
不对，java21那个地方也多了一次文件释放

**Comment by root-S7** [comment]
建议放在一个公共目录下共同访问，没有特别大必要每个java下都释放

**Comment by ShirosakiMio** [comment]
介个是设定，来自只有java17时的历史遗留问题

**Comment by root-S7** [comment]
> 介个是设定，来自只有java17时的历史遗留问题

行⑧
