### ISSUE TITLE
add more language to the game 

### ISSUE THREAD

**Issue by agent1243** [FCL-Team/FoldCraftLauncher#242]
### Description

In FCL, the only languages in the game are English and Chinese, more languages could be added, people who don't understand English or Chinese won't understand what Foldcraft shows 

### Why

It would be good, it would be a better understanding of the functions that foldcraft has, like pojavlauncher that supports all languages that exist

**Comment by FrostNovaHD** [comment]
> ### Description
> In FCL, the only languages in the game are English and Chinese, more languages could be added, people who don't understand English or Chinese won't understand what Foldcraft shows
> 
> ### Why
> It would be good, it would be a better understanding of the functions that foldcraft has, like pojavlauncher that supports all languages that exist

pojav thousand poeple that that will take time that we dont have

**Comment by agent1243** [comment]
Tabom, no problem, I just showed you an idea that you could put in the fcl, you can do it in your own time :)

**Comment by Llerey** [comment]
> > ### Описание
> > В FCL единственные языки в игре — английский и китайский, можно добавить больше языков, люди, которые не понимают английский или китайский, не поймут, что показывает Foldcraft.
> > ### Почему
> > Было бы хорошо, было бы лучшее понимание функций, которые есть у фолдкрафта, например, pojavlauncher, который поддерживает все существующие языки
> 
> у Pojav есть тысячи человек, которые смогут перевести это займет время, которого у нас нет, к тому же мы небольшая команда


A little later I can make a Russian and Ukrainian translation, or at least try.
