### ISSUE TITLE
hmcl-pe迁pcl版本加载不出来

### ISSUE THREAD

**Issue by OolongMC** [FCL-Team/FoldCraftLauncher#246]
### Launcher Version

1.1.4.1

### Device Information

honor v30 pro

### Problem Description

我是一个hmclpe用户，正在向fcl迁移，当我添加我的hmcl目录（其实是更早用过的pojav目录)时，fcl崩溃了一次，重新启动以后，只加载了6个版本，刷新后仍只有6个
![Screenshot_20240209_134106_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/137302776/5a419b97-00bd-4019-b513-58b831f3b36a)
![Screenshot_20240209_133848_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/137302776/744e2e1d-c623-4877-8ebd-6a7da6517944)
![Screenshot_20240209_133902_com tungsten hmclpe](https://github.com/FCL-Team/FoldCraftLauncher/assets/137302776/e40ffb9d-55d5-4eb1-a36f-bc5d3691133e)
![Screenshot_20240209_133908_com tungsten hmclpe](https://github.com/FCL-Team/FoldCraftLauncher/assets/137302776/b64a95d3-1504-47ee-b256-2e2d0cfbb4f9)
![Screenshot_20240209_133915_com tungsten hmclpe](https://github.com/FCL-Team/FoldCraftLauncher/assets/137302776/9c67c04d-0443-43a4-88e9-ef23bb7f3e2a)
![Screenshot_20240209_133923_com tungsten hmclpe](https://github.com/FCL-Team/FoldCraftLauncher/assets/137302776/fe12cd37-e526-46d2-96fe-9eb1c53550ef)
![Screenshot_20240209_133928_com tungsten hmclpe](https://github.com/FCL-Team/FoldCraftLauncher/assets/137302776/0be26f51-50a9-400f-a3b0-6dc26763a020)
![Screenshot_20240209_133940_com tungsten hmclpe](https://github.com/FCL-Team/FoldCraftLauncher/assets/137302776/eb6973b7-ae2b-4094-b7bf-71e86a858a8b)
![Screenshot_20240209_134008_com tungsten hmclpe](https://github.com/FCL-Team/FoldCraftLauncher/assets/137302776/b031b88a-1445-4e85-bc32-cd0343547ee8)
![Screenshot_20240209_134357_com tungsten hmclpe](https://github.com/FCL-Team/FoldCraftLauncher/assets/137302776/92e83518-4ac0-4a43-b104-f4f3ccf08781)
还有，FCL何时支持HMCL-PE键位

### Java

自动选择

### Renderer

HOLY GL4ES

### Modifications Made to the Game

除rift以外其他的

### Launcher Log File

[Uploading fcl-exported-logs-2024-02-09T13-32-41.log…]()

**Comment by Tungstend** [comment]
HMCL-PE 的version.json文件与FCL 并不完全一样，另外日志没上传成功，你需要等上传成功再发表

**Comment by OolongMC** [comment]
> HMCL-PE 的version.json文件与FCL 并不完全一样，另外日志没上传成功，你需要等上传成功再发表

我更新了1.1.4.2，发现版本列表里的一些版本的名字改为了最初的名字，如RLCraft被重命名为了1.12.2，每当我改了一个版本的名字，一个之前没加载出来的版本就被改为了版本号名字，直到我改了所有版本的名字，那些版本也就都显现出来了，我也不知道为什么会这样，但这个问题已经解决了
