### ISSUE TITLE
Please fix the textures 

### ISSUE THREAD

**Issue by Voidless-ark** [FCL-Team/FoldCraftLauncher#247]
When i play a modpack or so the items,water,particles get white i dont know why this happens it happens for a bit tho i have 7 gb allocated ☠️![Screenshot_2024-02-09-19-14-20-230_com.tungsten.fcl.jpg](https://github.com/FCL-Team/FoldCraftLauncher/assets/153999883/ca1d2b19-da3f-48ae-a95a-a0fe2a01ac4d)

**Comment by teaSummer** [comment]
It is recommended to use the _Bug Feedback_ issue template. It describes the problem more clearly.

**Comment by ShirosakiMio** [comment]
can't fix renderer bug
