### ISSUE TITLE
what is this message??

### ISSUE THREAD

**Issue by agent1243** [FCL-Team/FoldCraftLauncher#248]
### Description

It's not really an improvement, but rather a question, when I start version 1.20.1 in foldcraft with the new jre 21, this message appears, I didn't understand the message, if I click continue, it will cause some problems in the game just start? 

![Screenshot_20240209_133021_Fold Craft Launcher](https://github.com/FCL-Team/FoldCraftLauncher/assets/137364977/856cffa1-66a2-4881-bcb1-e4a67b5458a7)

### Why

it's just a question, not a new feature for foldcraft launcher

**Comment by ShirosakiMio** [comment]
It is just a reminder that you have selected a Java that may not be supported by the current version.
![Screenshot_2024-02-10-09-34-58-197_bin mt plus](https://github.com/FCL-Team/FoldCraftLauncher/assets/19233890/6cca221c-4f0d-4292-ac99-0c87f96e2357)

**Comment by ShirosakiMio** [comment]
![Screenshot_2024-02-10-09-44-22-573_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/19233890/44ae9af0-5eb8-477e-bdb3-fb9add9b8072)
If you don't want to see it, open the "Do not check JVM compatibility".

**Comment by agent1243** [comment]
Thank you very much for answering me :)
