### ISSUE TITLE
vgpu渲染错误

### ISSUE THREAD

**Issue by MakerLunar** [FCL-Team/FoldCraftLauncher#249]
### Launcher Version

1.1.4.1

### Problem Description

There is an issue with the vgpu rendering of Fcl, which makes the UI transparent when looking down,https://wwp.lanzn.com/iVDUW1nwq2xi (bug's video address)

### Renderer

vgpu

### Game Version

1.12.2

**Comment by root-S7** [comment]
视频中间那些问题吗？你按下f11试试?

**Comment by ShirosakiMio** [comment]
已换成1.4.0，1.3.68有亿点问题
