### ISSUE TITLE
Forge与LiteLoader不兼容

### ISSUE THREAD

**Issue by OolongMC** [FCL-Team/FoldCraftLauncher#250]
### Launcher Version

1.1.4.1

### Device Information

honor v30

### Problem Description

我为了解决**hmcl-pe迁pcl版本加载不出来**时，我决定重装所有版本。发现不管是1.8.9、1.11.2还是1.12.2，Forge与LiteLoader在FCL中都不兼容，HMCL-PE却兼容。根据LiteLoader官方文档，LiteLoader因该是与forge兼容的

Uploading lv_0_20240211125805.mp4…

### Game Version

1.8.9、1.11.2、1.12.2、1.7.10

### Modifications Made to the Game

OptiFine、Forge、重装前已安装LiteLoader

**Comment by zkitefly** [comment]
不应该同时安装 Forge 与 LiteLoader，而且为啥一定要安装 LiteLoader 呢

**Comment by OolongMC** [comment]
> 不应该同时安装 Forge 与 LiteLoader，而且为啥一定要安装 LiteLoader 呢
1、稳定的 LiteLoader 绝对不会和稳定的 Forge 有冲突，除非将 Forge 比较新的版本和 LiteLoader 比较老的版本（本段来源未知，如果出问题请将两个模组加载器均升级到最新版本）放在一起——摘自https://www.mcmod.cn/class/610.html
2、个人认为，装了LiteLoader后，以后装LiteLoader的MOD就可以不用再装LiteLoader了

**Comment by Tungstend** [comment]
更新1.1.4.2
