### ISSUE TITLE
control和log目录位置问题

### ISSUE THREAD

**Issue by root-S7** [FCL-Team/FoldCraftLauncher#252]
### Launcher Version

最新的版本

### Device Information

SM-G9910

### Problem Description

FCLauncher/src/main/java/com/tungsten/fclauncher/utils/FCLPath.java这个类中的LOG_DIR和CONTROLLER_DIR静态变量我建议应改为通过SHARED_COMMON_DIR静态变量读取的公共FCL目录。
FCLCore/src/main/java/com/tungsten/fclcore/download/ProcessService.java内的“Environment.getExternalStorageDirectory().getAbsolutePath() + "/FCL/log"”也应为FCLPath.LOG_DIR更好吧

但是吧，这样改了以后还有个问题；那就是若我进入启动器后修改了文件存放路径这样新的路径又没有日志文件和按键文件，最后又要监听下玩家改到了哪个目录下那么就要刷新下FCLPath类中对应变量

### Java

*

### Renderer

*

### Game Version

*

### Modifications Made to the Game

*

### Game Crash Report

*

### Launcher Crash Report

*

### Launcher Log File

*

**Comment by ShirosakiMio** [comment]
日志和按键搬到FCL目录只是相对于之前更方便没有root的以及小白找到对应的位置手动查看/修改，并不随玩家的设置而改变。ProcessService.java里的那个日志位置应该算是失误了，不过那个日志并没有什么价值
