### ISSUE TITLE
what is animation speed??

### ISSUE THREAD

**Issue by agent1243** [FCL-Team/FoldCraftLauncher#253]
### Description

One thing I still don't understand, what is this option, does it make Minecraft animations faster or slower?? 

![Screenshot_20240211_111802_Fold Craft Launcher](https://github.com/FCL-Team/FoldCraftLauncher/assets/137364977/e1a8ac8f-e6d2-49fe-bb61-e2a14bac8082)

### Why

It's not a benefit, it's just a question

**Comment by agent1243** [comment]
Thank you, I don't speak Chinese, I use the translator, but I understood

**Comment by root-S7** [comment]
The UI transition animation speed of the foldcraftlauncher software. It is not the speed of the minecraft gsme

**Comment by root-S7** [comment]
Similar to Android developer options：
![Screenshot_20240212_025355_Settings](https://github.com/FCL-Team/FoldCraftLauncher/assets/110681414/ba7c0151-804c-41d3-98e2-f27aa0237414)
