### ISSUE TITLE
1.12.2forge启动失败，java11无法使用

### ISSUE THREAD

**Issue by giaobupai** [FCL-Team/FoldCraftLauncher#254]
### Launcher Version

1.1.4.2

### Device Information

HWASK-H arm64 kirin710 Android10

### Problem Description

1.12.2forge启动失败，java11无法使用
由于是别人崩溃的，不要问我更多信息，我只是帮他报告
别人QQ号：2679768095
![Screenshot_20240212_013031](https://github.com/FCL-Team/FoldCraftLauncher/assets/137373766/8ff395bb-4f08-459e-ab8a-13563550efb1)

### Java

Java8

### Renderer

Holy-GL4ES

### Game Version

1.12.2

### Modifications Made to the Game

Forge-1.12.2-14.23.5.2860

### Game Crash Report

[fcl-latest8572680397044911095.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14233338/fcl-latest8572680397044911095.log)

**Comment by root-S7** [comment]
forge官网从来没说过1.12.2需要使用java11运行，请使用java8。java11环境只是给1.14-1.16版本某些特殊mod对java版本又要求才增加的

**Comment by root-S7** [comment]
剩余的问题：
1.你能解释下 -Xcheck:jni这个参数是你加的么，如果是那你加他是为了什么？
2.你的日志文件提示用的java8启动的游戏而不是11，你不会自己拆包改了java环境吧？

**Comment by giaobupai** [comment]
> 剩余的问题： 你的日志文件提示用的java8启动的游戏而不是11，你不会自己拆包改了java环境吧？

提交重复的，已关闭

**Comment by giaobupai** [comment]
> forge官网从来没说过1.12.2需要使用java11运行，请使用java8。java11环境只是给1.14-1.16版本某些特殊mod对java版本又要求才增加的

java11直接虚拟机报错，想着java11是整活用的，然后就不要求修复了

**Comment by giaobupai** [comment]
> 剩余的问题： 你的日志文件提示用的java8启动的游戏而不是11，你不会自己拆包改了java环境吧？

本来想把java11用不了和forge1.12.2启动在Java8的情况下启动不了一同上报，想着java11整活用的，后来删掉了。我没有想到重复提交了一个issue，非常抱歉。
