### ISSUE TITLE
1.12.2forge启动失败

### ISSUE THREAD

**Issue by giaobupai** [FCL-Team/FoldCraftLauncher#255]
### Launcher Version

1.1.4.2

### Device Information

HWASK-H arm64 kirin710 Android10

### Problem Description

1.12.2forge启动失败
由于是别人崩溃的，不要问我更多信息，我只是帮他报告
别人QQ号：2679768095
![Screenshot_20240212_013031](https://github.com/FCL-Team/FoldCraftLauncher/assets/137373766/8ff395bb-4f08-459e-ab8a-13563550efb1)

### Java

Java8

### Renderer

Holy-GL4ES

### Game Version

1.12.2

### Modifications Made to the Game

Forge-1.12.2-14.23.5.2860

### Game Crash Report

[fcl-latest8572680397044911095.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14233338/fcl-latest8572680397044911095.log)

**Comment by root-S7** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/issues/254#issuecomment-1937830459

**Comment by giaobupai** [comment]
> [#254 (comment)](https://github.com/FCL-Team/FoldCraftLauncher/issues/254#issuecomment-1937830459)

如果你帮他解决这个问题成功了，那么我就关闭这个issue，因为我没有这个困扰
