### ISSUE TITLE
.mrpack的导入问题

### ISSUE THREAD

**Issue by LsrlYrsc** [FCL-Team/FoldCraftLauncher#256]
### Launcher Version

1.1.4.2

### Device Information

Huawei Mate 30 Pro 5G

### Problem Description

“安装整合包”里展示的原地址没有我的.mrpack文件
是无法识别，还是只识别.zip但没有记录.mrpack?
如果是前者的话，我希望可以把分类直接改为“全部文件(*)”

**Comment by ShirosakiMio** [comment]
修好了
