### ISSUE TITLE
一些本来兼容的ModLoader无法同时安装

### ISSUE THREAD

**Issue by OolongMC** [FCL-Team/FoldCraftLauncher#257]
### Launcher Version

1.1.4.2

### Device Information

honor v30 pro

### Problem Description

![Screenshot_20240213_141808_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/137302776/79165a9d-716b-4963-b9bb-0234084ccf1e)
关于neoforge与forge的兼容：
We remain compatible with existing Forge for the present time.（目前我们仍然与现有的forge兼容。）——摘自https://neoforged.net/news/theproject/
关于neoforge与高清修复的兼容：
支持的MC版本:NeoForge:1.20.1——摘自https://www.mcmod.cn/class/36.html
还有，这个启动器叫FCL，PCL可以同装fabric和OptiFine，为什么FCL就不行呢？关于OptiFine可以使用OptiFabric、OptiLegacy、OptiFabric Legacy进行共存（还有，可不可以在低版本添加fabric（Legacy Fabric）的安装）

### Game Version

1.20.1

### Modifications Made to the Game

neoforge

**Comment by zkitefly** [comment]
这部分逻辑取自 HMCL，或许应该去 HMCL 发个 Issue？

**Comment by burningtnt** [comment]
这是 HMCLCore 的逻辑，抱歉给您带来了困扰、给 FCL 作者带来了不便。我们会尽快优化 HMCLCore 的逻辑，感谢您的支持

**Comment by root-S7** [comment]
仍然不代表以后一定兼容，你要知道的是OptiFabric本身兼容性就存在问题。

**Comment by zkitefly** [comment]
> 关于neoforge与forge的兼容：
> We remain compatible with existing Forge for the present time.（目前我们仍然与现有的forge兼容。）——摘自https://neoforged.net/news/theproject/

你的意思是 Forge 和 NeoForge 同时安装？

你这相当于安装了两个 Forge（

文章中说的“现有的forge兼容”是指兼容 Forge 模组，并不是可以同时安装 Forge 和 NeoForge

> 关于neoforge与高清修复的兼容：
> 支持的MC版本:NeoForge:1.20.1——摘自https://www.mcmod.cn/class/36.html
> 还有，这个启动器叫FCL，PCL可以同装fabric和OptiFine，为什么FCL就不行呢？
> 关于OptiFine可以使用OptiFabric、OptiLegacy、OptiFabric Legacy进行共存

PCL 使用 OptiFabric 进行 Fabric 与 OptiFine 的兼容，之前和一些人交流过，不推荐这样做，因为 OptiFabric 十分不稳定

我建议还是不要做。如果真的要的话，自己操作：仅安装 Fabric，然后下载对应版本的 OptiFabric 和 OptiFine，放置在模组文件夹中即可。

> （还有，可不可以在低版本添加fabric（Legacy Fabric）的安装）

和别人交流过，他们说不行，因为这个加载器模组太少，热度也不高
