### ISSUE TITLE
不上传Github了吗

### ISSUE THREAD

**Issue by HopiHopy** [FCL-Team/FoldCraftLauncher#26]

**Comment by root-S7** [comment]
没写完呢

**Comment by HopiHopy** [comment]
> 没写完呢

知道，说了开发中，但这已经这么久了，硬是一点动静没有

**Comment by root-S7** [comment]
![Screenshot_20230520_211029_QQ.png](https://github.com/FCL-Team/FoldCraftLauncher/assets/110681414/e9b915ab-2fe2-4237-b97d-25f225cf56f7)
