### ISSUE TITLE
game crashe

### ISSUE THREAD

**Issue by Rakib12345yb** [FCL-Team/FoldCraftLauncher#260]
### Launcher Version

1.1.4.2

### Device Information

samsung galaxy A13,android 13,armeabi-v7a

### Problem Description

launcher Crash 

### Java

Auto

### Renderer

Holy-GL4ES

### Game Version

1.20.1

### Modifications Made to the Game

FORGE 47.2.19

### Game Crash Report

[fcl-latest4825028962257632880.zip](https://github.com/FCL-Team/FoldCraftLauncher/files/14275213/fcl-latest4825028962257632880.zip)

**Comment by root-S7** [comment]
rubidium-mc1.20.1-0.7.1.jar, embeddium-0.2.16+mc1.20.1.jar????
why two?

**Comment by Rakib12345yb** [comment]
again crash 
[fcl-latest4872568641460832682.zip](https://github.com/FCL-Team/FoldCraftLauncher/files/14275420/fcl-latest4872568641460832682.zip)
