### ISSUE TITLE
FCL 日志格式问题

### ISSUE THREAD

**Issue by zkitefly** [FCL-Team/FoldCraftLauncher#264]
<image src="https://github.com/FCL-Team/FoldCraftLauncher/assets/64117916/8f5569cc-17ab-4890-957e-b1054732ad90" width="350"/>

<image src="https://github.com/FCL-Team/FoldCraftLauncher/assets/64117916/9bb6ca97-e0e6-439f-9074-90c80d9e71b6" width="350"/>

<image src="https://github.com/FCL-Team/FoldCraftLauncher/assets/64117916/dfbc08ed-1be3-4203-874f-2a86a232945f"/>

**Comment by burningtnt** [comment]
希望能够尽快修复
毕竟现在来问 HMCL 的手机版都被我（们）引流到 FCL 来了，这个问题导致日志显示很诡异

**Comment by Tungstend** [comment]
比较麻烦，这两天改

**Comment by burningtnt** [comment]
感谢
