### ISSUE TITLE
Crash when using Vulkan Zink

### ISSUE THREAD

**Issue by SingYann** [FCL-Team/FoldCraftLauncher#265]
### Launcher Version

1.1.4.3

### Device Information

Google Pixel 7 pro

### Problem Description

原版 使用vulkanzink时崩溃 未见到mojang图标

### Renderer

vulkan zink

### Game Version

1.20.1

### Modifications Made to the Game

forge

**Comment by zkitefly** [comment]
请上传日志

**Comment by SingYann** [comment]
invoke redirectStdio
invoke setLogPipeReady
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_loader.c:142
Log pipe ready.
invoke setFCLNativeWindow
invoke setEventPipe
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_bridge.c:60
setFCLNativeWindow : 0x6f48ddf620, size : 2232x1080
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_event.c:196
Succeeded to set event pipe
==================== Start Minecraft ====================
Device: cheetah
Architecture: arm64
CPU:cheetah
==================== Env Map ====================
Env: MESA_LOADER_DRIVER_OVERRIDE=zink
Env: MESA_GLSL_CACHE_DIR=/data/user/0/com.tungsten.fcl/cache
Env: JAVA_HOME=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17
Env: LIBGL_NAME=libOSMesa_8.so
Env: LIBGL_STRING=Zink
Env: MESA_GLSL_VERSION_OVERRIDE=460
Env: allow_higher_compat_version=true
Env: allow_glsl_extension_directive_midshader=true
Env: MESA_GL_VERSION_OVERRIDE=4.6
Env: GALLIUM_DRIVER=zink
Env: TMPDIR=/data/user/0/com.tungsten.fcl/cache
Env: LIBEGL_NAME=libEGL.so
Env: FCL_NATIVEDIR=/data/app/~~A3cM7drOtL5B3IJdRdD75A==/com.tungsten.fcl-lcm_5eyBvBbFf9VVtIurKg==/lib/arm64
Env: force_glsl_extensions_warn=true
Env: VTEST_SOCKET_NAME=/data/user/0/com.tungsten.fcl/cache/.virgl_test
Env: HOME=/storage/emulated/0/FCL/log
==================== Env Map ====================
Working directory: /storage/emulated/0/FCL/.minecraft
==================== Minecraft Arguments ====================
Minecraft argument: /data/user/0/com.tungsten.fcl/app_runtime/java/jre17/bin/java
Minecraft argument: -Djava.awt.headless=false
Minecraft argument: -Dcacio.managed.screensize=2232x1080
Minecraft argument: -Dcacio.font.fontmanager=sun.awt.X11FontManager
Minecraft argument: -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler
Minecraft argument: -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel
Minecraft argument: -Dawt.toolkit=com.github.caciocavallosilano.cacio.ctc.CTCToolkit
Minecraft argument: -Djava.awt.graphicsenv=com.github.caciocavallosilano.cacio.ctc.CTCGraphicsEnvironment
Minecraft argument: -Djava.system.class.loader=com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader
Minecraft argument: --add-exports=java.desktop/java.awt=ALL-UNNAMED
Minecraft argument: --add-exports=java.desktop/java.awt.peer=ALL-UNNAMED
Minecraft argument: --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED
Minecraft argument: --add-exports=java.desktop/sun.java2d=ALL-UNNAMED
Minecraft argument: --add-exports=java.desktop/java.awt.dnd.peer=ALL-UNNAMED
Minecraft argument: --add-exports=java.desktop/sun.awt=ALL-UNNAMED
Minecraft argument: --add-exports=java.desktop/sun.awt.event=ALL-UNNAMED
Minecraft argument: --add-exports=java.desktop/sun.awt.datatransfer=ALL-UNNAMED
Minecraft argument: --add-exports=java.desktop/sun.font=ALL-UNNAMED
Minecraft argument: --add-exports=java.base/sun.security.action=ALL-UNNAMED
Minecraft argument: --add-opens=java.base/java.util=ALL-UNNAMED
Minecraft argument: --add-opens=java.desktop/java.awt=ALL-UNNAMED
Minecraft argument: --add-opens=java.desktop/sun.font=ALL-UNNAMED
Minecraft argument: --add-opens=java.desktop/sun.java2d=ALL-UNNAMED
Minecraft argument: --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
Minecraft argument: --add-opens=java.base/java.net=ALL-UNNAMED
Minecraft argument: -Xbootclasspath/a:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
Minecraft argument: -Xmx2047m
Minecraft argument: -Dfile.encoding=UTF-8
Minecraft argument: -Dsun.stdout.encoding=UTF-8
Minecraft argument: -Dsun.stderr.encoding=UTF-8
Minecraft argument: -Djava.rmi.server.useCodebaseOnly=true
Minecraft argument: -Dcom.sun.jndi.rmi.object.trustURLCodebase=false
Minecraft argument: -Dcom.sun.jndi.cosnaming.object.trustURLCodebase=false
Minecraft argument: -Dlog4j2.formatMsgNoLookups=true
Minecraft argument: -Dlog4j.configurationFile=/storage/emulated/0/FCL/.minecraft/versions/1.20.1/log4j2.xml
Minecraft argument: -Dminecraft.client.jar=/storage/emulated/0/FCL/.minecraft/versions/1.20.1/1.20.1.jar
Minecraft argument: -Dfml.ignoreInvalidMinecraftCertificates=true
Minecraft argument: -Dfml.ignorePatchDiscrepancies=true
Minecraft argument: -Dext.net.resolvPath=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/resolv.conf
Minecraft argument: -Djava.io.tmpdir=/data/user/0/com.tungsten.fcl/cache/fclauncher
Minecraft argument: -Dos.name=Linux
Minecraft argument: -Dos.version=Android-14
Minecraft argument: -Dorg.lwjgl.opengl.libname=libOSMesa_8.so
Minecraft argument: -Dfml.earlyprogresswindow=false
Minecraft argument: -Dwindow.width=2232
Minecraft argument: -Dwindow.height=1080
Minecraft argument: -Duser.home=/storage/emulated/0/FCL/.minecraft
Minecraft argument: -Duser.language=zh
Minecraft argument: -Duser.timezone=Asia/Shanghai
Minecraft argument: -Djna.boot.library.path=/data/app/~~A3cM7drOtL5B3IJdRdD75A==/com.tungsten.fcl-lcm_5eyBvBbFf9VVtIurKg==/lib/arm64
Minecraft argument: -Dorg.lwjgl.vulkan.libname=libvulkan.so
Minecraft argument: -Dfcl.injector=4:enn:N:w:c
Minecraft argument: -Djava.library.path=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib:/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib/jli:/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib/server:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~A3cM7drOtL5B3IJdRdD75A==/com.tungsten.fcl-lcm_5eyBvBbFf9VVtIurKg==/lib/arm64
Minecraft argument: -Dio.netty.native.workdir=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib:/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib/jli:/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib/server:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~A3cM7drOtL5B3IJdRdD75A==/com.tungsten.fcl-lcm_5eyBvBbFf9VVtIurKg==/lib/arm64
Minecraft argument: -Dminecraft.launcher.brand=Fold Craft Launcher
Minecraft argument: -Dminecraft.launcher.version=1.1.4.3
Minecraft argument: -cp
Minecraft argument: /data/user/0/com.tungsten.fcl/app_runtime/lwjgl/lwjgl.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/github/oshi/oshi-core/6.3.0/oshi-core-6.3.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar:/storage/emulated/0/FCL/.minecraft/versions/1.20.1/1.20.1.jar
Minecraft argument: net.minecraft.client.main.Main
Minecraft argument: --username
Minecraft argument: Vincentule
Minecraft argument: --version
Minecraft argument: 1.20.1
Minecraft argument: --gameDir
Minecraft argument: /storage/emulated/0/FCL/.minecraft
Minecraft argument: --assetsDir
Minecraft argument: /storage/emulated/0/FCL/.minecraft/assets
Minecraft argument: --assetIndex
Minecraft argument: 5
Minecraft argument: --uuid
Minecraft argument: d9d1947890cc4f35a43840240f439c2f
Minecraft argument: --accessToken
Minecraft argument: eyJraWQiOiJhYzg0YSIsImFsZyI6IkhTMjU2In0.eyJ4dWlkIjoiMjUzNTQ1NDg5NTU5OTU5MCIsImFnZyI6IkFkdWx0Iiwic3ViIjoiMjgwOGFmZTEtMGUwNS00YTFiLTg2OGQtMmM2MDk3N2VmNWY5IiwiYXV0aCI6IlhCT1giLCJucyI6ImRlZmF1bHQiLCJyb2xlcyI6W10sImlzcyI6ImF1dGhlbnRpY2F0aW9uIiwiZmxhZ3MiOlsidHdvZmFjdG9yYXV0aCIsIm1zYW1pZ3JhdGlvbl9zdGFnZTQiLCJvcmRlcnNfMjAyMiIsIm11bHRpcGxheWVyIl0sInByb2ZpbGVzIjp7Im1jIjoiZDlkMTk0NzgtOTBjYy00ZjM1LWE0MzgtNDAyNDBmNDM5YzJmIn0sInBsYXRmb3JtIjoiVU5LTk9XTiIsInl1aWQiOiI4YzFkYmM3ZGI3Y2NkNTc0MDcyY2M3MjdhNjc0N2ZmZiIsIm5iZiI6MTcwODE4MDkzOSwiZXhwIjoxNzA4MjY3MzM5LCJpYXQiOjE3MDgxODA5Mzl9.J679l-gySHtlGCgEFxVsHqA8qTBXpbHpyyzbJ4YUWxw
Minecraft argument: --clientId
Minecraft argument: ${clientid}
Minecraft argument: --xuid
Minecraft argument: ${auth_xuid}
Minecraft argument: --userType
Minecraft argument: mojang
Minecraft argument: --versionType
Minecraft argument: Fold Craft Launcher
Minecraft argument: --width
Minecraft argument: 2232
Minecraft argument: --height
Minecraft argument: 1080
Hook exit success
[22:42:28] [main/WARN]: File not found or not readable: /proc/stat
[22:42:33] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 386 milliseconds
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/lwjgl/fcl_hook.c:70
Registered forkAndExec
[22:42:35] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:42:36] [Render thread/INFO]: Setting user: Vincentule
[22:42:37] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
OSMDroid: loading vulkan regularly...
OSMDroid: loaded vulkan, ptr=0x8a706e627edb8243

**Comment by SingYann** [comment]
还有一个日志文件 但似乎分析价值不大

[22:42:28] [main/WARN]: File not found or not readable: /proc/stat
[22:42:33] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 386 milliseconds
[22:42:35] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:42:36] [Render thread/INFO]: Setting user: Vincentule
[22:42:37] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot

**Comment by ShirosakiMio** [comment]
zink几乎只能支持骁龙cpu，你这是Google Tensor吧

**Comment by SingYann** [comment]
感谢解答！
