### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by MDEmonY** [FCL-Team/FoldCraftLauncher#266]
### Launcher Version

1.1.4.3

### Device Information

Redmi A1+, Android 12, arm32

### Problem Description

game crash when i start LabyMod

### Java

Java 17

### Renderer

Holy render

### Game Version

1.8.9

### Modifications Made to the Game

LabyMod

### Launcher Log File

[fcl-exported-logs-2024-02-17T20-05-38.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14319062/fcl-exported-logs-2024-02-17T20-05-38.log)

**Comment by ShirosakiMio** [comment]
LabyMod4 is not supported
