### ISSUE TITLE
在github actions中构建不混淆res的版本

### ISSUE THREAD

**Issue by hyplant** [FCL-Team/FoldCraftLauncher#267]
### Description

actions中发布的版本作为测试版，混淆res会导致难以直接通过xml文件找出一些与其有关的漏洞的原因，例如布局、动画等。应当保留res下文件的原文件名。

**Comment by root-S7** [comment]
混淆后可以减少apk体积，若不进行混淆apk体积会比较大

**Comment by root-S7** [comment]
最大问题，不会真的有那么多人看得懂崩溃原因吧？

**Comment by Vera-Firefly** [comment]
> ### Description
> actions中发布的版本作为测试版，混淆res会导致难以直接通过xml文件找出一些与其有关的漏洞的原因，例如布局、动画等。应当保留res下文件的原文件名。

你应该fork下来自己编译一份debug的,FCL-Team这里的直接就是release,而并非debug

**Comment by Vera-Firefly** [comment]
> ### Description
> actions中发布的版本作为测试版，混淆res会导致难以直接通过xml文件找出一些与其有关的漏洞的原因，例如布局、动画等。应当保留res下文件的原文件名。

你应该fork下来自己编译一份debug的,FCL-Team这里的直接就是release,而并非debug

**Comment by Vera-Firefly** [comment]
> ### Description
> actions中发布的版本作为测试版，混淆res会导致难以直接通过xml文件找出一些与其有关的漏洞的原因，例如布局、动画等。应当保留res下文件的原文件名。

你应该fork下来自己编译一份debug的,FCL-Team这里的直接就是release,而并非debug

**Comment by ShirosakiMio** [comment]
报错并不包含res里的什么东西

**Comment by Tungstend** [comment]
如果需要查找漏洞请直接在源码中查找，建议自己fork一个仓库或者直接本地构建测试
