### ISSUE TITLE
能否能把核心分离出来成一个库

### ISSUE THREAD

**Issue by LanHuangJG** [FCL-Team/FoldCraftLauncher#268]
### Description

我想自己做一个我的世界启动器满足我自己的特殊需求比如用kotlin jetpack compose写这个软件，还有用md3作为ui框架还有别的一些需求，但是我发现这特别难

### Why

可以吗？😭

**Comment by zkitefly** [comment]
fclcore 来自 还没出来 hnclcore

**Comment by ShirosakiMio** [comment]
启动器核心就是FCLauncher那个模块

**Comment by ShirosakiMio** [comment]
FCLauncher模块包含了全部运行游戏所需要的最精简的文件
