### ISSUE TITLE
game crash 

### ISSUE THREAD

**Issue by MDEmonY** [FCL-Team/FoldCraftLauncher#269]
### Launcher Version

1.1.4.3

### Device Information

Redmi A1+, Android 12, arm32

### Problem Description

crash

### Java

Java 8

### Renderer

Holy render

### Game Version

1.16.5

### Modifications Made to the Game

Additive modpack

### Launcher Crash Report

[fcl-latest3811294413366060137.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14322546/fcl-latest3811294413366060137.log)

**Comment by ShirosakiMio** [comment]
no sodium
