### ISSUE TITLE
problem with the shift button on the controller 

### ISSUE THREAD

**Issue by agent1243** [FCL-Team/FoldCraftLauncher#270]
### Launcher Version

1.1.4.3

### Device Information

Galaxy M22

### Problem Description

demonstration video: 

https://github.com/FCL-Team/FoldCraftLauncher/assets/137364977/d1db89ce-043f-4138-8ab5-471b035b26b2

in foldcraft in the game, when I click the shift button with keep pressing on, the player crouches and when I click the button again the player remains crouched and he just stays crouched , this really interferes with the game 

### Java

Java 21

### Renderer

Holy GL4ES

### Game Version

1.20.1 fabric

### Modifications Made to the Game

I don't have any mods 

### Game Crash Report

it does not have 

### Launcher Crash Report

didn't crash

**Comment by ShirosakiMio** [comment]
fixed
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/7954086919

**Comment by agent1243** [comment]
thank you very much
