### ISSUE TITLE
拥有自动保持的按键点击再取消后依然会保持

### ISSUE THREAD

**Issue by DSY-xiaoluo** [FCL-Team/FoldCraftLauncher#271]
### Launcher Version

1.1.4.3

### Device Information

VIVO X23;V1809A;Android9;arm64;OpenGL ES 3.2 V@331.0

### Problem Description

如题，给一个按键设置“自动保持”，点击一次，此时按键处于触发状态，键值也输出且保持了，这没问题。但再点一次按键，取消按键的触发状态，键值依旧在输出且保持。已经确定是关于键位的问题，游戏设置中确认是“按住”，且退出重新进入后依旧在输出键值，就连开关编辑模式也不能停止输出键值

### Java

Auto

### Renderer

Holy GL4E5 (OpenGL 2.1)

### Game Version

1.19.2

**Comment by ShirosakiMio** [comment]
修了
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/7954086919
