### ISSUE TITLE
使用键鼠时，需要便捷的输入法调出方式

### ISSUE THREAD

**Issue by fearry** [FCL-Team/FoldCraftLauncher#274]
### Description

针对键鼠添加更方便的输入法调出方式

### Why

用键鼠时没有快捷键调出输入法，鼠标也不能点击fcl虚拟按钮
想调出输入法又得戳屏幕，显然这是非常糟糕的，特别是在安卓平板上

**Comment by fearry** [comment]
这种需求是不是太小众了？

**Comment by Tungstend** [comment]
知道了，下个版本会加入这个功能

**Comment by ShirosakiMio** [comment]
有没有一种可能，按右边的alt就行（）

**Comment by fearry** [comment]
> 有没有一种可能，按右边的alt就行（）

你不说，还真的想不到，选择fcl的理由又多了一个

**Comment by Tungstend** [comment]
改成 enter 了，另外之前键鼠有些其他 bug，一并修复了，可以使用 action 里的最新构建
