### ISSUE TITLE
在1.1.4.3最新版本中，保持触发的虚拟按键（如潜行）无法松开

### ISSUE THREAD

**Issue by yuanbraing** [FCL-Team/FoldCraftLauncher#275]
### Launcher Version

1.1.4.3

### Device Information

Android 13

### Problem Description

当按下保持触发的虚拟按键时，它会一直按下，但再按时，虽然图标恢复成未按下状态，但游戏似乎并没有收到松开信号

### Java

Default

### Renderer

Vulkan Zink

### Game Version

1.20.1

### Modifications Made to the Game

Forge 机械动力0.5.1f 铷 铷 • 扩展 铁氧体磁芯

### Game Crash Report

未崩溃

### Launcher Crash Report

未崩溃

**Comment by Tungstend** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/7984382695
