### ISSUE TITLE
?? 

### ISSUE THREAD

**Issue by Tiger56c** [FCL-Team/FoldCraftLauncher#28]
Is this project dead

**Comment by TSaltedfishKing** [comment]
COULD YOU BE PATIENT PLEASE
IT IS EXTREMELY IMPOLITE FOR THE DEVELOPERS

**Comment by LegacyGamerHD** [comment]
> COULD YOU BE PATIENT PLEASE IT IS EXTREMELY IMPOLITE FOR THE DEVELOPERS

some on gets tired of those spams

**Comment by Tiger56c** [comment]
> COULD YOU BE PATIENT PLEASE IT IS EXTREMELY IMPOLITE FOR THE DEVELOPERS

I've been waiting for so long

**Comment by Tiger56c** [comment]
> > COULD YOU BE PATIENT PLEASE IT IS EXTREMELY IMPOLITE FOR THE DEVELOPERS
> 
> some on gets tired of those spams

What happened in hello launcher why there's no  updates?

**Comment by PIXIE0823** [comment]
Bruh 2 weeks and nothing

**Comment by HopiHopy** [comment]
> 布鲁两个星期什么都没有
The developers have temporarily halted development due to academic issues and are not expected to resume development until next year
