### ISSUE TITLE
增加报错详细性

### ISSUE THREAD

**Issue by Chinahfh** [FCL-Team/FoldCraftLauncher#280]
### Description

在中国主流启动器中，报错文件里面拥有异常在java中的类型(Type)，异常的信息(Message)，和堆栈跟踪(StackTrace)，它们更方便为人们找到错误，而我浏览了FCL的报错文件，发现里面似乎没有这三个东西，希望你们可以增加它，如果有，是我没有发现，希望你们可以将它标到基本信息下面

### Why

①可以在信息(Message)中找到“类”(class)通过类中的关键词找到哪个模组(Mod)引起了崩溃；②通过堆栈跟踪(stackTrace)，at后面每一个都是类(class)，一般来说，可直接排除at后面的java和minecraft。也可以帮助个人快速找到问题

**Comment by ShirosakiMio** [comment]
这东西并不是启动器生成的，是mc。一些报错类型比如IllegalArgumentException这种是会直接抛到jvm那边导致手机上的日志就显示一个openjdk exit code with 1，具体报错内容捕获不到
