### ISSUE TITLE
jar运行器使用当前游戏目录的默认java

### ISSUE THREAD

**Issue by hyplant** [FCL-Team/FoldCraftLauncher#282]
### Description

让jar运行器使用当前游戏目录的默认jre，以便使用其他jre的执行.jar文件。
若为自动选择，则使用jre8

**Comment by zkitefly** [comment]
有啥特殊的 JAR 需要非 Java 8 的？

**Comment by hyplant** [comment]
> 有啥特殊的 JAR 需要非 Java 8 的？
[运行minecraft数据生成器](https://zh.minecraft.wiki/w/Tutorial:%E8%BF%90%E8%A1%8C%E6%95%B0%E6%8D%AE%E7%94%9F%E6%88%90%E5%99%A8)
