### ISSUE TITLE
关于启动器的手柄适配

### ISSUE THREAD

**Issue by SinkEndTronier** [FCL-Team/FoldCraftLauncher#285]
### Description

目前，FCL启动的mc与手机所连接的手柄完全隔离，或许是虚拟按键屏蔽了外来输入。虽然不是什么要紧的事，但刚刚得知这个情况时，我确实失落了一下。但FCL的强大依然让我叹为观止。作者加油！

### Why

技多不压身，我认为适配手柄以及其他外来操纵设备还是很有必要的。

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/8246520349
加了
