### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by savvacorgi** [FCL-Team/FoldCraftLauncher#287]
### Launcher Version

Last update 

### Device Information

Teclast t40 pro eea android 12

### Problem Description

The bug does not log into my account, my main account simply does not add, my second one says no minecraft purchased

### Java

Idk

### Renderer

Idk

### Game Version

Idk

### Modifications Made to the Game

Idk

**Comment by savvacorgi** [comment]
🎉

**Comment by ShirosakiMio** [comment]
use browser and open minecraft.net to login again

**Comment by savvacorgi** [comment]
It fixed for me, I just tried it after a while but thanks 

> use browser and open minecraft.net to login again
