### ISSUE TITLE
pointer appears when press enter

### ISSUE THREAD

**Issue by FaryXMC** [FCL-Team/FoldCraftLauncher#288]
i use physical mouse, and as casually what i do, i open the launcher there's an update

and then after update i open minecraft and then when I pressed the enter key my **"mouse pointer"** appear and i cant get it back to the virtual mouse (using enter) i have to do with the "virtual" enter so that I can use it like normally what i do

i mean its nice but maybe you can remove the **"exit"** feature or replace to back button or whatever button instead of enter maybe?

**Comment by ShirosakiMio** [comment]
when press enter, it will open soft keyboard.

**Comment by Shota7481** [comment]
ooowh ok, maybe replaced **ctrl+enter?**

**Comment by Shota7481** [comment]
> when press enter, it will open soft keyboard.

oowh ok, maybe replace with **ctrl+enter**?
because why tf we need to use soft keyboard when using physical keyboard
