### ISSUE TITLE
奇怪的错误

### ISSUE THREAD

**Issue by ksGachaAxie** [FCL-Team/FoldCraftLauncher#289]
### Launcher Version

1.1.5

### Device Information

Huawei MatePad 11 HarmonyOS 4.0.0 arm 64

### Problem Description

游戏在此启动器版本进入世界后隔一段时间会闪退

### Game Version

1.20.1（fabric）

### Game Crash Report

[Uploading hs_err_pid12855.log…]()

### Launcher Log File

[Uploading latest_game.log…]()

**Comment by zkitefly** [comment]
日志没有上传成功，`Uploading` 字样消失才是上传成功

**Comment by ksGachaAxie** [comment]
[latest_game.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14462146/latest_game.log)
抱歉家里网不好

**Comment by ksGachaAxie** [comment]
补充
[hs_err_pid12855.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14463250/hs_err_pid12855.log)

**Comment by ShirosakiMio** [comment]
mod问题导致jvm崩溃了

**Comment by ShirosakiMio** [comment]
是xaero的地图

**Comment by ShirosakiMio** [comment]
老毛病了

**Comment by ShirosakiMio** [comment]
换成旅行地图啥的都行，别用xaero
