### ISSUE TITLE
Can anyone help me?!

### ISSUE THREAD

**Issue by netflexs** [FCL-Team/FoldCraftLauncher#292]
### Launcher Version

Latest

### Device Information

Xiaomi Redmi Note 12 4G NFC (Topaz)

### Problem Description

Always force close

### Java

Java auto

### Renderer

Zink

### Game Version

1.20.1

### Modifications Made to the Game

Vulkanite modpack

### Launcher Log File

[fcl-latest3316667947170805061.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14471467/fcl-latest3316667947170805061.log)

**Comment by ShirosakiMio** [comment]
vulkanmod is not supported by FCL

**Comment by netflexs** [comment]
> vulkanmod is not supported by FCL

really i though it was, cause it support zink.

**Comment by ShirosakiMio** [comment]
yes, it's different
