### ISSUE TITLE
功耗异常

### ISSUE THREAD

**Issue by YunnrEX** [FCL-Team/FoldCraftLauncher#293]
### Launcher Version

最新版本

### Device Information

k70p 12+256

### Problem Description

进入游戏后功耗异常，cpu单核运行。经过多次测试和功率记录，游戏平均功耗在8-11w，手机电池迅速升温至温度墙。多个手机测试发现问题都会出现，手机严重发热。

### Java

jre21

### Renderer

holy

### Game Version

1.20.4fa

**Comment by YunnrEX** [comment]
很明显，只有一个大核在工作，不知道是java遗留问题还是游戏适配问题

**Comment by root-S7** [comment]
功耗高不更正常么，哪不正常了。况且这也算游戏应用呀

**Comment by YunnrEX** [comment]
很少见有游戏 10w功耗，正常都是 3-6w，10w功耗发热量太大了，不知道是在手机运行java都这样还是什么情况

**Comment by root-S7** [comment]
1080P分辨率10w确实不高

**Comment by ShirosakiMio** [comment]
你可以逝世关掉基岩版触控，我发现那个东西一开，cpu直接100%

**Comment by YunnrEX** [comment]
正确的，关闭基岩版触控，功耗稳定在 4-7w了
