### ISSUE TITLE
如图，玩家启动b1.2_01~b1.4_01（目前测试的）后进入服务器名字会变成net.minecraft.launchwrapper.Launch

### ISSUE THREAD

**Issue by high20212021** [FCL-Team/FoldCraftLauncher#294]
### Launcher Version

1.1.5

### Device Information

Redmi Note 7,Android 10,arm64

### Problem Description

如下
![Screenshot_2024-03-05-01-26-53-344_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/127644288/416b2495-524f-44a3-91c4-7b2eec23d5ec)

### Java

Java 8

### Renderer

Hole-GL4ES

### Game Version

b1.4_01

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/8149693391
用这个

**Comment by high20212021** [comment]
还是一样
![Screenshot_2024-03-05-12-53-12-204_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/127644288/55692bd5-137f-4123-ac77-4f9159393e20)

**Comment by high20212021** [comment]
？好玄学
重启之后正常了
![Screenshot_2024-03-05-12-58-11-510_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/127644288/bb7d5026-b8b5-41dd-95a4-c8e0c59ead4b)
