### ISSUE TITLE
[Request] <Update OpenGl4Es>

### ISSUE THREAD

**Issue by N0Lu6k** [FCL-Team/FoldCraftLauncher#295]
### Description

Update OpenGl4Es 2.0 to 3.2 

### Why

other people needs this version os OpenGL4ES to run Minecraft with faster and more compatibility and can run almost all of mods like sodium without paching

**Comment by N0Lu6k** [comment]
pls do it

**Comment by ShirosakiMio** [comment]
you should go here https://github.com/ptitSeb/gl4es

**Comment by N0Lu6k** [comment]
what about virgl and agle the virgl have issues cant load to minecraft stuck in red screen and  agle have no texture

**Comment by N0Lu6k** [comment]
> you should go here https://github.com/ptitSeb/gl4es

:https://www.khronos.org/opengles/

how about this
