### ISSUE TITLE
virgl renderer stock on loading screen

### ISSUE THREAD

**Issue by N0Lu6k** [FCL-Team/FoldCraftLauncher#299]
### Launcher Version

1.1.5

### Device Information

OPPO A92 CPH2059

### Problem Description

stock on red loading screen

### Java

java17

### Renderer

vigl

### Game Version

1.20.1

### Modifications Made to the Game

fabric loader

**Comment by zkitefly** [comment]
Please upload logs

**Comment by ShirosakiMio** [comment]
no log and it's not recommend to use virgl with Snapdragon CPU
