### ISSUE TITLE
Need Swap jump and sneak 需要交换跳跃和潜行的设置

### ISSUE THREAD

**Issue by shenmo7192** [FCL-Team/FoldCraftLauncher#301]
### Description

Now the D-Pad only support jump and right place
现在只能在右侧按钮跳跃

### Why

习惯了旧版操作方式
I used to the legacy joystick

**Comment by zkitefly** [comment]
怎么不自己改下按钮位置？（

**Comment by shenmo7192** [comment]
> 怎么不自己改下按钮位置？（

是这样，十字键是一体的，不能改(((

**Comment by root-S7** [comment]
十字键可以删掉然后单独增加上下左右wasd键盘然后中间的自行加即可
