### ISSUE TITLE
使用lwjgl3ify时的bug

### ISSUE THREAD

**Issue by REYXTE** [FCL-Team/FoldCraftLauncher#302]
### Launcher Version

1.1.5.1

### Device Information

arm64 Android12

### Problem Description

使用lwjgl3ify时会导致背包等按键无效

### Java

Java17/Java21

### Renderer

holy

### Game Version

1.7.10

### Modifications Made to the Game

Forge

**Comment by ShirosakiMio** [comment]
打开lwjgl3ify的jar包，删除里面的org/lwjgl/input文件夹
