### ISSUE TITLE
Minecraft run out of memory

### ISSUE THREAD

**Issue by Proaman7603** [FCL-Team/FoldCraftLauncher#305]
### Launcher Version

1.1.5

### Device Information

Poco c3

### Problem Description

Whenever I play Minecraft like after 30 minutes I get a error like Minecraft run out of memory
I didn't get this problem in pojavlauncher
I setted my memory to 700 mb 
But it crashes

### Java

Java 17

### Renderer

Holy 

### Game Version

1.20.1

### Modifications Made to the Game

Optifine hd u5

### Launcher Log File

[latest_game.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14549587/latest_game.log)
Pls fix this

**Comment by FrostNovaHD** [comment]
not foldcrafts issue if your device doesnt have anough memory

**Comment by Proaman7603** [comment]
How to see how much memory I can allocate in foldcraft. I have allocated same memory in pojav but it doesn't crashes
