### ISSUE TITLE
希望FCL能识别更多的跳转类型

### ISSUE THREAD

**Issue by snow-sky233** [FCL-Team/FoldCraftLauncher#306]
### Description

目前在游戏内好多地方仍然无法识别该跳转到哪个应用（浏览器网页已有，所以除外）。比如打开文件及文件夹无法正确识别，直接跳转到系统的HTML查看器，建议之后添加一些类型的识别，建议让启动器打开游戏后能够正常识别并跳转到正确的应用程序

### Why

因为这样在游戏内导入资源包等不需要重启游戏的数据时可能会更方便。

**Comment by ShirosakiMio** [comment]
这得看系统了，我只能确保miui上能正确跳转

**Comment by ShirosakiMio** [comment]
至少在我的手机上是能跳到mt管理器的

**Comment by snow-sky233** [comment]
好吧，也许真是手机问题
