### ISSUE TITLE
VIRGLrenderer (openGL 4.3) error

### ISSUE THREAD

**Issue by alexdkkdj** [FCL-Team/FoldCraftLauncher#308]
### Launcher Version

1.1.5.2

### Device Information

Xiomi redmi note 12 ,8 GB  ram 

### Problem Description

When I enter the game nothing that has writing appears, all the words disappear when I enter the home screen and the world

### Java

Java auto 

### Game Version

VIRGLrenderer (openGL 4.3) 

### Modifications Made to the Game

Modpcak

**Comment by ShirosakiMio** [comment]
not work with adreno gpu, only mali gpu can render the words properly
