### ISSUE TITLE
日志中没有将 accessToken 进行过滤处理

### ISSUE THREAD

**Issue by zkitefly** [FCL-Team/FoldCraftLauncher#309]
![IMG_20240315_182736.jpg](https://github.com/FCL-Team/FoldCraftLauncher/assets/64117916/4176aa41-be24-4d49-b07a-9d47d582ad18)

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/commit/d4289031626e4ff3d77e0f4b44917680b0216187
