### ISSUE TITLE
Version 1.16.5 crashing when joining server 

### ISSUE THREAD

**Issue by Saddamkhanjadara** [FCL-Team/FoldCraftLauncher#311]
### Launcher Version

1.1.5.1

### Device Information

Poco c51 Android 13(go edition) arm32 

### Problem Description

Game crashing when joining server in 1.16.5 version with sodium 

### Java

Auto 

### Renderer

Holy-GL4ES

### Game Version

1.16.5

### Modifications Made to the Game

Fabric sodium 

### Launcher Log File

[latest_game.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14626516/latest_game.log)
[latest_jar_executor.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14626517/latest_jar_executor.log)

**Comment by root-S7** [comment]
Could not reserve enough space for 3899392KB object heap

**Comment by Saddamkhanjadara** [comment]
Now see the latest log file

**Comment by Saddamkhanjadara** [comment]
> ### Launcher Version
> 1.1.5.1
> 
> ### Device Information
> Poco c51 Android 13(go edition) arm32
> 
> ### Problem Description
> Game crashing when joining server in 1.16.5 version with sodium
> 
> ### Java
> Auto
> 
> ### Renderer
> Holy-GL4ES
> 
> ### Game Version
> 1.16.5
> 
> ### Modifications Made to the Game
> Fabric sodium
> 
> ### Game Crash Report
> _No response_
> 
> ### Launcher Crash Report
> _No response_
> 
> ### Launcher Log File
> [latest_game.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14626516/latest_game.log) [latest_jar_executor.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14626517/latest_jar_executor.log)

[2024-03-17-3.log.gz](https://github.com/FCL-Team/FoldCraftLauncher/files/14626563/2024-03-17-3.log.gz)
[latest.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14626564/latest.log)

**Comment by ShirosakiMio** [comment]
no sodium
