### ISSUE TITLE
物品栏切换非常困难且错位

### ISSUE THREAD

**Issue by XZH2024** [FCL-Team/FoldCraftLauncher#317]
### Launcher Version

1.1.5.1

### Device Information

小米5s，Android8，arm64

### Problem Description

如视频所示
[FCL.zip](https://github.com/FCL-Team/FoldCraftLauncher/files/14717000/FCL.zip)

### Java

java21

### Renderer

holy gl4es

### Game Version

1.20.1

### Modifications Made to the Game

fabric

**Comment by XZH2024** [comment]
还有个小问题补充下，在版本和设置相同的情况下，pojavlauncher的帧率和％1low都比fcl高很多，分辨率都是50％，渲染器都是holy，具体原因未知，虽然mod安装等功能fcl的确还不错，但是实际游戏体验方面和pojavlauncher相差甚远。
导致我现在喜欢用fcl安装mc，装好后用pojav玩😂

**Comment by zkitefly** [comment]
> 还有个小问题补充下，在版本和设置相同的情况下，pojavlauncher的帧率和％1low都比fcl高很多，分辨率都是50％，渲染器都是holy，具体原因未知，虽然mod安装等功能fcl的确还不错，但是实际游戏体验方面和pojavlauncher相差甚远。 导致我现在喜欢用fcl安装mc，装好后用pojav玩😂

https://github.com/FCL-Team/FoldCraftLauncher/issues/293#issuecomment-1977820220

**Comment by DSY-xiaoluo** [comment]
> ### Launcher Version
> 
> 1.1.5.1
> ### Device Information
> 
> 小米5s，Android8，arm64
> ### Problem Description
> 
> 如视频所示 [FCL.zip](https://github.com/FCL-Team/FoldCraftLauncher/files/14717000/FCL.zip)
> ### Java
> 
> java21
> ### Renderer
> 
> holy gl4es
> ### Game Version
> 
> 1.20.1
> ### Modifications Made to the Game
> 
> fabric
> ### Game Crash Report
> 
> _No response_
> ### Launcher Crash Report
> 
> _No response_
> ### Launcher Log File
> 
> _No response_

我以前发现更改分辨率后物品栏点击就错位了，于是我自己在按键里手动加了9个物品栏按键，不知道现在修复没有

**Comment by ShirosakiMio** [comment]
> > ### Launcher Version
> > 1.1.5.1
> > ### Device Information
> > 小米5s，Android8，arm64
> > ### Problem Description
> > 如视频所示 [FCL.zip](https://github.com/FCL-Team/FoldCraftLauncher/files/14717000/FCL.zip)
> > ### Java
> > java21
> > ### Renderer
> > holy gl4es
> > ### Game Version
> > 1.20.1
> > ### Modifications Made to the Game
> > fabric
> > ### Game Crash Report
> > _No response_
> > ### Launcher Crash Report
> > _No response_
> > ### Launcher Log File
> > _No response_
> 
> 我以前发现更改分辨率后物品栏点击就错位了，于是我自己在按键里手动加了9个物品栏按键，不知道现在修复没有

你可以用用这个https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/8385980108
我加了一个物品栏缩放，在右侧菜单里

**Comment by XZH2024** [comment]
> > 还有个小问题补充下，在版本和设置相同的情况下，pojavlauncher的帧率和％1low都比fcl高很多，分辨率都是50％，渲染器都是holy，具体原因未知，虽然mod安装等功能fcl的确还不错，但是实际游戏体验方面和pojavlauncher相差甚远。 导致我现在喜欢用fcl安装mc，装好后用pojav玩😂
> 
> [#293 (comment)](https://github.com/FCL-Team/FoldCraftLauncher/issues/293#issuecomment-1977820220)

我之前已经关闭了基岩版控制手势，但pojav帧率还是比fcl高不少，可能是因为pojav有强制大核渲染等功能😂

**Comment by XZH2024** [comment]
使用物品栏缩放后，可以正常切换物品栏了
