### ISSUE TITLE
Minecraft统一通行证

### ISSUE THREAD

**Issue by ZXY-Baa** [FCL-Team/FoldCraftLauncher#319]
### Description

希望添加对Minecraft统一通行证登录的支持

### Why

Minecraft统一通行证为服主提供了方便且快捷的管理操作，一些服务器需通过Minecraft统一通行证来完成登录并验证的操作 加入此项功能可以使更多服主选择FCL启动器

**Comment by zkitefly** [comment]
fcl 的游戏功能部分使用 hmclcore，而 hmcl 那不接受统一通行证，所以。。。

**Comment by ZXY-Baa** [comment]
有道理 ......

**Comment by blmulang** [comment]
> fcl 的游戏功能部分使用 hmclcore，而 hmcl 那不接受统一通行证，所以。。。

希望能增加 😔
