### ISSUE TITLE
The touchpad/mouse control is a bit bugged.

### ISSUE THREAD

**Issue by Happiness777** [FCL-Team/FoldCraftLauncher#32]
Hello, I just wanted to point out that the launcher has bugged mouse right now. It's weirdly more sensitive to movements to the right/down, than to the left/up.

I have a [video](https://drive.google.com/file/d/1J6d1P4GlaCU2nx3RrOqQsGlqDCT_Dg-M/view?usp=sharing) of the bug, maybe it'll explain things better.

**Comment by Happiness777** [comment]
Oh, also, if the sensitivity is above 130%, the cursor/pointer is being pulled towards bottom left corner of the screen. This makes controlling camera with high sensitivity almost impossible.

**Comment by Happiness777** [comment]
I managed to fix it, by modifying the `com/tungsten/fcl/control/view/TouchPad.java`.

In the original version, the calculation for `deltaX` and `deltaY` was based on the original `downX` and `downY` values, which were only updated once when the `ACTION_DOWN` event occurred. This caused the cursor to drift when moving, because the calculation for movement was always relative to the initial press location.

To fix this, I updated the `downX` and `downY` values every time an `ACTION_MOVE` event occurred.

Here's the specific change in the code:

Old Version:
```java
int deltaX = (int) ((event.getX(pointerIndex) - downX) * gameMenu.getMenuSetting().getMouseSensitivity());
int deltaY = (int) ((event.getY(pointerIndex) - downY) * gameMenu.getMenuSetting().getMouseSensitivity());

// Rest of the code

downX = (int) event.getX(pointerIndex);
downY = (int) event.getY(pointerIndex);
break;
```

New Version:
```java
int newDownX = (int) event.getX(pointerIndex);
int newDownY = (int) event.getY(pointerIndex);
int deltaX = (int) ((newDownX - downX) * gameMenu.getMenuSetting().getMouseSensitivity());
int deltaY = (int) ((newDownY - downY) * gameMenu.getMenuSetting().getMouseSensitivity());

// Rest of the code

downX = newDownX;
downY = newDownY;
break;
```

As you can see, in the new version, I calculate `newDownX` and `newDownY` first, then use these new values to calculate `deltaX` and `deltaY`. After that, I update `downX` and `downY` with the new values. This ensures that each movement is calculated relative to the previous location rather than the initial press location, preventing the cursor from drifting.

**Comment by LithuanianBoi41** [comment]
Add lib gl4es 1.1.5

**Comment by Happiness777** [comment]
@LithuanianBoi41 why?
