### ISSUE TITLE
第三方认证服务器登录失效无法重新输入密码

### ISSUE THREAD

**Issue by DanielToyama** [FCL-Team/FoldCraftLauncher#322]
### Launcher Version

1.1.5.1

### Device Information

Redmi K50pro Android12 arm64

### Problem Description

第三方验证服务器littleskin验证失效之后，无法正确弹出代码框，UI变暗但是密码框无法弹出

### Java

/

### Renderer

/

### Game Version

/

### Modifications Made to the Game

/

### Game Crash Report

/

### Launcher Crash Report

/

### Launcher Log File

/

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/commit/3e72a2672bc3baa085b7ab9afa5e5b9626edfb3b
