### ISSUE TITLE
Add controller support 🎮

### ISSUE THREAD

**Issue by i448** [FCL-Team/FoldCraftLauncher#325]
### Description

It would be great if controller support is added. Would wish it to be integrated to the controller menu. So no need to mod the vanilla game. But I also wish that it is possible to work with mods in x-input mode since some mod packs adds vibrations to it.

### Why

Would like to play with a d-input or x-input controller on my phone. I also wish to use the extra back paddles of my controller when in d-input mode.

**Comment by Axi0mBCS** [comment]
Iirc there is a actions build that supports gaming controllers

**Comment by i448** [comment]
What action? When I connected my controller the only button that works is the y button

**Comment by Axi0mBCS** [comment]
As far as I remember, it's the one called "Fix add & ItemBarScale".

**Comment by Axi0mBCS** [comment]
No, it's a beta version of FCL only available in the "actions" section.

**Comment by i448** [comment]
Oh, your talking about that. I was like what "action" are you talking about? Thanks, will try compiling.

**Comment by i448** [comment]
So I guess I can close this thread?
