### ISSUE TITLE
运行jar安装器时，所有中文字符乱码

### ISSUE THREAD

**Issue by high20212021** [FCL-Team/FoldCraftLauncher#328]
### Launcher Version

1.1.5.1

### Device Information

Redmi Note 7,Android 10,arm64

### Problem Description

如图
![1711810145591](https://github.com/FCL-Team/FoldCraftLauncher/assets/127644288/6350467f-8c55-4ef7-a980-d5bc2761247c)

**Comment by aaaapai** [comment]
运行时的问题

**Comment by aaaapai** [comment]
e
![Screenshot_20240331_235044_net kdt pojavlaunch debug](https://github.com/FCL-Team/FoldCraftLauncher/assets/89151134/a912a444-0fee-43a4-916f-bf5b64d99bed)
