### ISSUE TITLE
内置Frp内网穿透

### ISSUE THREAD

**Issue by BigLlk** [FCL-Team/FoldCraftLauncher#329]
### Description

可以在启动器里加上使用Frp内网穿透配置文件的功能，我记得Frp好像是开源的
让用户到网站里获取隧道的配置文件，再把配置文件复制到启动器里，然后启动器就可以内网穿透。联机比较方便，而且不需要自己出服务器什么的，安卓的那个Frp app适配不了那些网站的新版配置文件只能用旧的，但是又找不到旧的，所以希望能加上

### Why

方便联机

**Comment by BigLlk** [comment]
> 知道hmcl,pcl,bakaxl的联机功能怎么没的吗？

不知道，请问是怎么没的？

**Comment by BigLlk** [comment]
> 知道hmcl,pcl,bakaxl的联机功能怎么没的吗？

我能搜到的就是有人给龙腾猫跃提供第三方联机服务，然后变卦收费
但是我说的是内置frp，让用户自己去，樱花，星空，这些地方找frp配置，然后再在fcl启动器里面填写配置，以达到联机的目的
这个不需要自己提供服务器，自己不需要出钱，这些我原文里提到过

**Comment by ZSXB2468** [comment]
~~可是这些frp的延迟其实挺高的（~~
如果你会使用Android的命令行软件，可以直接去frp的仓库下载release，解压，运行里面的frpc
不会的话可以试试这个软件https://github.com/AceDroidX/frp-Android/
（我还没试过，你可以试着折腾下）

如果fcl能内置的话当然是更好的
