### ISSUE TITLE
添加FFmpeg插件

### ISSUE THREAD

**Issue by 0zjn0123** [FCL-Team/FoldCraftLauncher#336]
### Description

如题，我需要用replaymod渲染需要FFmpeg

### Why

用于渲染replay

**Comment by zkitefly** [comment]
自己加呗，为啥要启动器加呢（

**Comment by 0zjn0123** [comment]
我自己咋加？

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/8657568004

**Comment by 0zjn0123** [comment]
> https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/8657568004

我试了一下还是需要FFmpeg
![Screenshot_20240414_131645_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/116432703/2a21617d-dfcd-4404-8428-92e21509c50e)

**Comment by ShirosakiMio** [comment]
这个是兼容pojav的那个插件

**Comment by 0zjn0123** [comment]
> 这个是兼容pojav的那个插件

意思是我还需要安装pojav的FFmpeg插件？

**Comment by 0zjn0123** [comment]
> 这个是兼容pojav的那个插件

我把pojav的FFmpeg插件装上了还是需要

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/8678748102

**Comment by 0zjn0123** [comment]
> 这个是兼容pojav的那个插件

两个都试了还是不行

**Comment by ShirosakiMio** [comment]
有俩变量忘记加了
用这个就行了https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/8679003054

**Comment by 0zjn0123** [comment]
> 有俩变量忘记加了 用这个就行了https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/8679003054

还是不行

**Comment by ShirosakiMio** [comment]
> > 有俩变量忘记加了 用这个就行了https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/8679003054
> 
> 还是不行

1.12.2我测试是没问题了

**Comment by 0zjn0123** [comment]
> > > 有俩变量忘记加了 用这个就行了https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/8679003054
> > 
> > 
> > 还是不行
> 
> 1.12.2我测试是没问题了

啊这，我用的1.20.4

**Comment by ShirosakiMio** [comment]
高版本好像pojav都用不了来着。。。

**Comment by 0zjn0123** [comment]
> 高版本好像pojav都用不了来着。。。

那咋办啊（）

**Comment by ShirosakiMio** [comment]
兼容的是pojav的插件，pojav都不能用，那不是我们的问题了

**Comment by 0zjn0123** [comment]
> 兼容的是pojav的插件，pojav都不能用，那不是我们的问题了

那好吧（
