### ISSUE TITLE
Sodium and rebidium support 

### ISSUE THREAD

**Issue by MoonKnightBhai** [FCL-Team/FoldCraftLauncher#34]
Will support for sodium (fabric) and rebidium( wich is sodium for forge ) be added to FCl? [Just a question ]

**Comment by LegacyGamerHD** [comment]
No it won't work same limitation as pojav

**Comment by MoonKnightBhai** [comment]
But using sodium patcher on sodium now works in it. but on FCL I have seen that optiFabric dosent want to start for mid range phones but on forge it works upto 1.20 that's why I asked about it ok thanks for reply

**Comment by PIXIE0823** [comment]
How you have the apk ?

**Comment by MoonKnightBhai** [comment]
> How you have the apk ?
It's open source so my friend compiled it.
