### ISSUE TITLE
建议增加游戏版本搜索功能

### ISSUE THREAD

**Issue by REYXTE** [FCL-Team/FoldCraftLauncher#341]
### Description

在这个页面
![Uploading Screenshot_2024_0413_090003_com.tungsten.fcl.png…]()
增加搜索功能

### Why

增加了搜索可以让愚人节/快照版更加方便下载。

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/12349150158
