### ISSUE TITLE
能否增加一个功能，在识别不到你有正版的时候可以选择打开官网登录账号刷新一下登录状态

### ISSUE THREAD

**Issue by xiaoluo2333** [FCL-Team/FoldCraftLauncher#344]
### Description

有的时候启动游戏时会提示登录错误，然后重新添加微软账号时会提示没有正版账号，解决办法就是去系统浏览器重新登录我的世界官网就能正常识别到正版账号了

### Why

加了这个功能就再也不用打开浏览器登录官网了

**Comment by zkitefly** [comment]
https://github.com/HMCL-dev/HMCL/pull/2986

如果该 PR 的修复是可行的，那么 FCL 同步 HMCLCore 后会同步修复该为题

也就是不用跑到 minecraft.net 登录一下再回来登录了

**Comment by xiaoluo2333** [comment]
其实这个问题电脑上也有，但是发生的概率好像很低（
发这个建议之前我在b站上也有看到过也有人跟我发生过这样的问题

**Comment by zkitefly** [comment]
FCL 的功能部分是使用了 HMCL 的 HMCLCore 的，所以 HMCL 出问题，FCL 大概率也会出问题

**Comment by xiaoluo2333** [comment]
懒得再写个issue了，我再提个建议，对于运行jar文件那个功能能否在设置里边加个单独的设置项，就是可以允许用户运行jar文件时可以带参数或者是换一个Java版本（感谢termux这个高级控制台居然只有jdk17(◕︿◕✿)）
