### ISSUE TITLE
发现个问题，fcl自带的文件查看的使用外部应用打开那个按钮点了没反应

### ISSUE THREAD

**Issue by xiaoluo2333** [FCL-Team/FoldCraftLauncher#346]
### Launcher Version

1.1.6

### Device Information

vivo y76s   安卓11

### Problem Description

在给离线用户加皮肤的时候发现的，那个按钮点了没有任何反应

https://github.com/FCL-Team/FoldCraftLauncher/assets/132722330/e3b729fc-0a55-42bd-bbfc-70498460cbf4

**Comment by ShirosakiMio** [comment]
用户储存根目录你直接管理器里打开啊，provider不允许打开
![image](https://github.com/FCL-Team/FoldCraftLauncher/assets/19233890/b37564f5-1f02-4528-a476-17c7c8596062)
