### ISSUE TITLE
执行Jar文件时崩溃

### ISSUE THREAD

**Issue by HalfShadow111** [FCL-Team/FoldCraftLauncher#347]
### Launcher Version

1.1.6

### Device Information

IQOO Z5, Android 13 arm64

### Problem Description

执行Jar文件时会崩溃
我想装Legacy Fabric的时候崩溃了，以前版本的FCL是可以安装的，但是Cursed Legacy Fabric、Ornithe和Babric之类的模组加载器不能安装，现在什么Jar文件（无论Forge、Fabric还是NeoForge）都不能执行了

### Launcher Crash Report

[crash_report8192570915838688396.txt](https://github.com/FCL-Team/FoldCraftLauncher/files/14967257/crash_report8192570915838688396.txt)

**Comment by ShirosakiMio** [comment]
我的锅，修好了
