### ISSUE TITLE
How to compiled the code ?

### ISSUE THREAD

**Issue by PIXIE0823** [FCL-Team/FoldCraftLauncher#35]
Hey, I using an android and I want to know to compile the app ?

**Comment by LegacyGamerHD** [comment]
If you don't know how to compile I don't think you should use it

**Comment by PIXIE0823** [comment]
The person who as the apk file plz give me it on media fire or quick share I want to download it plz plz

**Comment by PIXIE0823** [comment]
Have* sorry I'm French

**Comment by zkitefly** [comment]
https://www.123pan.com/s/0cC7Vv-dMeov.html

> https://b23.tv/B9BLXbA

**Comment by PIXIE0823** [comment]
Thx zkitefly

**Comment by PIXIE0823** [comment]
How to change control?

**Comment by PIXIE0823** [comment]
Bruh doesn't work you can't give me your apk

**Comment by PIXIE0823** [comment]
?

**Comment by MoonKnightBhai** [comment]
> Bruh doesn't work you can't give me your apk

Join HMCLPE discord server there u will find the download link of the old version
BUT REMEMBER this is not the complete version of FCl so the application has a lot of BUGS 
Here is the link :https://discord.gg/zHV92j8t

**Comment by PIXIE0823** [comment]
Thx

**Comment by PIXIE0823** [comment]
I just want the recent apk compilated and I finish on suspicious website 💀

**Comment by MoonKnightBhai** [comment]
> I just want the recent apk compilated and I finish on suspicious website 💀

Yes u will get the second most recent one after when big chunk of update is added apk will be updated .also after finishing this plz close the issues tab.

**Comment by LegacyGamerHD** [comment]
You can get the latest here https://github.com/LegacyGamerHD/FoldCraftLauncher

**Comment by MoonKnightBhai** [comment]
> You can get the latest here https://github.com/LegacyGamerHD/FoldCraftLauncher

One question i have will there be .jar installer for clients like labby CMP pack lunar etc ??

**Comment by root-S7** [comment]
https://icraft.ren:90/tmp/FCL%e4%bf%ae%e5%a4%8d%e7%89%88.apk

Only "CN" translation
