### ISSUE TITLE
Game Freeze in forge Minecraft 1.12.2,check out pls

### ISSUE THREAD

**Issue by didntpenguin** [FCL-Team/FoldCraftLauncher#36]
.........like title

**Comment by LegacyGamerHD** [comment]
not really helpful without a log or logcat

**Comment by didntpenguin** [comment]
> not really helpful without a log or logcat

send soon :3

**Comment by didntpenguin** [comment]
https://drive.google.com/file/d/12BepKkpWQYSkH5LmxO16nW0CbwQ8ZsnJ/view?usp=drive_link
