### ISSUE TITLE
Can't start world with optifabric 

### ISSUE THREAD

**Issue by op30mmd** [FCL-Team/FoldCraftLauncher#368]
### Launcher Version

1.1.6.1

### Device Information

Samsung galaxy A05s, android 14, arm64

### Problem Description

I can't start a world with optifabric mod, i checked the logs and it says "failed to start profiler" and "failed to stop profiler" what to do?

### Java

17

### Renderer

Holy-GL4ES

### Game Version

1.20.1

### Modifications Made to the Game

Fabric, optifine 

### Game Crash Report

[latest_game.log](https://github.com/FCL-Team/FoldCraftLauncher/files/15271625/latest_game.log)

### Launcher Log File

[fcl-exported-logs-2024-05-10T10-54-01.log](https://github.com/FCL-Team/FoldCraftLauncher/files/15271630/fcl-exported-logs-2024-05-10T10-54-01.log)

**Comment by FrostNovaHD** [comment]
Works for me so

**Comment by FrostNovaHD** [comment]
Also not the right log am closing it

**Comment by op30mmd** [comment]
What? Did you looked the logs?
