### ISSUE TITLE
新版本java？

### ISSUE THREAD

**Issue by aaaapai** [FCL-Team/FoldCraftLauncher#37]
希望能更新一下java运行库
java17-->java17.0.9
java1.8.0-->java8_392

**Comment by Tungstend** [comment]
我记得Java版本过高也会导致部分版本无法运行，而且更新java没啥实际意义，而且麻烦

**Comment by root-S7** [comment]
> 我记得Java版本过高也会导致部分版本无法运行，而且更新java没啥实际意义，而且麻烦
之前有个bug，有些皮肤站对Java8版本有要求，太低会崩端
https://github.com/yushijinhun/authlib-injector/issues/207

**Comment by aaaapai** [comment]
> 我记得Java版本过高也会导致部分版本无法运行，而且更新java没啥实际意义，而且麻烦

行吧，你随意。高版本java对我来讲有很大的意义
