### ISSUE TITLE
Modpacks crashing

### ISSUE THREAD

**Issue by didntpenguin** [FCL-Team/FoldCraftLauncher#38]
some modpacks like hexxit updated,regrowth, hypothermia,ftb revelation and much much crashing like this...but work on pojav,hope u fix :3 because i like this launcher gui,pojav gud af but gui is bad,and didnt have modpacks downloader,mod downloader and some features:3

**Comment by didntpenguin** [comment]
https://drive.google.com/file/d/1XvI7x8mO7JEEhRCT-iRU7E8rDDYpCiWJ/view?usp=drive_link

**Comment by didntpenguin** [comment]
> https://drive.google.com/file/d/1XvI7x8mO7JEEhRCT-iRU7E8rDDYpCiWJ/view?usp=drive_link

logcat

**Comment by aaaapai** [comment]
I guess it's because the Java version is too old. Java 17 of this launcher was compiled in 2021.

**Comment by aaaapai** [comment]
I guess it's because the Java version is too old. Java 17 of this launcher was compiled in 2021.

**Comment by Tungstend** [comment]
Not sure the reason but looks like a scala error, try the latest release, delete all libraries and launch again, it will auto download new libraries, old builds download wrong scala libs

**Comment by didntpenguin** [comment]
> Not sure the reason but looks like a scala error, try the latest release, delete all libraries and launch again, it will auto download new libraries, old builds download wrong scala libs

okayy
