### ISSUE TITLE
LogWindow 问题

### ISSUE THREAD

**Issue by control0forver** [FCL-Team/FoldCraftLauncher#380]
### Launcher Version

1.1.6.1

### Device Information

Redmi Note 8 Pro, Android 11, arm64

### 若用户无法在启动游戏后第一时间开启该开关，用户很可能会错过来自日志的关键信息。

_`(我曾因为一个mod在启动游戏后一开始就会报错并终止游戏加载 但其不会使游戏崩溃(这让游戏看起来永远都正在启动中)，而我尝试多次后 每次都会因打开显示日志后一直都是空白 CPU及内存也无明显资源占用，我还以为是Java或者游戏文件损坏所导致)`_

### Java

Java 17

### Renderer

ANGLE

### Game Version

1.20.1

### Modifications Made to the Game

Fabric 0.15.11

**Comment by ShirosakiMio** [comment]
完整日志请看FCL/logs/latest_game.log。游戏内的日志窗口为了防止记录太多日志而卡顿会在每次开/关时清除并且记录到达100行也会清除，重新记录。
