### ISSUE TITLE
启动器反复崩溃无法启动

### ISSUE THREAD

**Issue by guobao2333** [FCL-Team/FoldCraftLauncher#389]
### Launcher Version

1.1.6.1 & 1.1.6.2

### Device Information

OPPO A3, Android10, arm64

### Problem Description

刚刚打开程序后收到了1.1.6.2版本的更新弹窗，点击更新后又不小心点到了取消，然后我想着那就待会再说，然后点击了启动游戏，结果就崩溃了，并且无论如何都无法启动  
接下来我尝试更新至1.1.6.2版本后重新打开，依旧崩溃，这可能是个严重bug……

### Launcher Crash Report

[crash_report7872932386560559367.txt](https://github.com/FCL-Team/FoldCraftLauncher/files/15454252/crash_report7872932386560559367.txt)

### Launcher Log File

这个是`FCL/log`目录下的日志文件，因为我目前无法打开启动器
[fcl.log](https://github.com/FCL-Team/FoldCraftLauncher/files/15454265/fcl.log)

**Comment by ShirosakiMio** [comment]
似乎是按键的问题，FCL/control这个文件夹你可以改成例如FCL/control_再打开看看

**Comment by guobao2333** [comment]
> 似乎是按键的问题，FCL/control这个文件夹你可以改成例如FCL/control_再打开看看

感谢，已经可以打开了。
我查看了一下原来的按键配置，似乎是因为上次崩溃导致了没有保存，而且文件也损坏了……Default.json完全是空的
