### ISSUE TITLE
Replay mod

### ISSUE THREAD

**Issue by Llerey** [FCL-Team/FoldCraftLauncher#403]
### Description

ffmpeg support for  Replay mod rendering

### Why

Add ffmpeg executables to support exporting video recordings of replay mod.
A similar idea has already been in the Pojav community
https://github.com/PojavLauncherTeam/PojavLauncher/issues/2572

**Comment by Llerey** [comment]
I think it would be possible to use the binary file in the termux application path
![Uploading Screenshot_2024-06-09-22-24-25-930_com.termux.jpg…]()

**Comment by Llerey** [comment]
![Uploading Screenshot_2024-06-09-22-24-25-930_com.termux.jpg…]()

**Comment by Llerey** [comment]
![1](https://github.com/FCL-Team/FoldCraftLauncher/assets/95129675/480b4523-5dc5-4d83-8591-436868b61fa6)
![2](https://github.com/FCL-Team/FoldCraftLauncher/assets/95129675/935e05bb-a5b1-4bd7-932e-a752adcf415a)
![3](https://github.com/FCL-Team/FoldCraftLauncher/assets/95129675/d61c1f6e-cede-4454-9fdc-d5c19b5a5750)

**Comment by Llerey** [comment]
In general, for some mods and tasks, giving the launcher access to Termux would be a great idea.

**Comment by ShirosakiMio** [comment]
[#](https://github.com/FCL-Team/FoldCraftLauncher/commit/7bee3a8ef3671ae432296ee3c47b0fe63a4f1716)

**Comment by Llerey** [comment]
> [#](https://github.com/FCL-Team/FoldCraftLauncher/commit/7bee3a8ef3671ae432296ee3c47b0fe63a4f1716)

I tried using the plugin 
![Screenshot_2024-06-20-21-37-37-819_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/95129675/33df43ae-5aa0-4d80-81dd-1442e53ddeb0)
![Screenshot_2024-06-20-21-40-00-465_com miui securitycenter](https://github.com/FCL-Team/FoldCraftLauncher/assets/95129675/eb488f1f-4ddf-43a3-86cb-4ae30701bbd6)
![Screenshot_2024-06-20-21-40-05-588_com miui securitycenter](https://github.com/FCL-Team/FoldCraftLauncher/assets/95129675/0259cad1-2396-4989-bc9d-f81bbdb3713e)
I installed the plugin, but it still doesn’t work, as far as I understand it should not have been used as a separate apk application, but as an .jar file in the plugins directory
Here is the link to the plugin I used https://github.com/PojavLauncherTeam/FFmpegPlugin

**Comment by Llerey** [comment]
![Screenshot_2024-06-20-21-54-41-197_me zhanghai android files](https://github.com/FCL-Team/FoldCraftLauncher/assets/95129675/27e28271-9bf9-4e28-bb63-f68923ccd616)

**Comment by ShirosakiMio** [comment]
can't run on 1.17+

**Comment by Llerey** [comment]
> can't run on 1.17+

How can this be fixed hypothetically?

**Comment by ShirosakiMio** [comment]
![image](https://github.com/FCL-Team/FoldCraftLauncher/assets/19233890/516b9dd0-6949-470c-9587-649af8f01667)
$PATH&$LD_LIBRARY_PATH is not work on 1.17+

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/11172790720
