### ISSUE TITLE
Support for 32 bit 

### ISSUE THREAD

**Issue by LdragoLegendOP** [FCL-Team/FoldCraftLauncher#41]
### Description

![Screenshot_2023-07-29-18-30-56-729_com google android packageinstaller](https://github.com/FCL-Team/FoldCraftLauncher/assets/138747962/261f6bb1-a45a-4fc8-9a79-9eb650847319)

### Why

My mobile is 32 bit and other people I think mobile 32 bit so pls add this feature

**Comment by PedrixzZ** [comment]
fold craft launcher has 32-bit support

**Comment by Tungstend** [comment]
It should support 32bit, but it doesn't support old Android versions, only Android 8+, if u are using an old device, I strongly recommend you to use pojavlauncher.
