### ISSUE TITLE
支持cleanroommc

### ISSUE THREAD

**Issue by ct-yx** [FCL-Team/FoldCraftLauncher#415]
### Description

支持cleanroommc的安装（一键安装整合包和加载器）

### Why

cleanroommc是新的1.12.2模组加载器，比forge更加高效，有整合包开始跟新cleanroommc版本

**Comment by ShirosakiMio** [comment]
自己用jar安装器解决

**Comment by ct-yx** [comment]
谢谢帮助



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月24日(周一) 晚上8:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [FCL-Team/FoldCraftLauncher] 支持cleanroommc (Issue #415)




 
自己用jar安装器解决
