### ISSUE TITLE
模组/整合包/世界/资源包的游戏版本选项最高版本过低

### ISSUE THREAD

**Issue by REYXTE** [FCL-Team/FoldCraftLauncher#419]
### Launcher Version

1.1.7

### Device Information

这好像没有意义

### Problem Description

![Screenshot_2024_0626_125925_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/139873242/8644c801-3665-429f-b8ed-29d483cd1169)
![Screenshot_2024_0626_130130_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/139873242/93e1beab-9c0d-47da-9f35-cfdeb23adf7b)

### Java

Java21

### Renderer

holy

### Game Version

?

### Modifications Made to the Game

No

**Comment by ShirosakiMio** [comment]
修了https://github.com/FCL-Team/FoldCraftLauncher/commit/bfe8743cafd8999c1145a9a840ba06c8dd463ded
