### ISSUE TITLE
无法分享布局

### ISSUE THREAD

**Issue by DSY-xiaoluo** [FCL-Team/FoldCraftLauncher#421]
### Launcher Version

1.1.7

### Device Information

VIVO X23 ANDROID9 ARM64

### Problem Description

![export1719411355217](https://github.com/FCL-Team/FoldCraftLauncher/assets/89125608/8255d154-6e7d-4ee8-af7f-495937871efd)
如图

**Comment by ShirosakiMio** [comment]
用这个https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/9688258570
