### ISSUE TITLE
Immersive Portals crashes Forge 1.18.2

### ISSUE THREAD

**Issue by U53R-96** [FCL-Team/FoldCraftLauncher#425]
### Launcher Version

1.1.7

### Device Information

Acer Spin 311 (Chromebook)

### Problem Description

Immersive Portals crashes (progressbar fully loads), briefly shows text saying "Saving world", and the crashes with error code -1.
![Screenshot 2024-06-27 7 22 20 PM](https://github.com/FCL-Team/FoldCraftLauncher/assets/163361877/5b005ce5-d6ad-4054-b00f-3f65827b1a1d)

### Java

Java 17

### Renderer

Holy-G4LES

### Game Version

1.18.2

### Modifications Made to the Game

Forge, Immersive Portals, downloaded from curseforge website (Problem), Create Mod.

### Game Crash Report

[latest_game.log](https://github.com/user-attachments/files/16023699/latest_game.log)

Sorry for uploading the log file itself (There was an error creating your Issue: body is too long (maximum is 65536 characters).

**Comment by ShirosakiMio** [comment]
Immersive Portals is not supported.
