### ISSUE TITLE
加载模组报错

### ISSUE THREAD

**Issue by 6833321** [FCL-Team/FoldCraftLauncher#428]
### Launcher Version

1.1.7

### Device Information

HarmonyOS 2.0.1

### Problem Description

我就加了模组钠，结果无法进入世界。

### Java

JAVA21

### Game Version

1.21

### Modifications Made to the Game

Fabric

**Comment by ShirosakiMio** [comment]
![QQ截图20240629192607](https://github.com/FCL-Team/FoldCraftLauncher/assets/19233890/763a64f0-258f-4090-8613-3598234de37f)
钠不支持安卓设备使用
