### ISSUE TITLE
This is any solution

### ISSUE THREAD

**Issue by LdragoLegendOP** [FCL-Team/FoldCraftLauncher#43]
### Description

I'm download foldcraftLauncher but test alpha 3 and I'm uninstall this launcher and download available version in GitHub but still this error 
![Screenshot_2023-07-30-09-12-38-657_com google android packageinstaller](https://github.com/FCL-Team/FoldCraftLauncher/assets/138747962/542c8459-ce8f-4cd3-8261-d401b07a250d)

### Why

Any solution?

**Comment by Tet100** [comment]
You need to go into android, then go to the date and give access, then look for the file "com.tungsten.fcl" it must be removed.
After you go back to where all the files are and delete "FCL"
And then try to install the launcher again

**Comment by LdragoLegendOP** [comment]
I'm test but not working and my Android version 10
