### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by ThundtrBY** [FCL-Team/FoldCraftLauncher#430]
### Launcher Version

1.1.7.1

### Device Information

Redmi K50

### Problem Description

Game crash

### Java

Java8

### Renderer

Holy-gl4es

### Game Version

1.7.10

### Modifications Made to the Game

Forge

### Game Crash Report

https://mclo.gs/803c7Yi

### Launcher Crash Report

https://mclo.gs/803c7Yi

### Launcher Log File

https://mclo.gs/803c7Yi

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/9760191983
