### ISSUE TITLE
使用vulkan zink莫名其妙的崩溃

### ISSUE THREAD

**Issue by ct-yx** [FCL-Team/FoldCraftLauncher#436]
### Launcher Version

今天的最新版

### Device Information

Redmi Turbo 3   8sGEN3 arm Xiaomi HyperoS

### Problem Description

在使用vulkan zink时莫名其妙崩溃

### Java

17

### Renderer

Vulkan Zink 

### Game Version

1.20.1

### Modifications Made to the Game

embeddium

### Game Crash Report

[22:08:11] [main/INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.10-internal by N/A; OS Linux arch aarch64 version Android-14
[22:08:11] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/lwjgl/fcl_hook.c:70
Registered forkAndExec
[22:08:11] [main/INFO]: Trying GL version 4.6
AdrenoSupp: Loaded Turnip, loader address: 0xfa6bc7a56ce9d7fb

### Launcher Crash Report

[latest_game.log](https://github.com/user-attachments/files/16110746/latest_game.log)

### Launcher Log File

[fcl.log](https://github.com/user-attachments/files/16110749/fcl.log)

**Comment by Vera-Firefly** [comment]
Turnip似乎识别不到你的设备?
能否提供你的Vulkan设备ID?
![Screenshot_2024-07-06-10-40-04-869_com finalwire aida64](https://github.com/FCL-Team/FoldCraftLauncher/assets/87926662/752a0965-06ca-4dd4-88f4-697dc91bf171)
