### ISSUE TITLE
使用zink驱动莫名其妙的屏幕屏闪

### ISSUE THREAD

**Issue by ct-yx** [FCL-Team/FoldCraftLauncher#439]

**Comment by ct-yx** [comment]
这是最新版本的，今早起来刚刚更新

**Comment by Vera-Firefly** [comment]
能否提供一下日志以及运行录屏?

**Comment by ct-yx** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/assets/122712983/73eb9438-ae82-460a-86df-c34b0f2a76b0

https://github.com/FCL-Team/FoldCraftLauncher/assets/122712983/60359daf-8b2f-44fe-8f3f-8ec54ecb0998

![Screenshot_2024-07-06-10-28-28-019_com.tungsten.fcl.jpg](https://github.com/FCL-Team/FoldCraftLauncher/assets/122712983/f68a4ca3-f144-4dbf-9280-7623fd345bd0)

无论是使用fabric端还是forge端都会出现频闪。

**Comment by ct-yx** [comment]
全都是最新版本
都是使用vulkan zink

**Comment by Vera-Firefly** [comment]
> 全都是最新版本 都是使用vulkan zink

静静等待修复
这次的Turnip驱动对A735的支持是我搓的,并非Mesa那边专门做驱动的哥们做的
个人技术有限,但我会尝试着去修复

**Comment by ct-yx** [comment]
> > 全都是最新版本 都是使用vulkan zink
> 
> 静静等待修复
> 这次的Turnip驱动对A735的支持是我搓的,并非Mesa那边专门做驱动的哥们做的
> 个人技术有限,但我会尝试着去修复

谢谢

**Comment by ct-yx** [comment]
> > 全都是最新版本 都是使用vulkan zink
> 
> 静静等待修复
> 这次的Turnip驱动对A735的支持是我搓的,并非Mesa那边专门做驱动的哥们做的
> 个人技术有限,但我会尝试着去修复

所以说是我a735的问题啊
当时买这玩意，本来以为高通兼容性好，想着模拟一些东西……

**Comment by Vera-Firefly** [comment]
> > > 全都是最新版本 都是使用vulkan zink
> > 
> > 
> > 静静等待修复
> > 这次的Turnip驱动对A735的支持是我搓的,并非Mesa那边专门做驱动的哥们做的
> > 个人技术有限,但我会尝试着去修复
> 
> 所以说是我a735的问题啊 当时买这玩意，本来以为高通兼容性好，想着模拟一些东西……

没驱动,和兼容无关

**Comment by ct-yx** [comment]
> > > > 全都是最新版本 都是使用vulkan zink
> > > 
> > > 
> > > 静静等待修复
> > > 这次的Turnip驱动对A735的支持是我搓的,并非Mesa那边专门做驱动的哥们做的
> > > 个人技术有限,但我会尝试着去修复
> > 
> > 所以说是我a735的问题啊 当时买这玩意，本来以为高通兼容性好，想着模拟一些东西……
> 
> 没驱动,和兼容无关

那个vulkan的id还需要吗？

**Comment by ct-yx** [comment]
> > > > 全都是最新版本 都是使用vulkan zink
> > > 
> > > 
> > > 静静等待修复
> > > 这次的Turnip驱动对A735的支持是我搓的,并非Mesa那边专门做驱动的哥们做的
> > > 个人技术有限,但我会尝试着去修复
> > 
> > 所以说是我a735的问题啊 当时买这玩意，本来以为高通兼容性好，想着模拟一些东西……
> 
> 没驱动,和兼容无关

所以现在无论使用哪个启动器都会出现相同的情况吧

**Comment by Vera-Firefly** [comment]
> > > > > 全都是最新版本 都是使用vulkan zink
> > > > 
> > > > 
> > > > 静静等待修复
> > > > 这次的Turnip驱动对A735的支持是我搓的,并非Mesa那边专门做驱动的哥们做的
> > > > 个人技术有限,但我会尝试着去修复
> > > 
> > > 
> > > 所以说是我a735的问题啊 当时买这玩意，本来以为高通兼容性好，想着模拟一些东西……
> > 
> > 
> > 没驱动,和兼容无关
> 
> 所以现在无论使用哪个启动器都会出现相同的情况吧

尝试这个构建:https://github.com/Vera-Firefly/FoldCraftLauncher/actions/runs/9819611784

**Comment by Vera-Firefly** [comment]
在Mesa24.1.x是不会出现这个情况的,所提供的Turnip驱动版本是Mesa24.1.2,所以对于相对应的版本不会出现奇怪的问题(应该)
FCL由于要对所有设备兼容,所以Mesa24.1.x暂时不会被合并

**Comment by Vera-Firefly** [comment]
目前A735的那个驱动问题特别大(个人技术有限,所以问题有点多,毕竟我不是专业的,能用就行了),运行光影会有严重的渲染错误,不开光影到没什么问题

**Comment by Vera-Firefly** [comment]
你要用的话debug和release包自己选,内容都一样的

**Comment by ct-yx** [comment]
> 目前A735的那个驱动问题特别大(个人技术有限,所以问题有点多,毕竟我不是专业的,能用就行了),运行光影会有严重的渲染错误,不开光影到没什么问题

用vulkan zink驱动，无论是forge还是fabric都会出现频闪。

**Comment by ct-yx** [comment]
> 目前A735的那个驱动问题特别大(个人技术有限,所以问题有点多,毕竟我不是专业的,能用就行了),运行光影会有严重的渲染错误,不开光影到没什么问题

安装了铷/钠

**Comment by ct-yx** [comment]
> > 目前A735的那个驱动问题特别大(个人技术有限,所以问题有点多,毕竟我不是专业的,能用就行了),运行光影会有严重的渲染错误,不开光影到没什么问题
> 
> 安装了铷/钠

又测试了一下，用原版也会出现问题， Angle 可以正确启动

**Comment by Vera-Firefly** [comment]
说了,你直接用链接里面的那个,没有事的

**Comment by Vera-Firefly** [comment]
这个issues可以关掉了,与启动器无关,没必要开着

**Comment by Vera-Firefly** [comment]
![Screenshot_2024-07-06-21-38-52-378_com miui mediaviewer](https://github.com/FCL-Team/FoldCraftLauncher/assets/87926662/e9edc251-0d66-4737-9713-8ca52a68e155)

**Comment by ct-yx** [comment]
> 说了,你直接用链接里面的那个,没有事的

在直接使用，压缩包中的安装包安装更新后，启动游戏仍会频闪。。。

**Comment by ct-yx** [comment]
> > 说了,你直接用链接里面的那个,没有事的
> 
> 在直接使用，压缩包中的安装包安装更新后，启动游戏仍会频闪。。。

https://github.com/FCL-Team/FoldCraftLauncher/assets/122712983/9e6c50df-43ee-4f02-9886-5b00acdca3f2

**Comment by Vera-Firefly** [comment]
那个是FML动画…
会闪很正常(Android启动器不兼容,1.20.x~1.21.x是意外)
进去之后就不会了

**Comment by ct-yx** [comment]
> 那个是FML动画…
> 会闪很正常(Android启动器不兼容,1.20.x~1.21.x是意外)
> 进去之后就不会了

在进去之后界面被一层红覆盖

**Comment by Vera-Firefly** [comment]
> > 那个是FML动画…
> > 会闪很正常(Android启动器不兼容,1.20.x~1.21.x是意外)
> > 进去之后就不会了
> 
> 在进去之后界面被一层红覆盖

检查你是否把
```
使用系统vulkan驱动
```
打开了,如果打开了就关闭,那个东西不是给你用的

**Comment by ct-yx** [comment]
> > > 那个是FML动画…
> > > 会闪很正常(Android启动器不兼容,1.20.x~1.21.x是意外)
> > > 进去之后就不会了
> > 
> > 在进去之后界面被一层红覆盖
> 
> 检查你是否把
> ```
> 使用系统vulkan驱动
> ```
> 打开了,如果打开了就关闭,那个东西不是给你用的

在关闭了该选项之后，频闪变得更离谱了
https://github.com/FCL-Team/FoldCraftLauncher/assets/122712983/f3fd9a11-60d9-4192-97ea-9f0eae83de33

**Comment by ct-yx** [comment]
> ![Screenshot_2024-07-06-21-38-52-378_com miui mediaviewer](https://github.com/FCL-Team/FoldCraftLauncher/assets/87926662/e9edc251-0d66-4737-9713-8ca52a68e155)
> 

关于此测试
我在1.16.5版本测试时问题仍然存在，只是闪的比较慢
选择vulkan zink的原因是铷/钠只支持此渲染器
别的渲染器无法进存档，且如果不加任何优化类mod游戏的可玩性将极低

**Comment by ct-yx** [comment]
> > ![Screenshot_2024-07-06-21-38-52-378_com miui mediaviewer](https://github.com/FCL-Team/FoldCraftLauncher/assets/87926662/e9edc251-0d66-4737-9713-8ca52a68e155)
> > 
> 
> 关于此测试
> 我在1.16.5版本测试时问题仍然存在，只是闪的比较慢
> 选择vulkan zink的原因是铷/钠只支持此渲染器
> 别的渲染器无法进存档，且如果不加任何优化类mod游戏的可玩性将极低

使用optfine倒是没有任何问题
但由于众所周知的原因，opt在高版本几乎不可用。。。

**Comment by Vera-Firefly** [comment]
说了是驱动的问题,而且你开着喝录屏在那个界面不闪你闪谁?
你干脆别用了,要么等Mesa那边专门做Turnip驱动的老哥做,爱用不用

**Comment by ct-yx** [comment]
> 说了是驱动的问题,而且你开着个录屏在那个界面不闪你闪谁?
> 你干脆别用了,要么等Mesa那边专门做Turnip驱动的老哥做,爱用不用

这也是驱动的问题吗[Screenshot_2024-07-08-09-13-58-582_com.tungsten.fcl.jpg](https://github.com/FCL-Team/FoldCraftLauncher/assets/122712983/f434cbb3-ac54-4458-a7f8-a4f311aad296)

![Screenshot_2024-07-08-09-13-02-523_com.tungsten.fcl.jpg](https://github.com/FCL-Team/FoldCraftLauncher/assets/122712983/c9848896-2ade-4554-8c4e-5013213358bc)

![Screenshot_2024-07-08-09-12-36-701_com.tungsten.fcl.jpg](https://github.com/FCL-Team/FoldCraftLauncher/assets/122712983/b039cba7-d605-4dba-936b-3511ed37a9fc)

**Comment by Vera-Firefly** [comment]
> > 说了是驱动的问题,而且你开着个录屏在那个界面不闪你闪谁?
> > 你干脆别用了,要么等Mesa那边专门做Turnip驱动的老哥做,爱用不用
> 
> 这也是驱动的问题吗[Screenshot_2024-07-08-09-13-58-582_com.tungsten.fcl.jpg](https://github.com/FCL-Team/FoldCraftLauncher/assets/122712983/f434cbb3-ac54-4458-a7f8-a4f311aad296)
> 
> ![Screenshot_2024-07-08-09-13-02-523_com.tungsten.fcl.jpg](https://private-user-images.githubusercontent.com/122712983/346839262-c9848896-2ade-4554-8c4e-5013213358bc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTg5MzIsIm5iZiI6MTcyMDUxODYzMiwicGF0aCI6Ii8xMjI3MTI5ODMvMzQ2ODM5MjYyLWM5ODQ4ODk2LTJhZGUtNDU1NC04YzRlLTUwMTMyMTMzNThiYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwOTUwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGE1YjE5MDk3MDA2OTM4NzI5YjU1OTFjMzllMGVlMDE2OTdjMmQ3ZGVlOTVlN2UxNmIyMDRkYjNhYzM1NjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pbWOQfKtwjZ6B-DMTD9_hREAJhSkmzjSL8tiRSqLcCc)
> 
> ![Screenshot_2024-07-08-09-12-36-701_com.tungsten.fcl.jpg](https://private-user-images.githubusercontent.com/122712983/346839270-b039cba7-d605-4dba-936b-3511ed37a9fc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTg5MzIsIm5iZiI6MTcyMDUxODYzMiwicGF0aCI6Ii8xMjI3MTI5ODMvMzQ2ODM5MjcwLWIwMzljYmE3LWQ2MDUtNGRiYS05MzZiLTM1MTFlZDM3YTlmYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwOTUwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGVhYTlmZDkzZmQ3ZjQ1YTA0ODE4MzZlZDlhMmNhNjdlOWJmMTQ0Yjg3MmUyZTdhMmJhMjAwNGIzYWEwM2Y4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0ErIR3cFxgm5Ct2urOQs-GpqDuWw_OXYlElqNgvBolo)

这是渲染器原因
