### ISSUE TITLE
error running sodium mod while joining world

### ISSUE THREAD

**Issue by Sang5231** [FCL-Team/FoldCraftLauncher#44]
### Launcher Version

1.0.2

### Device Information

Galaxy Tab A(8.0, 2019)

### Problem Description

there was a problem when i used mod sodium, i don't know how to describe it, all i can do is take a picture so the developer can fix it
![20230730_103529_mfnr](https://github.com/FCL-Team/FoldCraftLauncher/assets/99467894/0a8a91ef-68e7-4b3d-91d2-531c982576f0)
it even has 0-1 fps when running the game

### Java

Java 8

### Renderer

Holy-GL4ES

### Game Version

1.16.5

### Modifications Made to the Game

1.16.5 Fabric

**Comment by Sang5231** [comment]
I use Google Translate, so it may be wrong =))

**Comment by Sang5231** [comment]
i believe this bug can occur in multiple versions and not fixed at 1.16.5. it can happen at 1.17, 1.18, 1.19, 1.20 but i don't have much time to try them one by one

**Comment by Sang5231** [comment]
I believe this error can happen in many versions, it can happen in 1.17, 1.18, 1.19, 1.20 but I don't have much time to try them one by one.

**Comment by Tet100** [comment]
You can try downloading add-ons for it. 
Or download optifabrik

**Comment by Sang5231** [comment]
I will try optifabic and see if there are any errors

**Comment by didntpenguin** [comment]
1.16.5 need sodium patcher

**Comment by Tet100** [comment]
If optimization is important to you, download version 1.16.5 of Optifine, or replace the sodium with another optimization mod
