### ISSUE TITLE
lwjgl不兼容钠

### ISSUE THREAD

**Issue by su-yihong** [FCL-Team/FoldCraftLauncher#440]
### Launcher Version

1.1.7.2

### Device Information

huawei nova7 android 10

### Problem Description

lwjgl不兼容钠

### Java

java17

### Renderer

angle

### Game Version

1.20.1

### Modifications Made to the Game

Fabric,sodium

### Game Crash Report

==================== Basic Information ====================
FCL Version: 1.1.7.2
Architecture: arm64
Android SDK: 29
Java Version: 17
Renderer: ANGLE
Summarize: Application error, unable to launch, exit code = 1
==================== Basic Information ====================

invoke redirectStdio
invoke setLogPipeReady
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_loader.c:142
Log pipe ready.
invoke setFCLNativeWindow
invoke setEventPipe
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_bridge.c:60
setFCLNativeWindow : 0x6eaa901010, size : 2400x1080
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_event.c:193
Succeeded to set event pipe
==================== Start Minecraft ====================
Device: HWCDY
Architecture: arm64
CPU:kirin820
Android SDK: 29
==================== Env Map ====================
Env: PATH=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/bin:/sbin:/system/sbin:/product/bin:/apex/com.android.runtime/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Env: LIBEGL_NAME=libEGL_angle.so
Env: FCL_NATIVEDIR=/data/app/com.tungsten.fcl-O9-OnpKPNouQzvypoqEzBg==/lib/arm64
Env: JAVA_HOME=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17
Env: LIBGL_NAME=libtinywrapper.so
Env: LIBGL_STRING=ANGLE
Env: VULKAN_DRIVER_SYSTEM=1
Env: HOME=/storage/emulated/0/FCL/log
Env: TMPDIR=/data/user/0/com.tungsten.fcl/cache
Env: LIBGL_ES=3
==================== Env Map ====================
Working directory: /storage/emulated/0/FCL/.minecraft
==================== Minecraft Arguments ====================
Java argument: /data/user/0/com.tungsten.fcl/app_runtime/java/jre17/bin/java
Java argument: -Djava.awt.headless=false
Java argument: -Dcacio.managed.screensize=2400x1080
Java argument: -Dcacio.font.fontmanager=sun.awt.X11FontManager
Java argument: -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler
Java argument: -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel
Java argument: -Dawt.toolkit=com.github.caciocavallosilano.cacio.ctc.CTCToolkit
Java argument: -Djava.awt.graphicsenv=com.github.caciocavallosilano.cacio.ctc.CTCGraphicsEnvironment
Java argument: -Djava.system.class.loader=com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader
Java argument: --add-exports=java.desktop/java.awt=ALL-UNNAMED
Java argument: --add-exports=java.desktop/java.awt.peer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.java2d=ALL-UNNAMED
Java argument: --add-exports=java.desktop/java.awt.dnd.peer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.event=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.datatransfer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.font=ALL-UNNAMED
Java argument: --add-exports=java.base/sun.security.action=ALL-UNNAMED
Java argument: --add-opens=java.base/java.util=ALL-UNNAMED
Java argument: --add-opens=java.desktop/java.awt=ALL-UNNAMED
Java argument: --add-opens=java.desktop/sun.font=ALL-UNNAMED
Java argument: --add-opens=java.desktop/sun.java2d=ALL-UNNAMED
Java argument: --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
Java argument: --add-opens=java.base/java.net=ALL-UNNAMED
Java argument: -Xbootclasspath/a:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
Java argument: -Xmx2048m
Java argument: -Dfile.encoding=UTF-8
Java argument: -Dsun.stdout.encoding=UTF-8
Java argument: -Dsun.stderr.encoding=UTF-8
Java argument: -Djava.rmi.server.useCodebaseOnly=true
Java argument: -Dcom.sun.jndi.rmi.object.trustURLCodebase=false
Java argument: -Dcom.sun.jndi.cosnaming.object.trustURLCodebase=false
Java argument: -Dlog4j2.formatMsgNoLookups=true
Java argument: -Dlog4j.configurationFile=/storage/emulated/0/FCL/.minecraft/versions/1.20.1_Fabric/log4j2.xml
Java argument: -Dminecraft.client.jar=/storage/emulated/0/FCL/.minecraft/versions/1.20.1_Fabric/1.20.1_Fabric.jar
Java argument: -Dfml.ignoreInvalidMinecraftCertificates=true
Java argument: -Dfml.ignorePatchDiscrepancies=true
Java argument: -Dext.net.resolvPath=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/resolv.conf
Java argument: -Djava.io.tmpdir=/data/user/0/com.tungsten.fcl/cache/fclauncher
Java argument: -Dos.name=Linux
Java argument: -Dos.version=Android-10
Java argument: -Dorg.lwjgl.opengl.libname=libtinywrapper.so
Java argument: -Dfml.earlyprogresswindow=false
Java argument: -Dwindow.width=2400
Java argument: -Dwindow.height=1080
Java argument: -Duser.home=/storage/emulated/0/FCL/.minecraft
Java argument: -Duser.language=zh
Java argument: -Duser.timezone=Asia/Shanghai
Java argument: -Djna.boot.library.path=/data/app/com.tungsten.fcl-O9-OnpKPNouQzvypoqEzBg==/lib/arm64
Java argument: -Dorg.lwjgl.vulkan.libname=libvulkan.so
Java argument: -Dfcl.injector=4:net.minecraft.class_310:method_1551:field_1765:method_17783
Java argument: -Djava.library.path=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib:/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib/jli:/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib/server:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/com.tungsten.fcl-O9-OnpKPNouQzvypoqEzBg==/lib/arm64
Java argument: -Dio.netty.native.workdir=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib:/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib/jli:/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib/server:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/com.tungsten.fcl-O9-OnpKPNouQzvypoqEzBg==/lib/arm64
Java argument: -Dminecraft.launcher.brand=Fold Craft Launcher
Java argument: -Dminecraft.launcher.version=1.1.7.2
Java argument: -cp
Java argument: /data/user/0/com.tungsten.fcl/app_runtime/lwjgl/lwjgl.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/fabricmc/intermediary/1.20.1/intermediary-1.20.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/fabricmc/fabric-loader/0.15.11/fabric-loader-0.15.11.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/github/oshi/oshi-core/6.3.0/oshi-core-6.3.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar:/data/user/0/com.tungsten.fcl/files/plugins/MioLaunchWrapper.jar:/storage/emulated/0/FCL/.minecraft/versions/1.20.1_Fabric/1.20.1_Fabric.jar
Java argument: --add-exports
Java argument: net.fabricmc.loader.impl.launch.knot/net.fabricmc.loader.impl.launch.knot=ALL-UNNAMED
MainClass: mio.Wrapper
MainClass: net.fabricmc.loader.impl.launch.knot.KnotClient
Minecraft argument: --username
Minecraft argument: suyihong
Minecraft argument: --version
Minecraft argument: 1.20.1_Fabric
Minecraft argument: --gameDir
Minecraft argument: /storage/emulated/0/FCL/.minecraft
Minecraft argument: --assetsDir
Minecraft argument: /storage/emulated/0/FCL/.minecraft/assets
Minecraft argument: --assetIndex
Minecraft argument: 5
Minecraft argument: --uuid
Minecraft argument: 74bb15b3ed2f43e8bbf9e0a308aa21e4
Minecraft argument: --accessToken
Minecraft argument: ***
Minecraft argument: --clientId
Minecraft argument: ${clientid}
Minecraft argument: --xuid
Minecraft argument: ${auth_xuid}
Minecraft argument: --userType
Minecraft argument: msa
Minecraft argument: --versionType
Minecraft argument: Fold Craft Launcher
Minecraft argument: --width
Minecraft argument: 2400
Minecraft argument: --height
Minecraft argument: 1080
Hook exit success
[13:40:48] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.11
[13:40:48] [main/INFO]: Loading 65 mods:
	- chunksfadein 1.0.6-1.20.1
	   |-- com_moandjiezana_toml_toml4j 0.7.2
	   \-- crowdin-translate 1.4+1.19.3
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 17
	- minecraft 1.20.1
	- reeses-sodium-options 1.7.2+mc1.20.1-build.101
	- sodium 0.5.11+mc1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   \-- fabric-resource-loader-v0 0.11.10+1802ada577
	- sodium-extra 0.5.4+mc1.20.1-build.115
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- sspb 3.3.0
[13:40:49] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/FCL/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[13:40:49] [main/INFO]: Compatibility level set to JAVA_17
[13:40:49] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 0 override(s) found
[13:40:49] [main/INFO]: Loaded configuration file for Sodium Extra: 34 options available, 0 override(s) found
[13:40:51] [main/INFO]: [SSPB] Indium not detected. Option to toggle vanilla path block lighting is disabled
[13:40:51] [main/WARN]: Error loading class: link/infra/indium/renderer/aocalc/AoCalculator (java.lang.ClassNotFoundException: link/infra/indium/renderer/aocalc/AoCalculator)
[13:40:51] [main/ERROR]: The game failed to start because the currently active LWJGL version is not compatible.

Installed version: 3.3.3-snapshot
Required version: 3.3.1

You must change the LWJGL version in your launcher to continue. This is usually controlled by the settings for a profile or instance in your launcher.

For more information, please see: https://github.com/CaffeineMC/sodium-fabric/wiki/LWJGL-Compatibility
OpenJDK exited with code : 1

**Comment by ShirosakiMio** [comment]
https://github.com/ConfectionaryQwQ/sodium-fabric-con-edit/tree/1.20.1-Holy

**Comment by Haoyi71224** [comment]
- 模组 'Indium' (indium) 1.0.36+mc1.20.1 需要 模组 'Sodium' (sodium) 的 从 0.5.11（含）到 0.6-（不含）的任意版本，但已经安装了的版本 0.5.8+mc1.20.1 不对！
