### ISSUE TITLE
Fps limit

### ISSUE THREAD

**Issue by Insane565** [FCL-Team/FoldCraftLauncher#442]
### Launcher Version

1.1.7.2

### Device Information

Redmi 12 5g

### Problem Description

In minecraft every version I set fps unlimited in setting but my fps can't increase than 90 in gold craft launcher I get above fps in other launcher

### Game Version

1.21

### Modifications Made to the Game

Fabric

**Comment by WesleyVanNeck** [comment]
Disable vsync and set fps you wand in Minecraft
