### ISSUE TITLE
Sodium doesn't work

### ISSUE THREAD

**Issue by Insane565** [FCL-Team/FoldCraftLauncher#445]
### Launcher Version

1.1.7.2

### Device Information

Redmi 12 5g

### Problem Description

Sodium doesn't work in 1.21 

### Renderer

Holy-GL4ES

### Game Version

1.21

### Modifications Made to the Game

Fabric

**Comment by PocoX3Obed** [comment]
Use sodium with VirGlRenderer, should render chunks normally
