### ISSUE TITLE
Reducing resolution results in inability to touch

### ISSUE THREAD

**Issue by Aisaka-Yume** [FCL-Team/FoldCraftLauncher#45]
### Launcher Version

1.0.2

### Device Information

Oneplus Ace2 ; Android13 ; arm64

### Problem Description

Reducing the resolution in the settings can cause mouse touch to malfunction, such as 80% resolution and 50% resolution (the above statements are translated using translation software)

### Game Version

1.20.1

**Comment by Aisaka-Yume** [comment]
Supplement: JAVA version is JAVA17, and the publisher version is Holy GL4ES

**Comment by Tungstend** [comment]
already fixed
