### ISSUE TITLE
既不能进入游戏，又无崩溃报告

### ISSUE THREAD

**Issue by sakarwei** [FCL-Team/FoldCraftLauncher#453]
### Launcher Version

1.1.7.2

### Device Information

Huawei Mate30 armeabi-v7a

### Problem Description

Uploading SVID_20240712_185356_1.mp4…

下载、安装顺利，点击启动游戏后回退到主界面，无崩溃报告，导出日志无内容（大小0B，空白）

### Java

自动选择和JRE21

### Renderer

Holy GL4ES(OpenGL 2.1)

### Game Version

1.20.6、1.21 等

### Modifications Made to the Game

无

**Comment by sakarwei** [comment]
https://github.com/user-attachments/assets/86be51d7-59c4-481a-8926-e4e7eebe04f3

**Comment by WesleyVanNeck** [comment]
no log

**Comment by sakarwei** [comment]
[log.zip](https://github.com/user-attachments/files/16193040/log.zip)

**Comment by sakarwei** [comment]
> no log

I found and uploaded all the files in FCL/log
https://github.com/user-attachments/files/16193040/log.zip

**Comment by sakarwei** [comment]
[Screenshots.zip](https://github.com/user-attachments/files/16193756/Screenshots.zip)

The problem I encountered while collecting logs

**Comment by ct-yx** [comment]
我也遇见了相同的情况， Log文件是启动器的fcl.log。

**Comment by ct-yx** [comment]
[fcl.log](https://github.com/user-attachments/files/16200866/fcl.log)
[latest_game.log](https://github.com/user-attachments/files/16200867/latest_game.log)
反正不知道为什么，突然就崩溃了
@ShirosakiMio
