### ISSUE TITLE
Cannot login to Microsoft

### ISSUE THREAD

**Issue by PocoX3Obed** [FCL-Team/FoldCraftLauncher#456]
### Launcher Version

Latest

### Device Information

Samsung S21 Android 14

### Problem Description

![Screenshot_20240713_225855_Fold Craft Launcher](https://github.com/user-attachments/assets/7e386525-d156-410a-8fb9-7a1e59f8888c)

**Comment by Llerey** [comment]
Это баг перевода, используй английский язык в лаунчере если играешь на лицензии

**Comment by Llerey** [comment]
Без понятия как оно связано, но похоже я что-то не то тронул в файле перевода, уже некоторое время ищу в чем проблема:/

**Comment by PocoX3Obed** [comment]
> Без понятия как оно связано, но похоже я что-то не то тронул в файле перевода, уже некоторое время ищу в чем проблема:/

Yo, thanks for helping, that actually worked.
