### ISSUE TITLE
建议加一个自动选择opengl版本的功能

### ISSUE THREAD

**Issue by githubusera2034324** [FCL-Team/FoldCraftLauncher#458]
### Description

玩惯了1.8.9版本，需要把opengl版本调到2.1，然后每次想玩1.20.6版本时需要手动调节opengl版本到4.6，不然在加载存档时游戏会崩溃，试了好几次，崩溃日志都显示是模组出问题，代码缺失，于是把所有模组都删除了也不行，删除1.20.1重装也不行，然后发现是opengl版本的问题，所以来提个意见

### Why

自动选择opengl版本对不懂得opengl的新手来说比较友好

**Comment by githubusera2034324** [comment]
[fcl.log](https://github.com/user-attachments/files/16227641/fcl.log)

**Comment by DSY-xiaoluo** [comment]
有没有可能有一个东西，叫做“启用游戏特定版本设置”，在扳手图标里

**Comment by githubusera2034324** [comment]
> 可你发的日志文件跟opengl也没关系呀

这个是正常的启动日志，我去把bug复现一次才可以调出日志
