### ISSUE TITLE
i cant use optifine and forge at the same time

### ISSUE THREAD

**Issue by lazarrz** [FCL-Team/FoldCraftLauncher#46]
### Launcher Version

1.0.2

### Device Information

Redmi Note 9 Pro, Android 12, arm64-v8a

### Problem Description

when i join a world with forge and optifine it loads to 100 then it says saving then it crashes

### Java

Java 17

### Renderer

Holygl4es

### Game Version

1.20.1

### Modifications Made to the Game

Optifine HD_U_l5 Forge 47.1.43

### Launcher Log File

https://drive.google.com/file/d/1-I6Sdz9StJPMG8L6MFqrtS6je_HPequM/view?usp=drivesdk

**Comment by ShirosakiMio** [comment]
Wait for the Forge and Optifine update.It seems the newer version of forge remove a method which used in Optifine.
