### ISSUE TITLE
FCL与所有的瓦尔基里天空不兼容

### ISSUE THREAD

**Issue by OolongMC** [FCL-Team/FoldCraftLauncher#461]
### Launcher Version

1.1.7.2

### Device Information

荣耀V30PRO   以及   荣耀V10

### Problem Description

老问题了，从HMCL-PE到FCL，凡是加入了瓦尔基里天空mod，要么卡黑屏，要么闪退，要么进入了主界面，但是进入世界时闪退，我真的很想现瓦尔基里天空qwq

### Java

Java8、Java17、Java21

### Renderer

Holy GL4ES、VirGLRenderer

### Modifications Made to the Game

1.12.2Forge、1.18.2Fabric、1.20.1Fabric、1.20.1NeoForge（均为最新版本））

### Game Crash Report

以1.20.1NeiForge为例（进入世界时闪退）
[crash-2024-07-15_09.42.37-server.txt](https://github.com/user-attachments/files/16229403/crash-2024-07-15_09.42.37-server.txt)

### Launcher Log File

[fcl-latest5632311752445034482.log](https://github.com/user-attachments/files/16229404/fcl-latest5632311752445034482.log)

**Comment by OolongMC** [comment]
打错字了，我真的很想玩瓦尔基里天空MOD(இдஇ)

**Comment by ShirosakiMio** [comment]
这mod不支持手机使用，只能运行服务端再连进去
