### ISSUE TITLE
整合包问题

### ISSUE THREAD

**Issue by 6833321** [FCL-Team/FoldCraftLauncher#462]
有一些整合包，他有一些模组是有问题的。然后我就想把那些模组给卸掉，结果fcl贴心的帮我把那些模组安回去了

**Comment by 6833321** [comment]
而且还是不安不启动的那种

**Comment by OolongMC** [comment]
打开不检测游戏文件完整性，或者打开/storage/emulated/0/FCL/.minecraft/versions/版本名/，删除manifest.json和modpack.cfg文件

**Comment by OolongMC** [comment]
一般只有Modrinth或CurseForge托管的整合包会这样。我也遇到过

**Comment by zkitefly** [comment]
curseforge 整合包要到模组管理禁用，而不是直接删除

modrinth 整合包因为 hmcl 那边的逻辑有点问题，导致怎样都会下载模组，所以就等 hmcl 修复然后 fcl 同步
