### ISSUE TITLE
BE Gesture problem 

### ISSUE THREAD

**Issue by Firepoku** [FCL-Team/FoldCraftLauncher#463]
### Launcher Version

1.1.7.2

### Device Information

Motorola G Stylus 2023, Android 14

### Problem Description

Hey guys, from 1.20.5 to 1.21 I encountered a problem with the attack action, before 1.20.5 to attack I only had to touch the screen 1 time, now I have to hold to attack, I don't know if it is a change in controls of the app or something related (I think is something about the "BE" gesture option, but it doesn't matter if I turn that on or off the gesture still the same) 

### Java

Java 21

### Renderer

Holy-GL4ES (OpenGL 2.1)

### Game Version

1.20.5 - 1.21

**Comment by ShirosakiMio** [comment]
the "BE" gesture now is not support 1.20,.4+

**Comment by ShirosakiMio** [comment]
You can change the  "Gesture Mode" to "Fight"
