### ISSUE TITLE
终端弹不出键盘了

### ISSUE THREAD

**Issue by OolongMC** [FCL-Team/FoldCraftLauncher#469]
### Launcher Version

1.1.7.2

### Device Information

荣耀V30PRO，arm64，鸿蒙4.2

### Problem Description

从前长按启动游戏进入终端还可以打字的，现在进入终端怎么点也弹不出键盘
![Screenshot_20240720_083838_com tungsten fcl](https://github.com/user-attachments/assets/6530dc2c-22b3-40a6-ba1d-5be1b3952ea6)

### Java

Java17

**Comment by OolongMC** [comment]
不想开发终端了可以关闭终端的进入入口

**Comment by DSY-xiaoluo** [comment]
> ### Launcher Version
> 
> 1.1.7.2
> 
> ### Device Information
> 
> 荣耀V30PRO，arm64，鸿蒙4.2
> 
> ### Problem Description
> 
> 从前长按启动游戏进入终端还可以打字的，现在进入终端怎么点也弹不出键盘
> ![Screenshot_20240720_083838_com tungsten fcl](https://github.com/user-attachments/assets/6530dc2c-22b3-40a6-ba1d-5be1b3952ea6)
> 
> 
> ### Java
> 
> Java17
> 
> ### Renderer
> 
> _No response_
> 
> ### Game Version
> 
> _No response_
> 
> ### Modifications Made to the Game
> 
> _No response_
> 
> ### Game Crash Report
> 
> _No response_
> 
> ### Launcher Crash Report
> 
> _No response_
> 
> ### Launcher Log File
> 
> _No response_

点下面的横线就会弹了
