### ISSUE TITLE
Please build the installation package with a minimum API of 24

### ISSUE THREAD

**Issue by haozihhr** [FCL-Team/FoldCraftLauncher#47]
My system's sdk is 24(Android 7.x),but the apk's sdk is 26(Android 8.1),so the installation package unable install in my phone.

**Comment by LegacyGamerHD** [comment]
android 7 support wont be added

**Comment by LegacyGamerHD** [comment]
you need at least android 8.0

**Comment by haozihhr** [comment]
Why?

**Comment by Tungstend** [comment]
Some codes need sdk26 support
