### ISSUE TITLE
纤细皮肤错误

### ISSUE THREAD

**Issue by 1008611huafeiztc** [FCL-Team/FoldCraftLauncher#470]
### Launcher Version

1.1.7.2

### Device Information

Xiaomi Pad 5 Pro     android13    arm8

### Problem Description

纤细的本地皮肤
主菜单显示正常，游戏里出现黑边
![6d5eb6e78f8ea57dd7e8f4860859ab35251bcc635f12a5f1757794bca39b7d2e](https://github.com/user-attachments/assets/2c18cae5-ba5e-4e01-b7fb-6a95846b1d51)
![a6cc82ed148762f3eee17daca3f078656430b19e3136dfd014f1e43688c2772f](https://github.com/user-attachments/assets/0dba305c-1d78-4faf-9459-3dd047218a32)
![71d03c054edadf782119df789fa81d4b7026ffb7d52c218366b1406221f3f8f0](https://github.com/user-attachments/assets/95ba9bab-7903-4bdc-b199-434b8af76d4b)

**Comment by DSY-xiaoluo** [comment]
（此评论与问题无关）
bedjava键位（图3中的键位）的作者路过[doge]

**Comment by 1008611huafeiztc** [comment]
如修
![Screenshot_2024-07-22-12-53-43-044_com miui securitycenter](https://github.com/user-attachments/assets/6e8ee2ee-e2c4-42f3-bc0a-606b85cc148d)
![Screenshot_2024-07-22-12-33-36-645_com tungsten fcl](https://github.com/user-attachments/assets/b63ecc0e-7d0c-4e30-8f6e-b9ac0370bc88)
![Screenshot_2024-07-22-12-45-17-769_com tungsten fcl](https://github.com/user-attachments/assets/5a455f3d-d276-4598-9d8d-77cf791ffe5a)

**Comment by ShirosakiMio** [comment]
游戏里渲染错误是游戏的事，不关启动器的事

**Comment by Liufeng258** [comment]
> 游戏里渲染错误是游戏的事，不关启动器的事

离线账户的纤细皮肤在FCL里使用好像都是这样的，我记得已经停产的HMCL-PE以及隔壁的ZL2都没有这个问题🤔
