### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by 6833321** [FCL-Team/FoldCraftLauncher#471]
1. 夸克网盘下载速度如果不充VIP还是很慢。建议使用123盘。
2. 下载模组整合包速度一般都会比较慢。建议搞一个后台下载的功能，让用户在下载期间能干别的事。

**Comment by DSY-xiaoluo** [comment]
> 1. 夸克网盘下载速度如果不充VIP还是很慢。建议使用123盘。
> 2. 下载模组整合包速度一般都会比较慢。建议搞一个后台下载的功能，让用户在下载期间能干别的事。

第一个建议你可以看看#314号议题

**Comment by 199825443** [comment]
启动器设置里把并发数拉满，并关掉自动选择并发数

**Comment by zkitefly** [comment]
> 启动器设置里把并发数拉满，并关掉自动选择并发数

并发数是发起多少下载，而不是多线程

而且并发数并不会影响 FCL  从 GitHub 上下载 all-apk 的速度，该慢的还得慢

**Comment by 199825443** [comment]
我就是拉满后速度直接飙升
________________________________
发件人: Zkitefly ***@***.***>
发送时间: 2024年8月26日 13:31
收件人: FCL-Team/FoldCraftLauncher ***@***.***>
抄送: 199825443 ***@***.***>; Comment ***@***.***>
主题: Re: [FCL-Team/FoldCraftLauncher] 两个建议 (Issue #471)


启动器设置里把并发数拉满，并关掉自动选择并发数

并发数是发起多少下载，而不是多线程

而且并发数并不会影响 FCL 从 GitHub 上下载 all-apk 的速度，该慢的还得慢

―
