### ISSUE TITLE
主界面总是显示的过大

### ISSUE THREAD

**Issue by wdnmd2333311** [FCL-Team/FoldCraftLauncher#477]
### Launcher Version

1.1.7.3

### Device Information

vivo y36i 安卓13 

### Problem Description

在分辨率未调动的情况下显示的过大
只看得见2~3个按钮

### Java

java17

### Renderer

holy-GL4ES

### Game Version

1.21

**Comment by ShirosakiMio** [comment]
mc自身问题，界面大小为自动时就这样，自己改
