### ISSUE TITLE
在游戏内物品栏无法点击

### ISSUE THREAD

**Issue by wdnmd2333311** [FCL-Team/FoldCraftLauncher#478]
### Launcher Version

1.1.7.3

### Device Information

vivo y36i 安卓13 

### Problem Description

在原分辨率的情况下进入游戏物品栏无法点击
修改分辨率后依旧是无法点击

### Java

java17

### Renderer

holy-GL4ES

### Game Version

1.21

**Comment by DSY-xiaoluo** [comment]
> ### Launcher Version
> 
> 1.1.7.3
> 
> ### Device Information
> 
> vivo y36i 安卓13 
> 
> ### Problem Description
> 
> 在原分辨率的情况下进入游戏物品栏无法点击
> 修改分辨率后依旧是无法点击
> 
> ### Java
> 
> java17
> 
> ### Renderer
> 
> holy-GL4ES
> 
> ### Game Version
> 
> 1.21
> 
> ### Modifications Made to the Game
> 
> _No response_
> 
> ### Game Crash Report
> 
> _No response_
> 
> ### Launcher Crash Report
> 
> _No response_
> 
> ### Launcher Log File
> 
> _No response_

改物品栏缩放
