### ISSUE TITLE
The Resource Couldn't Loaded Properly

### ISSUE THREAD

**Issue by ManyullynSword** [FCL-Team/FoldCraftLauncher#48]
### Launcher Version

1.0.2

### Device Information

Pixel 5 Arm 64 Android 13

### Problem Description

The Resource Couldn't Loaded Properly

### Java

Java17

### Renderer

Holy-GL 4 ES

### Game Version

1.20.1

### Modifications Made to the Game

Fabric 0.14.21

**Comment by ManyullynSword** [comment]
All the blocks are black, not even a mosaic.

**Comment by ShirosakiMio** [comment]
Don't konw how it happens. Can't fix
