### ISSUE TITLE
希望添加按钮大小可直接输入调整

### ISSUE THREAD

**Issue by JiangYa114514** [FCL-Team/FoldCraftLauncher#480]
### Description

希望添加按钮大小可直接输入调整

### Why

每次调大小都很麻烦

**Comment by DSY-xiaoluo** [comment]
> ### Description
> 
> 希望添加按钮大小可直接输入调整
> 
> ### Why
> 
> 每次调大小都很麻烦

你是否在找：#465号议题

**Comment by ShirosakiMio** [comment]
#465
