### ISSUE TITLE
ANGLE渲染器导致游戏无法启动

### ISSUE THREAD

**Issue by ghost** [FCL-Team/FoldCraftLauncher#490]
### Launcher Version

1.1.7.3

### Device Information

IQOO Z9 Tubro, Android 14, arm64

### Problem Description

如标题，使用ANGLE渲染器导致卡死在Mod加载完毕后的最后一屏并无法进入游戏。
原版可以正常进入游戏，不知道是哪个mod导致的。

### Java

Java17

### Renderer

ANGLE

### Game Version

1.20.1

### Modifications Made to the Game

Forge 47.3.5, Embeddium 0.3.28

### Launcher Log File

[latest_game.log](https://github.com/user-attachments/files/16407373/latest_game.log)
[latest.log](https://github.com/user-attachments/files/16407442/latest.log)

**Comment by TskimiSeiran** [comment]
![Screenshot_20240729_122150_com tungsten fcl](https://github.com/user-attachments/assets/2a28b8c7-9219-45a6-9094-198e2544460d)
如图，启动时卡在这最后一个画面

**Comment by xuehuyue** [comment]
呃，我想说一下，你这种不应该是模组的问题吗？
你应该去该模组下面提 is
而不是启动器下面
