### ISSUE TITLE
FFmpeg库对新版游戏replaymod的适配问题

### ISSUE THREAD

**Issue by flcwsf** [FCL-Team/FoldCraftLauncher#494]
### Description

新版（1.21）游戏+Fabric打开ReplayMod并且导出视频时显示需要安装FFmpeg，希望能快点让FFmpeg适配新版游戏，谢谢！

### Why

因为这个问题导致在Minecraft最新版本无法使用ReplayMod导出视频（也就意味着只能回放，不能发布视频）

**Comment by ShirosakiMio** [comment]
适配不了，似乎从1.17开始就不行了，即使我通过hook的方式更改ffmpeg执行路径也会提示没有权限

**Comment by flcwsf** [comment]
哦好吧，我自己想想办法
