### ISSUE TITLE
希望增加一个添加jdk的功能

### ISSUE THREAD

**Issue by wzjwzjsd** [FCL-Team/FoldCraftLauncher#496]
### Description

我不想用内部jdk了
我想使用最新的jdk22了
我想使用那些openjdk分支了
我不想在去麻烦的更改apk在签名再安装了

### Why

它将不会让我把时间浪费在签名和安装上了

**Comment by ShirosakiMio** [comment]
MT管理器添加本地储存，选择FCL就能直接在mt里改了

**Comment by wzjwzjsd** [comment]
谢谢！
但是它太难发现了
在应用未开启的状态下FCL不显示
我希望FCL像下面的应用一样可以在未开启的状态下发现FCL
![IMG_20240804_230510](https://github.com/user-attachments/assets/8821b7e8-e876-4dcc-ac09-b3868413f07e)
