### ISSUE TITLE
不明原因聊天时发生严重卡顿

### ISSUE THREAD

**Issue by BallonAirr** [FCL-Team/FoldCraftLauncher#497]
### Launcher Version

1.1.7.3

### Device Information

OPPOA93s,Android11,arm64

### Problem Description

聊天或接受信息产生5～10秒不等卡顿

### Java

java21等

### Renderer

holy

### Game Version

1.21/1.16.5

### Modifications Made to the Game

forge/fabric

### Game Crash Report

无

### Launcher Crash Report

无

### Launcher Log File

游戏日志已上传

**Comment by BallonAirr** [comment]
如果log没传上去见「latest.log」，复制整段内容，打开最新版「夸克APP」即可获取。
畅享原画，免费5倍速播放，支持AI字幕和投屏，更有网盘TV版。
/~c4e3343ZkM~:/
链接：https://pan.quark.cn/s/01798cff3e25

**Comment by DSY-xiaoluo** [comment]
你检查一下是不是游戏设置或网络有问题

**Comment by BallonAirr** [comment]
> 你检查一下是不是游戏设置或网络有问题

没有问题 目前检查了forge和fabric都有这个问题 而且严重 近几次启动器更新前没有问题

**Comment by DSY-xiaoluo** [comment]
> > 你检查一下是不是游戏设置或网络有问题
> 
> 没有问题 目前检查了forge和fabric都有这个问题 而且严重 近几次启动器更新前没有问题

那也是游戏问题吧，和启动器没关系

**Comment by BallonAirr** [comment]
> > > 你检查一下是不是游戏设置或网络有问题
> > 
> > 
> > 没有问题 目前检查了forge和fabric都有这个问题 而且严重 近几次启动器更新前没有问题
> 
> 那也是游戏问题吧，和启动器没关系

已测试两个设备 不一样的mod fabric forge均出现问题

**Comment by DSY-xiaoluo** [comment]
> > > > 你检查一下是不是游戏设置或网络有问题
> > > 
> > > 
> > > 没有问题 目前检查了forge和fabric都有这个问题 而且严重 近几次启动器更新前没有问题
> > 
> > 那也是游戏问题吧，和启动器没关系
> 
> 已测试两个设备 不一样的mod fabric forge均出现问题

电脑上试过吗？

**Comment by ShirosakiMio** [comment]
ModernFix 的jei优化关掉
