### ISSUE TITLE
holy渲染器开光影问题

### ISSUE THREAD

**Issue by ThePZY3473** [FCL-Team/FoldCraftLauncher#498]
### Launcher Version

1.1.7.3

### Device Information

Samsung Galaxy C7 Pro，msm8953CPU，Adreno 506GPU，Android 8.0

### Problem Description

多人游戏过程中使用open4es光影，一会儿后画面抽搐，退后台再进入启动器，启动器崩溃
（经过我测试1.12.2、1.16.5的optifine都会这样，但貌似只有周围有玩家时才会触发此bug）

### Java

Java 8

### Renderer

Holy-GL4ES

### Game Version

1.8.9

### Modifications Made to the Game

Optifine-HD-U-M5

**Comment by ThePZY3473** [comment]
这是视频演示（很抱歉，但是视频太大无法上传Github）
https://www.123pan.com/s/lZleVv-u6gi.html

**Comment by ShirosakiMio** [comment]
不考虑光影问题，holy不适合光影，即使是open4es
