### ISSUE TITLE
Sodium can play 

### ISSUE THREAD

**Issue by LdragoLegendOP** [FCL-Team/FoldCraftLauncher#50]
### Description

I can use sodium in foldcraftLauncher crash without sodium patches and how to patch sodium for all version

### Why

Sodium better for give so add sodium patch features

**Comment by didntpenguin** [comment]
download sodium patcher.jar, extract and copy sodium mixins.properties to config folder

**Comment by ShirosakiMio** [comment]
restart

**Comment by Denji499** [comment]
Where to download sodium patcher.jar?
