### ISSUE TITLE
陀螺仪卡顿问题

### ISSUE THREAD

**Issue by kongkong14** [FCL-Team/FoldCraftLauncher#503]
### Launcher Version

1.1.7.4

### Device Information

Redmi Note11t pro, Android14

### Problem Description

陀螺仪一卡一卡的，不管怎么调灵敏度都不行。上一个版本(1.1.7.3)和上上个版本(1.1.7.2)亦是如此

**Comment by ShirosakiMio** [comment]
已知问题，查不出来，目前没法修

**Comment by kongkong14** [comment]
> 已知问题，查不出来，目前没法修

https://1drv.ms/v/c/db7348ca4ca04191/Ee6EckwqLyBNghplPGTL9sMBYPmWqpi26O_ycxFIwXoQ_w

**Comment by kongkong14** [comment]
![Screenshot_2024-08-10-22-24-34-186_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/99cac0aa-eb87-4e2a-971e-0297b47062bb)

**Comment by ShirosakiMio** [comment]
修复了（）T把变量类型写错了，查了这么久才发现
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/10861179960
