### ISSUE TITLE
Twitch Broadcasting Unavailable  Unable to load the libraries needed for the integrated Twitch broadcasting service.

### ISSUE THREAD

**Issue by Trivn-12** [FCL-Team/FoldCraftLauncher#509]
### Launcher Version

Late

### Device Information

Poco c40

### Problem Description

Twitch Broadcasting Unavailable

Unable to load the libraries needed for the integrated Twitch broadcasting service.

### Java

Java8

### Renderer

Holy-GL4ES

### Game Version

1.8.9

### Modifications Made to the Game

Optifile late

### Launcher Log File

[latest.log](https://github.com/user-attachments/files/16548752/latest.log)

**Comment by ShirosakiMio** [comment]
no twitch native library for android

**Comment by jainit703-oss** [comment]
Jainit4
Patel
jainit703@gmail.com
