### ISSUE TITLE
Launcher crash 

### ISSUE THREAD

**Issue by LdragoLegendOP** [FCL-Team/FoldCraftLauncher#51]
### Launcher Version

1.0.1 

### Device Information

Poco c3 Prosser mediatek hello g35 bit 32 

### Problem Description

Uploading Screenrecorder-2023-07-31-07-11-12-44.mp4…

### Java

Jre17 

### Renderer

Render angle and all render

### Game Version

1.20.1

### Modifications Made to the Game

Fabric

**Comment by zkitefly** [comment]
Please upload logs

**Comment by LdragoLegendOP** [comment]
[Uploading fcl-exported-logs-2023-07-31T07-22-20.log…]()

**Comment by zkitefly** [comment]
> Uploading fcl-exported-logs-2023-07-31T07-22-20.log…

Your log was not uploaded successfully...

**Comment by Tungstend** [comment]
Ur log upload failed and u are using old build
