### ISSUE TITLE
I combined optifine and force and it crashed

### ISSUE THREAD

**Issue by sadfl** [FCL-Team/FoldCraftLauncher#510]
### Launcher Version

1.1.0

### Device Information

HTC Desire 22 pro、android12、arm64

### Problem Description

I put the optifine mod into forge and then opened the game and it crashed

### Java

Java17

### Renderer

Holy-GL4ES

### Game Version

1.20.4forge

### Modifications Made to the Game

Forge and optifine

### Game Crash Report

[fcl-latest5580989363228235824.log](https://github.com/user-attachments/files/16550932/fcl-latest5580989363228235824.log)

### Launcher Log File

[fcl-exported-logs-2024-08-09T00-29-56.log](https://github.com/user-attachments/files/16550947/fcl-exported-logs-2024-08-09T00-29-56.log)

**Comment by DSY-xiaoluo** [comment]
> ### Launcher Version
> 
> 1.1.0
> 
> ### Device Information
> 
> HTC Desire 22 pro、android12、arm64
> 
> ### Problem Description
> 
> I put the optifine mod into forge and then opened the game and it crashed
> 
> ### Java
> 
> Java17
> 
> ### Renderer
> 
> Holy-GL4ES
> 
> ### Game Version
> 
> 1.20.4forge
> 
> ### Modifications Made to the Game
> 
> Forge and optifine
> 
> ### Game Crash Report
> 
> [fcl-latest5580989363228235824.log](https://github.com/user-attachments/files/16550932/fcl-latest5580989363228235824.log)
> 
> 
> ### Launcher Crash Report
> 
> _No response_
> 
> ### Launcher Log File
> 
> [fcl-exported-logs-2024-08-09T00-29-56.log](https://github.com/user-attachments/files/16550947/fcl-exported-logs-2024-08-09T00-29-56.log)
> 

optifine啊，那就不奇怪了
![Screenshot_2024_0809_105416.png](https://github.com/user-attachments/assets/48093d02-1a15-4c67-a482-1d6417826233)
[doge]

**Comment by sadfl** [comment]
那有沒有可以替代的，還有兄弟，你這表情包哪找的，夠好笑的

**Comment by DSY-xiaoluo** [comment]
> 那有沒有可以替代的，還有兄弟，你這表情包哪找的，夠好笑的

Forge我暂时找不到其它的，你可以试试Fabric的Iris+Sodium

**Comment by DSY-xiaoluo** [comment]
> 那有沒有可以替代的，還有兄弟，你這表情包哪找的，夠好笑的

如果你依旧希望使用Optifine，可以试试旧版本（如1.16.5）
