### ISSUE TITLE
加载脆骨症整合包时出错

### ISSUE THREAD

**Issue by qualing** [FCL-Team/FoldCraftLauncher#513]
### Launcher Version

1.1.7.4

### Device Information

IQOO Pad 2 Pro, Android 14, arm64

### Problem Description

进入游戏时崩溃

### Java

Java 17

### Renderer

VirGLRenderer

### Game Version

1.19.2

### Modifications Made to the Game

Forge 43.3.8, No Flesh Within CHest

### Launcher Log File

==================== Basic Information ====================
FCL Version: 1.1.7.4
Architecture: arm64
Android SDK: 34
Java Version: 17
Renderer: Holy-GL4ES
Summarize: Application error, unable to launch, exit code = -1
==================== Basic Information ====================

invoke redirectStdio
invoke setLogPipeReady
invoke setFCLNativeWindow
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_loader.c:142
Log pipe ready.
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_bridge.c:60
setFCLNativeWindow : 0x6e4f205f20, size : 3096x2064
invoke setEventPipe
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_event.c:193
Succeeded to set event pipe
==================== Start Minecraft ====================
Device: DPD2329
Architecture: arm64
CPU:mt8796
Android SDK: 34
==================== Env Map ====================
Env: PATH=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Env: LIBGL_NOINTOVLHACK=1
Env: JAVA_HOME=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17
Env: LIBGL_NAME=libgl4es_114.so
Env: LIBGL_STRING=Holy-GL4ES
Env: LIBGL_MIPMAP=3
Env: TMPDIR=/data/user/0/com.tungsten.fcl/cache
Env: LIBGL_ES=2
Env: LIBEGL_NAME=libEGL.so
Env: FCL_NATIVEDIR=/data/app/~~aviFgO3h3I1V5UtgwsVvqw==/com.tungsten.fcl-yvaqCD00KOF3OdgVtm8qQg==/lib/arm64
Env: LIBGL_NOERROR=1
Env: LIBGL_VSYNC=1
Env: HOME=/storage/emulated/0/FCL/log
Env: LIBGL_NORMALIZE=1
==================== Env Map ====================
Working directory: /storage/emulated/0/FCL/.minecraft/versions/No Flesh Within Chest
==================== Minecraft Arguments ====================
Java argument: /data/user/0/com.tungsten.fcl/app_runtime/java/jre17/bin/java
Java argument: -Djava.awt.headless=false
Java argument: -Dcacio.managed.screensize=3096x2064
Java argument: -Dcacio.font.fontmanager=sun.awt.X11FontManager
Java argument: -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler
Java argument: -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel
Java argument: -Dawt.toolkit=com.github.caciocavallosilano.cacio.ctc.CTCToolkit
Java argument: -Djava.awt.graphicsenv=com.github.caciocavallosilano.cacio.ctc.CTCGraphicsEnvironment
Java argument: -Djava.system.class.loader=com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader
Java argument: --add-exports=java.desktop/java.awt=ALL-UNNAMED
Java argument: --add-exports=java.desktop/java.awt.peer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.java2d=ALL-UNNAMED
Java argument: --add-exports=java.desktop/java.awt.dnd.peer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.event=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.datatransfer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.font=ALL-UNNAMED
Java argument: --add-exports=java.base/sun.security.action=ALL-UNNAMED
Java argument: --add-opens=java.base/java.util=ALL-UNNAMED
Java argument: --add-opens=java.desktop/java.awt=ALL-UNNAMED
Java argument: --add-opens=java.desktop/sun.font=ALL-UNNAMED
Java argument: --add-opens=java.desktop/sun.java2d=ALL-UNNAMED
Java argument: --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
Java argument: --add-opens=java.base/java.net=ALL-UNNAMED
Java argument: -Xbootclasspath/a:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
Java argument: -Xmx4096m
Java argument: -Dfile.encoding=UTF-8
Java argument: -Dsun.stdout.encoding=UTF-8
Java argument: -Dsun.stderr.encoding=UTF-8
Java argument: -Djava.rmi.server.useCodebaseOnly=true
Java argument: -Dcom.sun.jndi.rmi.object.trustURLCodebase=false
Java argument: -Dcom.sun.jndi.cosnaming.object.trustURLCodebase=false
Java argument: -Dlog4j2.formatMsgNoLookups=true
Java argument: -Dlog4j.configurationFile=/storage/emulated/0/FCL/.minecraft/versions/No Flesh Within Chest/log4j2.xml
Java argument: -Dminecraft.client.jar=/storage/emulated/0/FCL/.minecraft/versions/No Flesh Within Chest/No Flesh Within Chest.jar
Java argument: -Dfml.ignoreInvalidMinecraftCertificates=true
Java argument: -Dfml.ignorePatchDiscrepancies=true
Java argument: -Dext.net.resolvPath=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/resolv.conf
Java argument: -Djava.io.tmpdir=/data/user/0/com.tungsten.fcl/cache/fclauncher
Java argument: -Dos.name=Linux
Java argument: -Dos.version=Android-14
Java argument: -Dorg.lwjgl.opengl.libname=libgl4es_114.so
Java argument: -Dfml.earlyprogresswindow=false
Java argument: -Dwindow.width=3096
Java argument: -Dwindow.height=2064
Java argument: -Duser.home=/storage/emulated/0/FCL/.minecraft
Java argument: -Duser.language=zh
Java argument: -Duser.timezone=Asia/Shanghai
Java argument: -Djna.boot.library.path=/data/app/~~aviFgO3h3I1V5UtgwsVvqw==/com.tungsten.fcl-yvaqCD00KOF3OdgVtm8qQg==/lib/arm64
Java argument: -Dorg.lwjgl.vulkan.libname=libvulkan.so
Java argument: -Dfcl.injector=4:net.minecraft.client.Minecraft:m_91087_:f_91077_:m_6662_
Java argument: -Djava.library.path=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib:/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib/jli:/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/lib/server:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~aviFgO3h3I1V5UtgwsVvqw==/com.tungsten.fcl-yvaqCD00KOF3OdgVtm8qQg==/lib/arm64
Java argument: -Dminecraft.launcher.brand=Fold Craft Launcher
Java argument: -Dminecraft.launcher.version=1.1.7.4
Java argument: -cp
Java argument: /data/user/0/com.tungsten.fcl/app_runtime/lwjgl/lwjgl.jar:/storage/emulated/0/FCL/.minecraft/libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/minecraftforge/eventbus/6.0.3/eventbus-6.0.3.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/minecraftforge/forgespi/6.0.0/forgespi-6.0.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/cpw/mods/modlauncher/10.0.8/modlauncher-10.0.8.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/minecraftforge/JarJarSelector/0.3.16/JarJarSelector-0.3.16.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/minecraftforge/JarJarMetadata/0.3.16/JarJarMetadata-0.3.16.jar:/storage/emulated/0/FCL/.minecraft/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/minecraftforge/fmlloader/1.19.2-43.3.8/fmlloader-1.19.2-43.3.8.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.0/log4j-slf4j18-impl-2.17.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/authlib/3.11.49/authlib-3.11.49.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/storage/emulated/0/FCL/.minecraft/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar:/storage/emulated/0/FCL/.minecraft/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.17.0/log4j-api-2.17.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.17.0/log4j-core-2.17.0.jar:/storage/emulated/0/FCL/.minecraft/libraries/com/mojang/text2speech/1.16.7/text2speech-1.16.7.jar:/data/user/0/com.tungsten.fcl/files/plugins/MioLaunchWrapper.jar:/storage/emulated/0/FCL/.minecraft/versions/No Flesh Within Chest/No Flesh Within Chest.jar
Java argument: -Djava.net.preferIPv6Addresses=system
Java argument: -DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,JarJarFileSystems,client-extra,fmlcore,javafmllanguage,lowcodelanguage,mclanguage,forge-,No Flesh Within Chest.jar,No Flesh Within Chest.jar
Java argument: -DmergeModules=jna-5.10.0.jar,jna-platform-5.10.0.jar
Java argument: -DlibraryDirectory=/storage/emulated/0/FCL/.minecraft/libraries
Java argument: -p
Java argument: /storage/emulated/0/FCL/.minecraft/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar:/storage/emulated/0/FCL/.minecraft/libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar:/storage/emulated/0/FCL/.minecraft/libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar
Java argument: --add-modules
Java argument: ALL-MODULE-PATH
Java argument: --add-opens
Java argument: java.base/java.util.jar=cpw.mods.securejarhandler
Java argument: --add-opens
Java argument: java.base/java.lang.invoke=cpw.mods.securejarhandler
Java argument: --add-exports
Java argument: java.base/sun.security.util=cpw.mods.securejarhandler
Java argument: --add-exports
Java argument: jdk.naming.dns/com.sun.jndi.dns=java.naming
Java argument: --add-exports
Java argument: cpw.mods.bootstraplauncher/cpw.mods.bootstraplauncher=ALL-UNNAMED
MainClass: mio.Wrapper
MainClass: cpw.mods.bootstraplauncher.BootstrapLauncher
Minecraft argument: --username
Minecraft argument: Bairuichen
Minecraft argument: --version
Minecraft argument: No Flesh Within Chest
Minecraft argument: --gameDir
Minecraft argument: /storage/emulated/0/FCL/.minecraft/versions/No Flesh Within Chest
Minecraft argument: --assetsDir
Minecraft argument: /storage/emulated/0/FCL/.minecraft/assets
Minecraft argument: --assetIndex
Minecraft argument: 1.19
Minecraft argument: --uuid
Minecraft argument: 9ba9f1b57ed6452db039305dd68c5531
Minecraft argument: --accessToken
Minecraft argument: ***
Minecraft argument: --clientId
Minecraft argument: ${clientid}
Minecraft argument: --xuid
Minecraft argument: ${auth_xuid}
Minecraft argument: --userType
Minecraft argument: msa
Minecraft argument: --versionType
Minecraft argument: Fold Craft Launcher
Minecraft argument: --width
Minecraft argument: 3096
Minecraft argument: --height
Minecraft argument: 2064
Minecraft argument: --launchTarget
Minecraft argument: forgeclient
Minecraft argument: --fml.forgeVersion
Minecraft argument: 43.3.8
Minecraft argument: --fml.mcVersion
Minecraft argument: 1.19.2
Minecraft argument: --fml.forgeGroup
Minecraft argument: net.minecraftforge
Minecraft argument: --fml.mcpVersion
Minecraft argument: 20220805.130853
Hook exit success
[03:24:13] [main/INFO]: ModLauncher running: args [--username, Bairuichen, --version, No Flesh Within Chest, --gameDir, /storage/emulated/0/FCL/.minecraft/versions/No Flesh Within Chest, --assetsDir, /storage/emulated/0/FCL/.minecraft/assets, --assetIndex, 1.19, --uuid, 9ba9f1b57ed6452db039305dd68c5531, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, Fold Craft Launcher, --width, 3096, --height, 2064, --launchTarget, forgeclient, --fml.forgeVersion, 43.3.8, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[03:24:13] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.10-internal by N/A; OS Linux arch aarch64 version Android-14
[03:24:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/storage/emulated/0/FCL/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2372!/ Service=ModLauncher Env=CLIENT

**Comment by suq-weer** [comment]
emm，日志看起来好像还没开始运行游戏就已经结束了（
