### ISSUE TITLE
鼠标指针位置偏移

### ISSUE THREAD

**Issue by ZiHaoMC** [FCL-Team/FoldCraftLauncher#515]
### Launcher Version

1.1.7.4

### Device Information

Android 11

### Problem Description

在使用聊天，会自动向下看，在此时鼠标指针位置偏移

### Java

Java 21

### Game Version

1.21

**Comment by Llerey** [comment]
Last action version log

[fcl-latest225788203333778440.log](https://github.com/user-attachments/files/16622808/fcl-latest225788203333778440.log)

**Comment by ShirosakiMio** [comment]
禁用软键盘自适应
