### ISSUE TITLE
更新后不稳定出现的图形问题

### ISSUE THREAD

**Issue by wzjwzjsd** [FCL-Team/FoldCraftLauncher#517]
### Launcher Version

1.1.7.5

### Device Information

realme Q3s RMX3461_11C.13

### Problem Description

因为是图形问题所以首先排查了钠和钠的附属模组，发现问题出现在了IRIS(未加载光影)。
但除此之外还有很多奇怪现象：
1.IRIS和钠·扩展同时运行时不会出现图形问题
2.经过一段时间的测试后问题会消失(测试指反复进入存档后再正常退出到fcl的界面)
3.经过一段时间的放置后会重新出现(放置指不运行游戏的情况下息屏放置)
(猜测可能与温度有关)
4.不同模组(即使与图形无关)会造成不同的图形错误

这张是在Masa全家桶加钠和iris的情况下出现
![Screenshot_2024-08-16-18-27-43-77_c8a66bc90793a73eafa5773962b202df](https://github.com/user-attachments/assets/41ded6e2-80b8-43f2-84b2-e664c3e2d393)

这张是在去除Masa全家桶中的minihud和tweakeroo后出现的
![Screenshot_2024-08-16-18-31-39-51_c8a66bc90793a73eafa5773962b202df](https://github.com/user-attachments/assets/f69b3c4d-ffe1-48fe-8a66-eeb2a2e6cd22)

这张是在只有钠和iris时出现的
![Screenshot_2024-08-16-18-37-58-43_c8a66bc90793a73eafa5773962b202df](https://github.com/user-attachments/assets/5d6693d3-7b6b-41fc-b630-1ba213948b1e)

### Java

java21

### Renderer

Holy GL4ES

### Game Version

1.21

### Modifications Made to the Game

Fabric0.16.0

**Comment by wzjwzjsd** [comment]
还有新发现，版本退回后一样不行

**Comment by wzjwzjsd** [comment]
好消息：重启后消失

**Comment by luohaike** [comment]
我在使用纳和Iris和你遇到了一样的问题，请问一下你解决了吗
