### ISSUE TITLE
部分使用JNA的模组会在启动时崩溃

### ISSUE THREAD

**Issue by Fox-ace** [FCL-Team/FoldCraftLauncher#518]
### Launcher Version

1.1.7.5

### Device Information

OPPO Reno11(PJH110), ColorOS14.0(Android 14), arm64

### Problem Description

在启动部分模组时崩溃，查看日志中出现“There is an incompatible JNA native library installed on this system”

### Java

Java21

### Renderer

Holy-GL4ES

### Game Version

1.21(Fabric)

### Modifications Made to the Game

Fabric

### Game Crash Report

[latest.log](https://github.com/user-attachments/files/16643037/latest.log)

**Comment by ShirosakiMio** [comment]
jna只内置了5.13.0的native库文件，其他版本自己下载替换libjnidispatch.so
