### ISSUE TITLE
添加钠模组或部分模组启动器崩溃

### ISSUE THREAD

**Issue by 199825443** [FCL-Team/FoldCraftLauncher#519]
### Launcher Version

1.1.7.5

### Device Information

redmi pad se，6g内存，androld14

### Problem Description

添加钠模组，瓦尔基里天空，维克的现代战争等模组时会发生崩溃

### Java

21

### Renderer

holy-gl4es

### Game Version

所有版本都会

### Modifications Made to the Game

无

### Launcher Log File

[fcl-exported-logs-2024-08-17T17-31-37.log](https://github.com/user-attachments/files/16644256/fcl-exported-logs-2024-08-17T17-31-37.log)

**Comment by ShirosakiMio** [comment]
不兼容手机，能不崩么

**Comment by ShirosakiMio** [comment]
不兼容手机，能不崩么

**Comment by 199825443** [comment]
> 不兼容手机，能不崩么

我认为是渲染器的事，切换为vir以后可以进入游戏，但不显示方块
