### ISSUE TITLE
crash on fabric 1.18.2

### ISSUE THREAD

**Issue by Qian-F** [FCL-Team/FoldCraftLauncher#52]
### Launcher Version

1.0.5

### Device Information

Realme GT NEO 3 150W

### Problem Description

Initializing game failed

### Java

java 17

### Renderer

所有渲染均报错

### Game Version

1.18.2 fabric

### Game Crash Report

https://mclo.gs/bSOhnhc#L175

**Comment by didntpenguin** [comment]
![Screenshot_2023-07-31-09-37-41-318_com android chrome](https://github.com/FCL-Team/FoldCraftLauncher/assets/118114231/9a4499bb-5450-4f1a-a8ec-55692ed27e6d)
try wen?

**Comment by Qian-F** [comment]
I tried, useless

**Comment by Qian-F** [comment]
crash again

**Comment by didntpenguin** [comment]
> crash again

but big modpacks can't run on mobile, because lag and buggy àg

**Comment by Qian-F** [comment]
But this modpack works fine on my backward computer

**Comment by Qian-F** [comment]
I just want to know which mod is affecting its startup

**Comment by Qian-F** [comment]
this stack may help
https://stackoverflow.com/questions/3613889/gl-framebuffer-incomplete-attachment-when-trying-to-attach-texture

**Comment by zkitefly** [comment]
> crash again

Please upload the log again

**Comment by Qian-F** [comment]
soon 10 min

**Comment by Qian-F** [comment]
Hi here
https://mclo.gs/Qc9pAGt

**Comment by zkitefly** [comment]
> Hi here https://mclo.gs/Qc9pAGt
```
[11:19:39] [main/WARN]: Warnings were found!
 - Mod 'Block Meter' (blockmeter) 1.6 recommends version 1.1.7 or later of modupdater, which is missing!
	 - You should install version 1.1.7 or later of modupdater for the optimal experience.
 - Mod 'Simply Swords' (simplyswords) 1.40-1.18.2 recommends version 1.5.5 or later of bettercombat, which is missing!
	 - You should install version 1.5.5 or later of bettercombat for the optimal experience.
```

**Comment by Qian-F** [comment]
These warnings will not affect the start of the game
I have started many times on PC.

**Comment by zkitefly** [comment]
> Hi here https://mclo.gs/Qc9pAGt

Oh sorry, I read it wrong, the log says: GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT

**Comment by root-S7** [comment]
通用机械mod非高通平台请使用修复版mod!!!!!!!!!!!!!!!!!!

**Comment by Qian-F** [comment]
> 机械动力mod非高通平台请使用修复版mod!!!!!!!!!!!!!!!!!!

指个路

**Comment by Qian-F** [comment]
> > 机械动力mod非高通平台请使用修复版mod!!!!!!!!!!!!!!!!!!
> 
> 指个路

哦 找到了 感谢
