### ISSUE TITLE
Vulkan mod suport

### ISSUE THREAD

**Issue by WesleyVanNeck** [FCL-Team/FoldCraftLauncher#522]
### Description

I can maintain arm64 version that was from soldev

### Why

Better performance

**Comment by WesleyVanNeck** [comment]
i have a build here https://github.com/WesleyVanNeck/VulkanMod/actions/runs/10441973704

**Comment by ShirosakiMio** [comment]
try this
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/10455302323

**Comment by WesleyVanNeck** [comment]
1. Dublicated of #514
