### ISSUE TITLE
[非重要] 主题图标（Themed Icons）支持请求

### ISSUE THREAD

**Issue by SaltedFishesNG** [FCL-Team/FoldCraftLauncher#523]
### Description

请参考：https://developer.android.com/about/versions/13/features#themed-app-icons
或者： https://stackoverflow.com/questions/69800362/how-to-implement-themed-icons-by-material-you-in-my-android-app

### Why

qwq

**Comment by SaltedFishesNG** [comment]
似乎并未完成（？）![Screenshot_20240830-043045_crDroid Home.png](https://github.com/user-attachments/assets/4772f8ff-06af-4054-8cd5-a7224df8a554)

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/10625495312
