### ISSUE TITLE
Rubidium Artifacts

### ISSUE THREAD

**Issue by sharusu** [FCL-Team/FoldCraftLauncher#524]
### Launcher Version

1.1.7.5

### Device Information

Samsung S20FE Snapdragon, Android 13, aarch64 (arm64)

### Problem Description

when the camera/player moves, artifacts related to rendering appear (I think so) 
![Screenshot_20240820_002954_Fold Craft Launcher](https://github.com/user-attachments/assets/8f79377b-e678-4f75-a455-fc16ca94a78b)

### Java

Java 21

### Renderer

Vulkan Zink

### Game Version

1.20.1

### Modifications Made to the Game

Simple Voice Chat, Rubidium

### Launcher Log File

[fcl-exported-logs-2024-08-20T00-36-59.log](https://github.com/user-attachments/files/16665543/fcl-exported-logs-2024-08-20T00-36-59.log)

**Comment by ShirosakiMio** [comment]
rendering issue cannot be resolved
