### ISSUE TITLE
启动器UI渲染错误

### ISSUE THREAD

**Issue by xiangtou** [FCL-Team/FoldCraftLauncher#525]
### Launcher Version

1.1.7.1

### Device Information

Samsung Galaxy S10,Android12,arm64-v8a

### Problem Description

启动器内UI渲染为紫色，文字正常
![Screenshot_20240820-082030_Fold Craft Launcher](https://github.com/user-attachments/assets/efdd1ee1-9c43-4c16-8f78-ab9c6ec90ce6)

**Comment by ShirosakiMio** [comment]
默认会根据你的壁纸提取颜色，并没有错误
