### ISSUE TITLE
Problem with commands 

### ISSUE THREAD

**Issue by Fayzer20** [FCL-Team/FoldCraftLauncher#526]
### Launcher Version

1.1.7.5

### Device Information

Poco X3 pro 

### Problem Description

I can't use /gamemode or other commands on my server 

### Java

17

### Game Version

1.16.5

### Launcher Crash Report

I can't use any commands, not even /gamemode and the others. On my server

**Comment by WesleyVanNeck** [comment]
Server issue

**Comment by Fayzer20** [comment]
> Problema no servidor
Sim
