### ISSUE TITLE
Can't choose forge in vesion creating menu. 

### ISSUE THREAD

**Issue by loluch123321** [FCL-Team/FoldCraftLauncher#527]
### Launcher Version

1.1.7.5

### Device Information

samsung galaxy s24 ultra

### Problem Description

i tried to create new version with forge and optifine but when i trien to choose forge version it just didn't load. Same wirh optifine but other mod installers worked great. 
![Screenshot_20240821_100843_Fold Craft Launcher](https://github.com/user-attachments/assets/cf2dc867-04b6-418f-8320-e2d4cdfc3d0c) And i know that 1.20.4 (my version) had fotge and optifine in launcher before

### Game Version

1.20.4

**Comment by WesleyVanNeck** [comment]
Know and not our issue as the server is down
