### ISSUE TITLE
Modpacks crashing

### ISSUE THREAD

**Issue by didntpenguin** [FCL-Team/FoldCraftLauncher#53]
### Launcher Version

latest

### Device Information

Redmi K40, android 13,arm64

### Problem Description

some 1.7.10 modpacks like regrowth,ftb magic quest... can run on 1.0.1,1.0.2 but in latest version,it's crash

### Java

Java 8

### Renderer

GL4ES

### Game Version

1.7.10

### Modifications Made to the Game

Forge 1.7.10, modpacks regrowth

### Game Crash Report

https://drive.google.com/file/d/1-P6vjwlbXx0-MXV0fNfLj3ce3ZeqMt3B/view?usp=drivesdk

### Launcher Log File

[fcl-exported-logs-2023-07-31T09-34-54.log](https://github.com/FCL-Team/FoldCraftLauncher/files/12210969/fcl-exported-logs-2023-07-31T09-34-54.log)

**Comment by Tungstend** [comment]
Already fixed
