### ISSUE TITLE
The menu to install Forge did not load.

### ISSUE THREAD

**Issue by Seaofstars86** [FCL-Team/FoldCraftLauncher#530]
### Launcher Version

1.1.7.5

### Device Information

Motorola G60, Android 12

### Problem Description

I am trying to install Minecraft in version 1.18.2 with Forge but when I open the menu where Forge is applied it does not load. I tried several times but the menu did not load at any time.

### Launcher Log File

[fcl-exported-logs-2024-08-21T11-12-23.log](https://github.com/user-attachments/files/16695642/fcl-exported-logs-2024-08-21T11-12-23.log)

**Comment by WesleyVanNeck** [comment]
Known and not our issue as the server is down

**Comment by WesleyVanNeck** [comment]
And it's not our server so there is nothing we can do

**Comment by zkitefly** [comment]
Can you open https://bmclapi2.bangbang93.com/forge/minecraft/1.18.2?

**Comment by WesleyVanNeck** [comment]
> Can you open https://bmclapi2.bangbang93.com/forge/minecraft/1.18.2?

Yeah but it happens with optifine and forge

**Comment by WesleyVanNeck** [comment]
java.util.concurrent.CompletionException: java.io.FileNotFoundException: https://bmclapi2.bangbang93.com/forge/minecraft/1.18.2

**Comment by zkitefly** [comment]
![Screenshot_2024-08-22-02-43-14-72_c8a66bc90793a73eafa5773962b202df.jpg](https://github.com/user-attachments/assets/65b4b777-99bb-4216-9318-3214a173ce94)

If it still doesn't work, you can install the original version first, then go to the forge or optifine download page to download the jar file, and then go to settings, loader settings, and install it manually
