### ISSUE TITLE
在1.1.7.6版本中，游戏内无法正常调整分辨率

### ISSUE THREAD

**Issue by LarZavil** [FCL-Team/FoldCraftLauncher#543]
### Launcher Version

1.1.7.6

### Device Information

OPPOR17，Android10，骁龙670

### Problem Description

在游玩1.21版本时，在游戏内调整分辨率异常，并不会适应屏幕，在之前的FCL启动器版本则没有这种情况。
![Screenshot_2024-08-23-18-48-13-44_c8a66bc90793a73eafa5773962b202df](https://github.com/user-attachments/assets/a7e39a09-b62d-4e9c-a034-e40f2c72c0c0)

### Java

Java21

### Renderer

Freedreno

### Game Version

1.21

### Modifications Made to the Game

钠，iris等

**Comment by ShirosakiMio** [comment]
修了https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/10525028937
