### ISSUE TITLE
启动闪退

### ISSUE THREAD

**Issue by xigiy** [FCL-Team/FoldCraftLauncher#55]
![Screenshot_20230731_175811.jpg](https://github.com/FCL-Team/FoldCraftLauncher/assets/132143521/5ae374ea-9713-4da0-803f-522518e6e8e1)

启动时总出现这种情况，使用测试版却能正常使用。
机型
vivo x21a
运行时
自动选择

**Comment by Tungstend** [comment]
这是哪个版本，你说的测试版又是哪个版本
