### ISSUE TITLE
The oshi-core-6.3.0.jar library does not download 

### ISSUE THREAD

**Issue by TeenyZoo4678** [FCL-Team/FoldCraftLauncher#551]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.7.6

### Device Information / 设备信息

Motorola Moto G51 5G/Android 12/arm64

### Problem Description / 问题描述

When removing the **libraries** from the instance game settings and relaunching the game, the **oshi-core-6.3.0.jar** file is not downloaded and the game does not start, the bug is recent

### Java

Java 17

### Renderer / 渲染器

Holly-GL4ES

### Game Version / 游戏版本

1.20.1

### Modifications Made to the Game / 对游戏所做的修改

OptiFine HD_U_I6 & Forge 47.3.7

**Comment by ShirosakiMio** [comment]
#544 
change download source to BMCLAPI

**Comment by TeenyZoo4678** [comment]
Still not working

**Comment by ShirosakiMio** [comment]
mojang source has deleted this [file](https://libraries.minecraft.net/com/github/oshi/oshi-core/6.3.0/oshi-core-6.3.0.jar)

**Comment by ShirosakiMio** [comment]
try this[](https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/10543202131) (wait for building)

**Comment by ShirosakiMio** [comment]
> try this (wait for building)

https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/10543202131

**Comment by TeenyZoo4678** [comment]
Thanks it worked :)
