### ISSUE TITLE
在启动游戏时崩溃了

### ISSUE THREAD

**Issue by Qingjinshikuai** [FCL-Team/FoldCraftLauncher#556]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [x] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.7.7

### Device Information / 设备信息

samsung galaxy a70

### Problem Description / 问题描述

我在启动时出现了未知原因的崩溃重启后我试了删除optifine看看能不能启动进入游戏但是没用，不知道是不是模组冲突还是文件有问题。

### Java

自动

### Renderer / 渲染器

Virglrenderer

### Game Version / 游戏版本

1.16.3

### Game Crash Report / 游戏崩溃报告

[2024-08-27-1.log.gz](https://github.com/user-attachments/files/16755934/2024-08-27-1.log.gz)

**Comment by zkitefly** [comment]
注意，不要下载这个文件，这个是病毒！

**Comment by Qingjinshikuai** [comment]
> 注意，不要下载这个文件，这是病毒！

我有下载到但是已经删了。
