### ISSUE TITLE
在启动器1.1.7.7版本，鼠标位置偏移。

### ISSUE THREAD

**Issue by LarZavil** [FCL-Team/FoldCraftLauncher#564]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.7.7

### Device Information / 设备信息

OPPOR17，Android10，骁龙670

### Problem Description / 问题描述

在这个启动器版本中，出现了鼠标位置偏移的情况，鼠标指的物品栏不是所指向的那一格物品栏。而在之前的启动器版本没有出现过这种情况。
![Screenshot_2024-08-29-19-43-56-33_c8a66bc90793a73eafa5773962b202df](https://github.com/user-attachments/assets/f24b05d3-0f6c-43ae-a479-d71b8707c820)
![Screenshot_2024-08-29-19-44-26-88](https://github.com/user-attachments/assets/5c1f8046-3241-494a-a96c-9c652f2c21e2)

### Java

Java21

### Renderer / 渲染器

Freedreno

### Game Version / 游戏版本

1.21

### Modifications Made to the Game / 对游戏所做的修改

fabric，Sodium，iris等

**Comment by ShirosakiMio** [comment]
#562

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/10615703227

**Comment by ShirosakiMio** [comment]
游戏菜单右侧“鼠标指针偏移”

**Comment by ShirosakiMio** [comment]
#464
