### ISSUE TITLE
Problems with versions below 1.19

### ISSUE THREAD

**Issue by Tet100** [FCL-Team/FoldCraftLauncher#57]
### Launcher Version

1.0.5

### Device Information

Redmi note 10 5g, android 13

### Problem Description

I noticed, below 1.19, the optimization problem starts 

### Java

Java 9

### Renderer

-

### Game Version

<1.19

### Modifications Made to the Game

Without mods and with mods for optimization

**Comment by didntpenguin** [comment]
logcat where? if no log,dev can't fix

**Comment by root-S7** [comment]
？
