### ISSUE TITLE
Function to record gameplays

### ISSUE THREAD

**Issue by EljoseXD123** [FCL-Team/FoldCraftLauncher#570]
### Before making issue / 在发布提问之前...

- [X] I understand this is a request, not a wish.我明白这是在提出请求而不是在许愿。

### Description / 描述

A good feature would be for the launcher to detect if the screen is being recorded, making the controls invisible in the recording

### Why / 原因

it would make the videos look great without the controls being in the way of what you are recording

**Comment by Happ1ness-dev** [comment]
> detect if the screen is being recorded

I don't know if that's really possible.




> making the controls invisible

This is possible already, there's an option for that in overlay/side menu, iirc.

**Comment by ShirosakiMio** [comment]
If you want to see controls when you play but not in the recorded video, that's impossible

**Comment by ShirosakiMio** [comment]
You can only play with mouse&keyboard without controls or remember the position of controls before hiding

**Comment by ShirosakiMio** [comment]
It's better to use replay mod. But... you need to manually convert it to video with ffmpeg. Due to some unknown reasons, ffmpeg cannot be called by replay.
