### ISSUE TITLE
Every keys except tab, space and other nav key is acting like im pressing back button

### ISSUE THREAD

**Issue by ItsMeFary24** [FCL-Team/FoldCraftLauncher#571]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.7.7

### Device Information / 设备信息

Oppo A16, Android 11, arm64 

### Problem Description / 问题描述

Every key (except space, tab, and enter) is acting like I'm pressing the back button (the arrow one below the settings).

If I'm typing to search for a mod, and I'm holding the backspace, it will cause me to exit the launcher like pressing back multiple times

### Java

i don't think info of this input is needed

### Renderer / 渲染器

i don't think info of this input is needed

### Game Version / 游戏版本

i don't think info of this input is needed

### Modifications Made to the Game / 对游戏所做的修改

i don't think info of this input is needed

### Game Crash Report / 游戏崩溃报告

i don't think info of this input is needed

### Launcher Crash Report / 启动器崩溃报告

i don't think info of this input is needed

### Launcher Log File / 启动器日志文件

i don't think info of this input is needed

**Comment by ShirosakiMio** [comment]
I have already mentioned it in the announcement

**Comment by ShirosakiMio** [comment]
You can get latest build here https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/10625495312

**Comment by ItsMeFary24** [comment]
> I have already mentioned it in the announcement

oowhh sorry my bad, i forgot about that because the first time it's doesn't appear to happen
