### ISSUE TITLE
Незапускает beta 1.7.3 и другие

### ISSUE THREAD

**Issue by Mefodiu** [FCL-Team/FoldCraftLauncher#575]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.7.8

### Device Information / 设备信息

Samsung s24

### Problem Description / 问题描述

Вылетает ошибка при запуске beta 1.7.3 примерно с таким содержанием:Невозможно скачать библиотеку org.ow2.asm:asm-all:5.2 java.io.FileNotFoundException: https://libraries.minecraft .net/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar at com.tungsten.fclcore.task.FetchTask.execute(FetchTask Java:127) at com.tungsten.fclcore.task.AsyncTaskExecutor.lambda$e xecuteNormalTask$22Scom-tungsten-fclcore-task-Async TaskExecutor(AsyncTaskExecutor.java:243) at com.tungsten.fclcore.task.AsyncTaskExecutors SExternalSyntheticlambda6.run(Unknown Source:4) at com.tungsten.fclcore.util.Lang.lambdaSwrap$2(Lang.jav а:291) at com.tungsten.fclcore.util.Lang$
ТЕКСТ НЕ ПОЛНЫЙ.
Все моды были отключены перед запуском
Помогите пожалуйсто , я уже всё перепробовал
![Screenshot_20240904_112356_Fold Craft Launcher](https://github.com/user-attachments/assets/b0832277-cc55-4d22-9cee-5cb4aaeaffc1)

### Java

Java 8

### Renderer / 渲染器

Holy-gles4

### Game Version / 游戏版本

Beta 1.7.3

### Game Crash Report / 游戏崩溃报告

[fcl-latest7703428073699305791.log](https://github.com/user-attachments/files/16880571/fcl-latest7703428073699305791.log)

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/10711766720
