### ISSUE TITLE
加入預設控件倉庫

### ISSUE THREAD

**Issue by RuizeSun** [FCL-Team/FoldCraftLauncher#577]
### Before making issue / 在发布提问之前...

- [X] I understand this is a request, not a wish.我明白这是在提出请求而不是在许愿。

### Description / 描述

建議在launcher内部加入控件倉庫，玩家/開發者可以自行上傳自己的控件json（可以參考LSPosed借用github作爲模組倉庫的做法），其他玩家可以通過搜索下載添加到自己的控件庫中。

### Why / 原因

預設的控件太難用了，沒時間調就只能找別人做好的，這樣可以利於玩家互相分享發佈控件，讓launcher更簡單上手。

**Comment by Tungstend** [comment]
可以考虑，但如何进行审核与筛选呢？
仓库里的布局需要由玩家自行上传，我们需要确保控件的质量，不可能什么控件都往里面塞。
控件需区分语言，例如中文控件不适合他国用户，这个可以通过仓库分区和本地语言检测实现筛选。
但在其他方面或许也需要进行一定的区分？例如适用于手机还是平板，或是适用于某些特定整合包，如果加以区分可能更好。
最主要的问题是审核问题，筛选可以暂时不做考虑，但开发者很难有大量的精力审核

**Comment by Tungstend** [comment]
恐怕需要招募一位或数位社区贡献者参与审核，该工作可能会花费不少的时间，同时也不会获得任何物质上的收益

**Comment by Tungstend** [comment]
最多可以将参与者名单加入启动器内置的致谢名单

**Comment by Tungstend** [comment]
另外国内许多地区无法使用github或下载速度过慢

**Comment by Tungstend** [comment]
1.1.8.1已经实现此功能
