### ISSUE TITLE
调整窗口分辨率后鼠标指针偏移失效

### ISSUE THREAD

**Issue by LarZavil** [FCL-Team/FoldCraftLauncher#579]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.7.8

### Device Information / 设备信息

OPPOR17，Android10，骁龙670

### Problem Description / 问题描述

进入游戏后，我会调整分辨率来获得不同游戏体验，但是每次调整完成之后鼠标指针偏移会失效，需要重新在菜单拖条。这无疑挺麻烦的（手残）。希望可以修复这个问题，或者可以添加一个重载按钮（重新拖条真的很难受），万分感激！
![Screenshot_2024-09-10-22-59-38-74_c8a66bc90793a73eafa5773962b202df](https://github.com/user-attachments/assets/03fe6dcb-4f6f-45ac-9b72-9f51b747b343)
![Screenshot_2024-09-10-22-59-53-44](https://github.com/user-attachments/assets/38114aa0-535d-4519-b2cc-916a43136c81)
![Screenshot_2024-09-10-23-00-06-76_c8a66bc90793a73eafa5773962b202df](https://github.com/user-attachments/assets/66d27357-f472-46fa-b531-fa0fddb93e8e)

### Java

Java21

### Renderer / 渲染器

Freedreno

### Game Version / 游戏版本

1.21

### Modifications Made to the Game / 对游戏所做的修改

fabric，Sodium，iris等

**Comment by ShirosakiMio** [comment]
偏移也是靠修改分辨率实现的，没办法

**Comment by ShirosakiMio** [comment]
偏移的值在不同的缩放倍率下效果是不一样的，缩放完可能还是得调偏移

**Comment by LarZavil** [comment]
好吧QWQ
