### ISSUE TITLE
允许在终端和日志中复制文本

### ISSUE THREAD

**Issue by hyplant** [FCL-Team/FoldCraftLauncher#581]
### Before making issue / 在发布提问之前...

- [X] I understand this is a request, not a wish.我明白这是在提出请求而不是在许愿。

### Description / 描述

希望可以在内置shell和游戏日志输出屏幕中长按选择并复制文本。

### Why / 原因

便于复制日志

**Comment by ShirosakiMio** [comment]
游戏内输出的日志长度只会保持在100行，只建议从FCL/log目录下或从崩溃界面获取完整日志。终端里面的复制倒是可以
