### ISSUE TITLE
FCL Detected as threat

### ISSUE THREAD

**Issue by ItsMeFary24** [FCL-Team/FoldCraftLauncher#588]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.7.9

### Device Information / 设备信息

Oppo A16, Android 11, arm64 

### Problem Description / 问题描述

When i open app that has secure payment (feature from oppo that secure the app from possible threat) it's detected FCL as threat and won't let me open the app unless i uninstalled the FCL app

something like below

![Screenshot_2024-09-15-13-20-26-22_1c37ef63dcf02305cb94eec0e7b7412f](https://github.com/user-attachments/assets/0bcfc1c1-54a7-46b5-b514-97c16dbd25b3)

**Comment by WesleyVanNeck** [comment]
This is because of the dubug key

**Comment by WesleyVanNeck** [comment]
We explained it on discord
