### ISSUE TITLE
无法使用VoxelMap Mod

### ISSUE THREAD

**Issue by Xiaomo305Mua** [FCL-Team/FoldCraftLauncher#589]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.7.9

### Device Information / 设备信息

HONOR 20 PRO，Android 10，arm64

### Problem Description / 问题描述

自从Actions#663更新了lwjgl之后，FCL就无法使用VoxelMap Mod，装上此Mod之后启动游戏加载到"Mojang"界面即将进入游戏主菜单时游戏就会崩溃，在此之前此Mod一切正常。
Pojav也是这样，我反馈给他们他们叫我用ADB提供一个日志文件......

### Java

Java 8

### Renderer / 渲染器

Holy-GL4ES

### Game Version / 游戏版本

1.7.10

### Modifications Made to the Game / 对游戏所做的修改

Forge，Liteloader，VoxelMap

### Game Crash Report / 游戏崩溃报告

[latest_game.log](https://github.com/user-attachments/files/17004825/latest_game.log)

### Launcher Crash Report / 启动器崩溃报告

无

### Launcher Log File / 启动器日志文件

[fcl.log](https://github.com/user-attachments/files/17004824/fcl.log)

**Comment by ShirosakiMio** [comment]
因为#660使用了pojav后端

**Comment by Xiaomo305Mua** [comment]
> 因为#660使用了pojav后端

所以澪妈能修好吗（    ）或者给他们修，反正我安卓10又没电脑没法用ADB。。

**Comment by ShirosakiMio** [comment]
lwjgl的opengl部分的问题，得等pojav那边修了

**Comment by ShirosakiMio** [comment]
换成zink倒是可以启动

**Comment by Xiaomo305Mua** [comment]
> 换成zink倒是可以启动

我这破手机只能用holy

**Comment by Xiaomo305Mua** [comment]
> lwjgl的opengl部分的问题，得等pojav那边修了

现在我只发现体素地图不能用，不给他们bugreport的话他们应该不会去修。 。麻

**Comment by Xiaomo305Mua** [comment]
> 换成zink倒是可以启动

澪妈FCL能不能做一下微软用户玩家手臂模型正确显示？我细臂皮肤显示成粗臂。。。

**Comment by ShirosakiMio** [comment]
#612
