### ISSUE TITLE
使用FCL启动器运行MC服务器

### ISSUE THREAD

**Issue by XZH2024** [FCL-Team/FoldCraftLauncher#594]
### Before making issue / 在发布提问之前...

- [X] I understand this is a request, not a wish.我明白这是在提出请求而不是在许愿。

### Description / 描述

完善“执行jar文件”功能，使其能运行mc服务器，最好能再加一个控制台方便输入指令和自定义启动参数
目前使用“执行jar文件”运行服务器后卡在这里了
![Screenshot_2024-09-17-13-29-32-618_com tungsten f](https://github.com/user-attachments/assets/75214448-d7a5-4981-be5b-1dd97118c1f8)
等待5分钟后没有任何反应

### Why / 原因

使用Termux开服较为麻烦，需要先输入pkg install openjdk-17安装java，然后cd到服务器文件夹并使用java -Xmx4g -jar server.jar启动服务器，同时官方只提供了openjdk17，不支持最新版本的mc服务器，而且存储占用也非常高，配置好环境后程序体积达到了800多MB（不包含服务器文件）
并且还出现了
Unsupported Java detected (17-internal). You are running an unsupported, non official, version. Only general availability versions of Java are supported. Please update your Java version. See https://docs.papermc.io/paper/faq#unsupported-java-detected-what-do-i-do for more information.

Failed to load native library:jansi-2.4.0-10e68629ae9ef0b6-libjansi.so. osinfo: Linux/arm64                   java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/usr/tmp/jansi-2.4.0-10e68629ae9ef0b6-libjansi.so: dlopen failed: library "libc.so.6" not found
等报错
希望FCL启动器能支持开服功能

**Comment by zkitefly** [comment]
你可以长按 启动游戏 按钮

**Comment by XZH2024** [comment]
> 你可以长按 启动游戏 按钮

然后怎么做？
![Screenshot_2024-09-17-14-17-31-903_com tungsten f](https://github.com/user-attachments/assets/1e81edb3-1340-4b91-a78e-5af069d9a6af)

**Comment by ShirosakiMio** [comment]
fcl终端不能执行java命令，服务器只建议在termux装linux跑
