### ISSUE TITLE
I'm trying to play this modpack but when I enter the world it closes by itself, the name of the modpack is better mc fabric 2, and there is no reason for the game to close.

### ISSUE THREAD

**Issue by alexdkkdj** [FCL-Team/FoldCraftLauncher#595]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.7.9

### Device Information / 设备信息

Redimi note 12 8gb ram

### Problem Description / 问题描述

I'm trying to play this modpack but when I enter the world it closes by itself, the name of the modpack is better mc fabric 2, and there is no reason for the game to close.

### Java

Automatic

### Renderer / 渲染器

Open GL 2.1

### Game Version / 游戏版本

1.20.1

### Modifications Made to the Game / 对游戏所做的修改

Better mc fabric 2

### Game Crash Report / 游戏崩溃报告

I'm trying to play this modpack but when I enter the world it closes by itself, the name of the modpack is better mc fabric 2, and there is no reason for the game to close.

### Launcher Crash Report / 启动器崩溃报告

I'm trying to play this modpack but when I enter the world it closes by itself, the name of the modpack is better mc fabric 2, and there is no reason for the game to close.

### Launcher Log File / 启动器日志文件

I'm trying to play this modpack but when I enter the world it closes by itself, the name of the modpack is better mc fabric 2, and there is no reason for the game to close.

**Comment by WesleyVanNeck** [comment]
No log no help

**Comment by PRSXFENG** [comment]
This modpack has Sodium, it will not work, so, there is your reason
https://www.curseforge.com/minecraft/modpacks/better-mc-fabric-bmc2/relations/dependencies?page=13
see https://github.com/FCL-Team/FoldCraftLauncher/issues/441

Also, that modpack has ~240 mods
please have realistic expectations, that phone is not capable of running that modpack
