### ISSUE TITLE
Always Crashing

### ISSUE THREAD

**Issue by JohnreyMartes14** [FCL-Team/FoldCraftLauncher#596]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.7.9

### Device Information / 设备信息

POCO F5 5G , ANDROID 14 , Arm 64

### Problem Description / 问题描述

When i use distant horizon it keep crashing

### Java

Auto

### Renderer / 渲染器

Vulkan Zink (OpenGL 4.6)

### Game Version / 游戏版本

1.21.1 Haste

### Modifications Made to the Game / 对游戏所做的修改

Fabric

### Launcher Log File / 启动器日志文件

[fcl-latest6144128850533620924.log](https://github.com/user-attachments/files/17044809/fcl-latest6144128850533620924.log)

**Comment by WesleyVanNeck** [comment]
21:30:54] [main/INFO]: Reason: [NEG_HARD_DEP distanthorizons 2.2.1-a {breaks iris @
