### ISSUE TITLE
The new 1.1.8 update broke the game... 

### ISSUE THREAD

**Issue by Amoodee10** [FCL-Team/FoldCraftLauncher#598]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [ ] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.8.1

### Device Information / 设备信息

Oppo A18, Android 14, arm64-v8a, Mediatek Helio G85 GPU

### Problem Description / 问题描述

On 1.7.9 update, the shader works fine on Zink renderer with 15+ fps at least. Now, the shader broke the game. The screen turn black to normal over again when i join the world with shaders. Even without shader, the fps was like i use a shader (below 25 fps). I tried changing render resolution, but the screen will turn to plain black.. only mouse alone :(.. Guess i have to stick with older version

### Java

Java 8

### Renderer / 渲染器

Zink (Vulkan)

### Game Version / 游戏版本

1.16.5

### Modifications Made to the Game / 对游戏所做的修改

Optifine, Forge, Starlight x Create and more optimizations mod that works before 1.8.1 FCL update

**Comment by Amoodee10** [comment]
It doesn't crash the game, so there's no report log

**Comment by TanakaLun** [comment]
LWLGR 版本更新了吧，那目前最好的方法就是回退旧版本

**Comment by Amoodee10** [comment]
> LWLGR 版本更新了吧，那目前最好的方法就是回退旧版本

Okay, thanks! Hope your team can fix it soon 👍

**Comment by ShirosakiMio** [comment]
1.1.8 is pojav backend

**Comment by LICER369** [comment]
尽快修复！！！！！谢谢
