### ISSUE TITLE
Keep crashing

### ISSUE THREAD

**Issue by JohnreyMartes14** [FCL-Team/FoldCraftLauncher#601]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8

### Device Information / 设备信息

POCO F5 5G 12/256GB

### Problem Description / 问题描述

I tried the immersive portal gun and i download the mod that is needed to make the immersive gun mod but it's still crash i don't know why

### Java

Auto

### Renderer / 渲染器

HOLY-GL4ES

### Game Version / 游戏版本

1.21.1 Haste

### Modifications Made to the Game / 对游戏所做的修改

Fabric

### Launcher Log File / 启动器日志文件

[fcl-latest1172380255670102252.log](https://github.com/user-attachments/files/17082824/fcl-latest1172380255670102252.log)

**Comment by WesleyVanNeck** [comment]
Portal gun is incompatible with your Minecraft version
