### ISSUE TITLE
Add Custom Java VM Options

### ISSUE THREAD

**Issue by eikarna** [FCL-Team/FoldCraftLauncher#606]
### Before making issue / 在发布提问之前...

- [X] I understand this is a request, not a wish.我明白这是在提出请求而不是在许愿。

### Description / 描述

hello, can you guys add additional option to import Java VM? Because I want to import third-party Java VMs such as GraalVM, Azul, and many more.

### Why / 原因

I've heard that changing the Java VM can affect Minecraft performance, including that some mods require a third party Java VM (Ex. FasterRandom Mod).

**Comment by creeperfox987** [comment]
This request may not be accepted

**Comment by ShirosakiMio** [comment]
They are for linux aarch64, not for Android

**Comment by eikarna** [comment]
Oh okay, thank you guys for your attention. I will close this.
