### ISSUE TITLE
Add Zink Render for Fold Craft Launcher 

### ISSUE THREAD

**Issue by LithuanianBoi41** [FCL-Team/FoldCraftLauncher#61]
### Description

We want zink render to play shaders on Minecraft java fold craft launcher android 

### Why

Thanks

**Comment by JmisDump** [comment]
Yeah good idea

**Comment by aaaapai** [comment]
其实已经添加有在里面，但是zink需要vulkan，而且旧mesa zink效率不高。新mesa zink大部分设备是不支持的。总之呢，只能看PojavLauncherTeam的行动。

**Comment by aaaapai** [comment]
其实已经添加有在里面，但是zink需要vulkan，而且旧mesa zink效率不高。新mesa zink大部分设备是不支持的。总之呢，只能看PojavLauncherTeam的行动。
