### ISSUE TITLE
自定义java

### ISSUE THREAD

**Issue by 199825443** [FCL-Team/FoldCraftLauncher#611]
### Before making issue / 在发布提问之前...

- [X] I understand this is a request, not a wish.我明白这是在提出请求而不是在许愿。

### Description / 描述

我不想使用原版的java了，他太卡了。请添加一个自定义java的端口，直接把java的.exe安装程序放进去，启动器自己安装java。或者加几个zulu的优化版java

### Why / 原因

原版的java他太卡了

**Comment by Tungstend** [comment]
那么问题来了，既然你的手机能直接用java的exe安装程序，那你为什么不直接用电脑版的启动器呢（

**Comment by 199825443** [comment]
> 你猜为什么没做这个功能（）

不兼容手机？

**Comment by 199825443** [comment]
> 那么问题来了，既然你的手机能直接用java的exe安装程序，那你为什么不直接用电脑版的启动器呢（

我的意思是自定义JAVA安装而不是在手机上允许EXE

**Comment by leafANDY** [comment]
openj9😭
