### ISSUE TITLE
[Bug] 鼠标右键和中键在 Boat 模式下被交换

### ISSUE THREAD

**Issue by EatHatsuneShallots** [FCL-Team/FoldCraftLauncher#613]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [ ] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

e97ef831f12d3cd6388134c44d98c7bb2791c053

### Device Information / 设备信息

HUAWEI P30 Pro, HarmonyOS 2.0 (Android 10), arm64

### Problem Description / 问题描述

如题

### Java

Java 21

### Renderer / 渲染器

Holy-GL4ES

### Game Version / 游戏版本

1.21.1-Fabric

### Modifications Made to the Game / 对游戏所做的修改

Fabric

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/11010026949

**Comment by EatHatsuneShallots** [comment]
> https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/11010026949

就打了个补丁吗（
