### ISSUE TITLE
是否可以添加联机模块

### ISSUE THREAD

**Issue by Baobuchi** [FCL-Team/FoldCraftLauncher#62]
### Description

一个没有联机的启动器，用户不能与其他用户同一个世界里游玩

### Why

1.用户与用户之间产生友好关系
2.大大减少了动手开服务器的复杂操作
3.可以共同创建一个世界

**Comment by root-S7** [comment]
最大问题是，钱谁出

**Comment by aaaapai** [comment]
> 最大问题是，钱谁出

我记得，HMCL使用了N2N的联机方案

**Comment by aaaapai** [comment]
> 最大问题是，钱谁出

我记得，HMCL使用了N2N的联机方案
