### ISSUE TITLE
长按 Boat 按钮不会调出终端页面

### ISSUE THREAD

**Issue by EatHatsuneShallots** [FCL-Team/FoldCraftLauncher#625]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [ ] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

091d15f411175219ddce2388bced578c31de5e0f

### Device Information / 设备信息

HUAWEI P30 Pro, HarmonyOS 2.0 (Android 10), arm64

### Problem Description / 问题描述

长按主界面的 Boat 按钮不会调出终端页面，但是长按 Pojav 按钮会

**Comment by 199825443** [comment]
终端在pojav可以掉出

**Comment by 199825443** [comment]
都一样

**Comment by 199825443** [comment]
嗨，跟你说一下，fcl的测试版添加了一个长按启动游戏时选择渲染器，反而完全没有了终端
