### ISSUE TITLE
red screen on recent snapshots

### ISSUE THREAD

**Issue by Bobuxic** [FCL-Team/FoldCraftLauncher#628]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.2

### Device Information / 设备信息

chromebook acer Spin 513 (CP513-1H/CP513-1HL/R841LT/R841T)

### Problem Description / 问题描述

when i enter the latest snapshots like 24w39a i always get just a red screen, no logo, no loading, i waited 6 minutes but nothing, the game is running i can hear the music, the buttons i click but theres just a red screen, its only for snapshots

### Java

java 21

### Renderer / 渲染器

Holy-GL4ES

### Game Version / 游戏版本

24w39a

**Comment by 199825443** [comment]
新版本更改了顶点着色器，你需要在设置里把渲染器改成angle

**Comment by 199825443** [comment]
关了吧
