### ISSUE TITLE
renderer error

### ISSUE THREAD

**Issue by Samara3544y5** [FCL-Team/FoldCraftLauncher#63]
### Launcher Version

1.0.6-patch1

### Device Information

HUAWEI Y6 2019

### Problem Description

Please fix I can't see anything in the game everything is too dark.
![Screenshot_20230802_170217_com android gallery3d](https://github.com/FCL-Team/FoldCraftLauncher/assets/141254309/36f63d10-c541-418a-bcc9-4f30321037ee)
![Screenshot_20230802_123113_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/141254309/ae0eb963-4108-4b44-bd76-07ee01670cc2)
![Screenshot_20230802_122234_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/141254309/a85e11cc-1739-47f4-a462-932192a701d0)
![Screenshot_20230802_122234_com tungsten fcl](https://github.com/FCL-Team/FoldCraftLauncher/assets/141254309/1453e195-a4d5-497b-be96-75720e0eba3c)

### Java

Java 8 instant crash, Java 17 error, auto error

### Renderer

Holy-GL4ES,  The rest doesn't work

### Game Version

1.20.1,   All versions since 1.13 have bugs

**Comment by root-S7** [comment]
you need to use 64 bit device

**Comment by Emanuelfab** [comment]
I did test on my dad phone an also my dad phone is 64 bit but still did the same

**Comment by LegacyGamerHD** [comment]
> I did test on my dad phone an also my dad phone is 64 bit but still did the same

Wait for the new update it should be fixed
