### ISSUE TITLE
填充主题色

### ISSUE THREAD

**Issue by mmmdyzy** [FCL-Team/FoldCraftLauncher#632]
### Before making issue / 在发布提问之前...

- [x] I understand this is a request, not a wish.我明白这是在提出请求而不是在许愿。

### Description / 描述

启动器不忽略刘海屏时刘海处可以填充主题色而非纯黑

### Why / 原因

这会使刘海处不容易被注意到

**Comment by ShirosakiMio** [comment]
不忽略就无法对那个区域进行操作
