### ISSUE TITLE
Crashing when i install a mod pack called BM: Revalations II

### ISSUE THREAD

**Issue by JohnreyMartes14** [FCL-Team/FoldCraftLauncher#637]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.2

### Device Information / 设备信息

POCO F5 5G 12/256GB ANDROID 14

### Problem Description / 问题描述

when i install the mod pack called "BM: Revalations II" and after installing it it crash but don't worry I'll send some fcl log so you can find the problems 

### Java

Auto

### Renderer / 渲染器

HOLY-GL4ES

### Game Version / 游戏版本

1.20.1, Forge: 47.3.0

### Modifications Made to the Game / 对游戏所做的修改

Forge

### Launcher Log File / 启动器日志文件

[fcl-latest4191981799670382071.log](https://github.com/user-attachments/files/17199434/fcl-latest4191981799670382071.log)

**Comment by RuizeSun** [comment]
try to use another renderer. if it is still crash, i dont have more idea
