### ISSUE TITLE
强制渲染器在大核上运行

### ISSUE THREAD

**Issue by tazixa** [FCL-Team/FoldCraftLauncher#638]
### Before making issue / 在发布提问之前...

- [X] I understand this is a request, not a wish.我明白这是在提出请求而不是在许愿。

### Description / 描述

可以将pojav设置中的强制渲染器在大核中运行添加到FCL中

### Why / 原因

这样会略微提升一些帧数

**Comment by lzfddkd** [comment]
你确定会提升帧数？你自己先试试

**Comment by 199825443** [comment]
> 你确定会提升帧数？你自己先试试

gpu强的的确可以提升帧数

**Comment by groxs001** [comment]
я был бы рад если это добавили

**Comment by tazixa** [comment]
> я был бы рад если это добавили
Спасибо, друг

**Comment by tazixa** [comment]
> я был бы рад если это добавили
Спасибо, друг

**Comment by tazixa** [comment]
> я был бы рад если это добавили

Спасибо, друг

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/11377845551
