### ISSUE TITLE
Patcher mod crash

### ISSUE THREAD

**Issue by Zelthoo** [FCL-Team/FoldCraftLauncher#64]
### Launcher Version

1.0.6-patch1

### Device Information

Samsung Galaxy A33 5G, Android 13, aarch64

### Problem Description

So I tried to run Patcher mod in Minecraft Forge 1.8.9, At first it was running fine, but when I open a world or when I open the settings, the game freezes and crashes for no reason after a few seconds.
I even tried to run it several times but it gives the same thing.

Would it be possible for you to fix this problem ?
And would it be possible for you to make it work in the next updates ?

If you want, I even recorded to show you how this happened.

https://github.com/FCL-Team/FoldCraftLauncher/assets/80771781/29ef9f2d-e16e-43e1-87b2-8c6439a89234

![Screenshot of the issue](https://github.com/FCL-Team/FoldCraftLauncher/assets/80771781/71f5ef88-4b01-4538-910b-4331b4d80534)

### Java

Java 8

### Renderer

Holy-GL4ES

### Game Version

1.8.9

### Modifications Made to the Game

Forge 11.15.1.2318, OptiFine HD_U_M5, Sidebar Mod Revamp 2.0, BetterFps-1.2.0, Cloud Client 1.4.1, Essential-forge_1-8-9, foamfix-0.6.3-law-1.8.x, Patcher 1.8.7, TimeChanger 1.0

### Game Crash Report

[crash-2023-08-02_17.33.09-client.txt](https://github.com/FCL-Team/FoldCraftLauncher/files/12242854/crash-2023-08-02_17.33.09-client.txt)

### Launcher Crash Report

[fcl-latest4926806606398782674.log](https://github.com/FCL-Team/FoldCraftLauncher/files/12242869/fcl-latest4926806606398782674.log)

### Launcher Log File

[fcl-exported-logs-2023-08-02T19-07-31.log](https://github.com/FCL-Team/FoldCraftLauncher/files/12242898/fcl-exported-logs-2023-08-02T19-07-31.log)

**Comment by ShirosakiMio** [comment]
fixed

**Comment by ShirosakiMio** [comment]
> 

I dont konw how it crash

**Comment by MoonKnightBhai** [comment]
I can't even remove those mods from the modpack . when re launching FCL re adds those mods .

**Comment by ShirosakiMio** [comment]
It's a protection mechanism.Just remove "modpack.cfg" under your modpack folder.

**Comment by ShirosakiMio** [comment]
> I can't even remove those mods from the modpack . when re launching FCL re adds those mods .



> It's a protection mechanism.Just remove "modpack.cfg" under your modpack folder.

or maybe "modpack.json" "manifest.json"

**Comment by ShirosakiMio** [comment]
![image](https://github.com/FCL-Team/FoldCraftLauncher/assets/19233890/8c78809e-5405-4f3c-a5e2-44941aeea6ee)
you must compile yourself or wait for 1.0.7 release

**Comment by Zelthoo** [comment]
> ![image](https://github.com/FCL-Team/FoldCraftLauncher/assets/19233890/8c78809e-5405-4f3c-a5e2-44941aeea6ee)
> you must compile yourself or wait for 1.0.7 release

Can you show me how can I compile it myself ?
