### ISSUE TITLE
Add FFempg for Replay mod

### ISSUE THREAD

**Issue by JiJiucha** [FCL-Team/FoldCraftLauncher#642]
给回放模组加上FFempg😡😡😡
不然该用什么导出视频

**Comment by zkitefly** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/issues/494

https://github.com/FCL-Team/FoldCraftLauncher/issues/336

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/11172790720

**Comment by strobecat** [comment]
> https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/11172790720

你好，请问可以重新发布一下这个文件吗？这个链接已经失效了
