### ISSUE TITLE
在设置中加入一个隐藏悬浮窗的开关

### ISSUE THREAD

**Issue by Kal19801** [FCL-Team/FoldCraftLauncher#643]
### Before making issue / 在发布提问之前...

- [X] I understand this is a request, not a wish.我明白这是在提出请求而不是在许愿。

### Description / 描述

在设置中添加一个隐藏游戏启动后出现的圆形附魔台悬浮窗的开关

### Why / 原因

这样就不用每次打开游戏都要打开悬浮窗再打开隐藏所有控件的开关来关闭这个悬浮窗

**Comment by DSY-xiaoluo** [comment]
这个好，FCL菜单悬浮球确实有点挡了

**Comment by Kal19801** [comment]
1.1.8.6的更新在菜单键打开的界面里加入了这个功能的开关，不过可以的话建议启动器设置里也放一个，不然可能有人关了不知道滑动能打开菜单界面想再打开的时候就急了🧐
