### ISSUE TITLE
FPS dropped since 1.1.8.1 FCL update

### ISSUE THREAD

**Issue by Amoodee10** [FCL-Team/FoldCraftLauncher#648]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [ ] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.3 (latest)

### Device Information / 设备信息

Oppo A18

### Problem Description / 问题描述

The performance dropped to 90 fps to literally 15 fps after updating to use pojav backend

Removing it might be the best way to solve it

I also tried 2 modes (boat&pojav). Still the same

### Java

Java 8

### Renderer / 渲染器

Holy GL4ES

### Game Version / 游戏版本

1.12

### Modifications Made to the Game / 对游戏所做的修改

Optifine, and any optimization mods that works on 1.1.7.9 FCL

**Comment by dontknowhy** [comment]
Not recommended to add too many optimization mods.
Have you tried to reduce your mods number or just have Optifine loaded.
I'm just guessing, not a professional.

**Comment by Amoodee10** [comment]
> Not recommended to add too many optimization mods. Have you tried to reduce your mods number or just have Optifine loaded. I'm just guessing, not a professional.

I just said that it works on older fcl. The fps just went down for no reason about the mods. This problem exist after using pojav backend

**Comment by Amoodee10** [comment]
Well, its now stable as before lol
Case closed

**Comment by Amoodee10** [comment]
Yaey
