### ISSUE TITLE
LTW渲染器问题

### ISSUE THREAD

**Issue by zsw247** [FCL-Team/FoldCraftLauncher#652]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [ ] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.4

### Device Information / 设备信息

REDMI K70E

### Problem Description / 问题描述

正常游玩时，出现openGL错误：1280(Invalid enum)，
Xaero's World Map和Xaero's Minimap和LTW渲染器出现错误导致无法进入世界并闪退

### Java

Java17

### Renderer / 渲染器

LTW

### Game Version / 游戏版本

1.19.2

### Modifications Made to the Game / 对游戏所做的修改

Forge

### Game Crash Report / 游戏崩溃报告

[crash-2024-10-05_23.15.19-client.txt](https://github.com/user-attachments/files/17266731/crash-2024-10-05_23.15.19-client.txt)
[latest.txt](https://github.com/user-attachments/files/17266732/latest.txt)

**Comment by ShirosakiMio** [comment]
来着Pojav，不稳定，不开源，提了也没法修
