### ISSUE TITLE
[Renderer]LTW无法正常加载光影

### ISSUE THREAD

**Issue by dontknowhy** [FCL-Team/FoldCraftLauncher#654]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

8aadce2 (git commit号)(换句话来说就是actions版)

### Device Information / 设备信息

BRT-W09, Android 12, armv8.2-a

### Problem Description / 问题描述

> [!Warning]
> 涉及到传奇级别开发者（不点名防止自搜）的LTW渲染器，我还不知道各位拿没拿到源码或有没有能力对着预编译做hackjob，如果没有可以关掉这个issue了，我会等更新的

新的LTW渲染器能加载未经过修改的Sodium,但是光影会开始报错：（
换了好几个光影(除BSL均经过解压因为minecraft不认光影只认文件夹)：
1. ComplementaryUnbound_r5.3
2. CyanideShaders_v1.1
3. MakeUp-UltraFast-9.0a
4. Open4es(Ultra Lite, Beta7.1.17+, Beta7.Mali)
5. BSL Original v8.3

这些光影均表现为应用后F3菜单带fallback标识或者完全黑屏（Open4es），要么就是设置菜单有可以切换到Optifine模式但是只会应用bloom和带颜色的太阳光效果(好象是CyanideShaders)
如果你很好奇怎么报错的话，我这里有不小心被我完全打乱的报错：
```
basic.fsh: basic.fsh: 0:83: S0032: no default precision defined for variable 'shadowtex0'

deferred1.vsh: deferred1.vsh: 0:40: L0003: Keyword 'noperspective' is reserved

textured.fsh: textured.fsh: 0:28: S0032: no default precision defined for variable 'shadowtex1'

final.vsh: final.vsh: 0:1: L0009: Missing main() function for shader
```

另：我使用Mali G77 MC9,如果Mali用户都有这种问题那我也只好等更新
又另：Minecraft提示的OpenGL版本是3.0而不是4.6,原因未知，ARM的驱动工作疑似太烂了.jpg
还另：LTW在满血Sodium+没光影的情况下从Holy的接近120帧变成60帧都稳不住，以及对于Modern Font Pack疑似有兼容性问题，加了之后会更卡

### Java

Jvav(? 21

### Renderer / 渲染器

LTW

### Game Version / 游戏版本

1.21

### Modifications Made to the Game / 对游戏所做的修改

Iris 1.7.3 + Sodium(未修改) 0.5.11

**Comment by Vera-Firefly** [comment]
这是一个实验性的渲染器,出现任何问题都是合理的,
并且该渲染器并非FCL-Team制作,出现的任何问题都不由FCL-Team承担,如有问题报告,请前往
PojavLauncherTeam:[PojavLauncher](https://github.com/PojavLauncherTeam/PojavLauncher)

**Comment by dontknowhy** [comment]
> 这是一个实验性的渲染器,出现任何问题都是合理的,
> 并且该渲染器并非FCL-Team制作,出现的任何问题都不由FCL-Team承担,如有问题报告,请前往
> PojavLauncherTeam:[PojavLauncher](https://github.com/PojavLauncherTeam/PojavLauncher)

那就算了，下次一定（
