### ISSUE TITLE
Error feedback

### ISSUE THREAD

**Issue by ghost** [FCL-Team/FoldCraftLauncher#66]
### Launcher Version

1.0.6-patch1

### Device Information

Redmi Note 7     Android 10     arm64

### Problem Description

1.12.2 Running the Avaritia module will crash back

### Java

Java8

### Renderer

Holy GL4ES

### Game Version

1.12.2

### Modifications Made to the Game

OptiFine_1.12.2_HD_U_G5     Avaritia     CodeChicken Lib     Forge14.23.5.2860

### Launcher Log File

[fcl-exported-logs-2023-08-03T14-48-52.log](https://github.com/FCL-Team/FoldCraftLauncher/files/12247728/fcl-exported-logs-2023-08-03T14-48-52.log)

**Comment by ShirosakiMio** [comment]
use vgpu
