### ISSUE TITLE
[CRITICAL VIOLATION] FoldCraft violates LTW license

### ISSUE THREAD

**Issue by Felix14-v2** [FCL-Team/FoldCraftLauncher#662]
### Description
Since the https://github.com/FCL-Team/FoldCraftLauncher/commit/61a7c277eb1539a8e3b0e575f95e861b86337530 commit you added the Tinywrapper renderer from the PojavLauncher@QuestCraft project to your launcher. This action directly violates the LTW license: Tinywrapper is published under the [Polyform Shield](https://polyformproject.org/licenses/shield/1.0.0) license, which protects the LTW renderer code from being stolen without the direct permission of its authors.

### Suggested solution
The only right thing you are allowed to do is to revert this commit and remove all the code related to LTW from the FoldCraft Launcher until you have the direct permission to use it in your project.

### Report info
- [X] I have read the publishing guidelines.
- [X] I have searched for existing issues.

### Launcher Version
1.1.8.4 and newer

### Renderer
Tinywrapper (LTW)

**Comment by 199825443** [comment]
能玩不就行，管这么多干啥，人家pojav会管的

**Comment by FLXHubGit** [comment]
> 能玩不就行，管这么多干啥，人家pojav会管的

I mean ArtDev knows about the situation

**Comment by WesleyVanNeck** [comment]
> ### Description
> Since the [61a7c27](https://github.com/FCL-Team/FoldCraftLauncher/commit/61a7c277eb1539a8e3b0e575f95e861b86337530) commit you added the Tinywrapper renderer from the PojavLauncher@QuestCraft project to your launcher. This action directly violates the LTW license: Tinywrapper is published under the [Polyform Shield](https://polyformproject.org/licenses/shield/1.0.0) license, which protects the LTW renderer code from being stolen without the direct permission of its authors.
> 
> ### Suggested solution
> The only right thing you are allowed to do is to revert this commit and remove all the code related to LTW from the FoldCraft Launcher until you have the direct permission to use it in your project.
> 
> ### Report info
> * [x]  I have read the publishing guidelines.
> * [x]  I have searched for existing issues.
> 
> ### Launcher Version
> 1.1.8.4 and newer
> 
> ### Renderer
> Tinywrapper (LTW)

Yes but what about pojav glow worm

**Comment by WesleyVanNeck** [comment]
And no I left foldcraft am no longer in the repo as a admin

**Comment by WesleyVanNeck** [comment]
If your doing this right then opne a issues there to

**Comment by WesleyVanNeck** [comment]
If wand I can sue pojav for things they done in the past so Fock of am done with pojav and minecraft android launcher space in general

**Comment by RaydanOMGr** [comment]
> If wand I can sue pojav for things they done in the past so Fock of am done with pojav and minecraft android launcher space in general

![962355953968234596](https://github.com/user-attachments/assets/d4664758-e41b-4e01-b454-ffd311020d03)

**Comment by Yarpopcat08** [comment]
> And no I left foldcraft am no longer in the repo as a admin

They didn't want to see such an immature, childish person as the project leader?


> If wand I can sue pojav for things they done in the past so Fock of am done with pojav and minecraft android launcher space in general

Please go on, we are interested

**Comment by WesleyVanNeck** [comment]
> > And no I left foldcraft am no longer in the repo as a admin
> 
> They didn't want to see such an immature, childish person as the project leader?
> 
> > If wand I can sue pojav for things they done in the past so Fock of am done with pojav and minecraft android launcher space in general
> 
> Please go on, we are interested, explain us what are you talking about

? What me childish look at self first I left out my self

**Comment by WesleyVanNeck** [comment]
> > If wand I can sue pojav for things they done in the past so Fock of am done with pojav and minecraft android launcher space in general
> 
> LMAO WHAT ARE YOU EVEN TALKING ABOUT

Most forgot something I used to work for pojav

**Comment by WesleyVanNeck** [comment]
> > And no I left foldcraft am no longer in the repo as a admin
> 
> They didn't want to see such an immature, childish person as the project leader?
> 
> > If wand I can sue pojav for things they done in the past so Fock of am done with pojav and minecraft android launcher space in general
> 
> Please go on, we are interested, explain us what are you talking about

Also go ahead make fun of me I am not childish I left because of toxic ness of guys like you are stressing me out

**Comment by Yarpopcat08** [comment]
> ? What me childish look at self first I left out my self

Now calm down, get away from the monitor for a second, maybe go outside for a walk, and when you are ready, please come back and write everything you wanted to say in a readable manner


> Also go ahead make fun of me I am not childish I left because of toxic ness of guys like you are stressing me out

We don't want to make fun of you, this is not in our interests

**Comment by Yarpopcat08** [comment]
> Yes but what about pojav glow worm [Vera-Firefly/Pojav-Glow-Worm@e107abc](https://github.com/Vera-Firefly/Pojav-Glow-Worm/commit/e107abcaf0e2cf8b5d30ad71a24a2d8783538315)

Made an [issue](https://github.com/Vera-Firefly/Pojav-Glow-Worm/issues/319) there)

**Comment by Vera-Firefly** [comment]
> > Yes but what about pojav glow worm [Vera-Firefly/Pojav-Glow-Worm@e107abc](https://github.com/Vera-Firefly/Pojav-Glow-Worm/commit/e107abcaf0e2cf8b5d30ad71a24a2d8783538315)
> 
> Made an [issue](https://github.com/Vera-Firefly/Pojav-Glow-Worm/issues/319) there)

dude, look at this submission!
https://github.com/PojavLauncherTeam/PojavLauncher/issues/6158 
You'll see how wrong you are

**Comment by WesleyVanNeck** [comment]
> > > Yes but what about pojav glow worm [Vera-Firefly/Pojav-Glow-Worm@e107abc](https://github.com/Vera-Firefly/Pojav-Glow-Worm/commit/e107abcaf0e2cf8b5d30ad71a24a2d8783538315)
> > 
> > 
> > Made an [issue](https://github.com/Vera-Firefly/Pojav-Glow-Worm/issues/319) there)
> 
> dude, look at this submission! [PojavLauncherTeam/PojavLauncher#6158](https://github.com/PojavLauncherTeam/PojavLauncher/issues/6158) You'll see how wrong you are

Am not saying it right or wrong am saying if they open a issue then open one at your repo to

**Comment by 199825443** [comment]
#655

**Comment by agent1243** [comment]
ltw creators are very selfish

**Comment by RaydanOMGr** [comment]
> ltw creators are very selfish

And so are FCL developers
