### ISSUE TITLE
Boat后端无法使用LTW渲染器，黑屏后闪退

### ISSUE THREAD

**Issue by TuTou2024** [FCL-Team/FoldCraftLauncher#663]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.5

### Device Information / 设备信息

IQOO 12 Pro

### Problem Description / 问题描述

Boat后端用不了新渲染器，启动之后黑屏闪退，不是模组问题

### Java

全Java版本

### Renderer / 渲染器

TinyWrapper

### Game Version / 游戏版本

全版

**Comment by EatHatsuneShallots** [comment]
https://github.com/FCL-Team/FoldCraftLauncher/issues/655#issuecomment-2399388523
