### ISSUE TITLE
希望改进方向键的控制模式

### ISSUE THREAD

**Issue by yiCIbeet** [FCL-Team/FoldCraftLauncher#675]
### Before making issue / 在发布提问之前...

- [X] I understand this is a request, not a wish.我明白这是在提出请求而不是在许愿。

### Description / 描述

1.取消方向键中键双击潜行选项，将方向键中键修改成和上下左右同样的键值。
2.将方向键分为“按压”和“双击”两种操作模式，可以分别赋予不同的值。
3.将方向键修改成和按键一样，每个键可以被赋予多个键值。

### Why / 原因

我十年前就开始在手机上玩我的世界了，对我来说明显更习惯基岩版旧版本的操作模式。
如果方向键的中键是跳，我就可以用一只手指滑动来操作移动和跳跃。
这对于我这种手残来说真的很重要！😂谢谢

**Comment by 199825443** [comment]
你可以自定义按键输出值

**Comment by yiCIbeet** [comment]
> 你可以自定义按键输出值

似乎中键只有双击才能用

**Comment by yiCIbeet** [comment]
如果我在方向键上加其他按键或者用五个按键代替方向键，这显然不成立，我似乎没有找到能够组合按键的方法

**Comment by 199825443** [comment]
> 如果我在方向键上加其他按键或者用五个按键代替方向键，这显然不成立，我似乎没有找到能够组合按键的方法

中间关闭双击

**Comment by yiCIbeet** [comment]
> > 如果我在方向键上加其他按键或者用五个按键代替方向键，这显然不成立，我似乎没有找到能够组合按键的方法
> 
> 中间关闭双击

关闭中间双击之后就无法使用了，按了没反应
