### ISSUE TITLE
隐藏菜单键后怎么恢复显示

### ISSUE THREAD

**Issue by littleli233** [FCL-Team/FoldCraftLauncher#677]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.6

### Device Information / 设备信息

arm64

### Problem Description / 问题描述

如题

**Comment by 199825443** [comment]
你可以从屏幕右上角滑动

**Comment by 199825443** [comment]
关了吧
