### ISSUE TITLE
add fcl to google play store

### ISSUE THREAD

**Issue by david79111** [FCL-Team/FoldCraftLauncher#678]
### Before making issue / 在发布提问之前...

- [X] I understand this is a request, not a wish.我明白这是在提出请求而不是在许愿。

### Description / 描述

I would like to see this project on play store just like pojav launcher is already on play store

### Why / 原因

It's more convenient and more people would find this project and enjoy it.

**Comment by ShirosakiMio** [comment]
We have no plans to do so

**Comment by david79111** [comment]
I didnt know that a dev account is paid so I guess it's reasonable that there's no google play release.
