### ISSUE TITLE
最新版本启动器更新后控制组件错位

### ISSUE THREAD

**Issue by creeperfox987** [FCL-Team/FoldCraftLauncher#681]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.7

### Device Information / 设备信息

vivoy7s,android9,arm64

### Problem Description / 问题描述

启动启动器时出现问题 具体如下 
![Screenshot_2024_1022_232809](https://github.com/user-attachments/assets/a0b31181-fb0a-4d01-a376-6b8945305c71)
出现了控制组件严重错位,关了忽略刘海屏,开启后也是这样 ,已重复实验

**Comment by creeperfox987** [comment]
![Uploading Screenshot_2024_1022_232809.jpg…]()

**Comment by creeperfox987** [comment]
补充一张图片 
![Uploading Screenshot_2024_1022_233640.jpg…]()

**Comment by creeperfox987** [comment]
![Screenshot_2024_1022_233640](https://github.com/user-attachments/assets/b2c4ca72-6062-48f3-9bdd-1eeb1dd2409e)

**Comment by Quaff03** [comment]
![Screenshot_20241025_172500_com tungsten fcl](https://github.com/user-attachments/assets/78a5f721-46e5-4e07-81bd-d3bb9e8b5bfa)
平板也是如此，左边的组件完全不在屏幕内
