### ISSUE TITLE
未正常捕获外置键盘esc按键

### ISSUE THREAD

**Issue by 123cy321** [FCL-Team/FoldCraftLauncher#688]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.6

### Device Information / 设备信息

三星 z fold3 Android12 arm64

### Problem Description / 问题描述

安卓系统esc按键问题
>处于三星dex模式或者常规桌面，
正常启动游戏
使用外置键盘esc按键会触发安卓系统快捷键，而不是游戏内菜单。
之前版本可以正常捕获，还尝试未回退版本

希望能得到解决

**Comment by 199825443** [comment]
尝试更改系统按键映射

**Comment by liking008** [comment]
可以切换键盘模式吧，现在的键盘一般都可以fn+w切换模式
