### ISSUE TITLE
使用holy渲染器打开1.21.3错误，无法显示画面

### ISSUE THREAD

**Issue by liking008** [FCL-Team/FoldCraftLauncher#689]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.7

### Device Information / 设备信息

iQOO neo9s pro Android14，aarch64

### Problem Description / 问题描述

使用holy渲染器打开1.21.3版本的实例无法正常渲染画面，LTW可以正常渲染，由于Holy比较经典，我希望它可以适配

### Java

JAVA21

### Renderer / 渲染器

Holy-Gl4ES

### Game Version / 游戏版本

1.21.3

### Modifications Made to the Game / 对游戏所做的修改

fabric,纯原版也试过启动直接无法正常显示，LTW可以

**Comment by liking008** [comment]
I have find that Pojav'issue.there is the same problem,they said that need holy fix or use LTW.
我发现pojav那边貌似也有类似议题，他们那边说等待或者使用LTW。

**Comment by 199825443** [comment]
用ltw不行吗，他的性能和open2.3差不多啊

**Comment by frygttt** [comment]
兼容性不好。
