### ISSUE TITLE
外置账户登录的用户名密码输入弹窗的登录和取消按钮互换位置

### ISSUE THREAD

**Issue by zkitefly** [FCL-Team/FoldCraftLauncher#69]
### Description

![Screenshot_2023-08-04-10-32-35-93_c8a66bc90793a73eafa5773962b202df](https://github.com/FCL-Team/FoldCraftLauncher/assets/64117916/4d79fd7a-fff5-4f89-bd78-f4b12aa5e554)

如题

### Why

登录的时候总是点右边的按钮，然后点到取消，用户名和密码白输入了（

**Comment by ShirosakiMio** [comment]
...
