### ISSUE TITLE
Add Instances

### ISSUE THREAD

**Issue by TBG09** [FCL-Team/FoldCraftLauncher#690]
### Before making issue / 在发布提问之前...

- [X] I understand this is a request, not a wish.我明白这是在提出请求而不是在许愿。

### Description / 描述

I would like instances for better organization, and if possible maybe importing modpacks of types from modrinth and curseforge.

### Why / 原因

Over all, this would be a quality of life addition and helps with organization!

**Comment by JadianRadiator** [comment]
Agreed, I want instances too.

**Comment by david79111** [comment]
When clicking on the wrench icon and then game settings there is a per-**instance** toggle and if you toggle it you have many options such as **isolate working directory**.
though I'm not sure if that's what you're looking for

**Comment by JadianRadiator** [comment]
That's exactly it.
I found it in the past day or so, but forgot about the ticket.

**Comment by david79111** [comment]
@TBG09 You should close this issue then
