### ISSUE TITLE
1.1.8.7 版本UI在平板上显示异常

### ISSUE THREAD

**Issue by RuizeSun** [FCL-Team/FoldCraftLauncher#694]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.7

### Device Information / 设备信息

Xiaomi Mi Pad 6 Pro (CN) - MIUI Pad 14.0.9 [UNLOCKED] [ROOT]

### Problem Description / 问题描述

更新後出現
![Screenshot_2024-11-03-11-48-57-512_com tungsten f](https://github.com/user-attachments/assets/877381f2-2bd1-4f51-809d-2be700220fc4)
[fcl.log](https://github.com/user-attachments/files/17609163/fcl.log)

### Java

None

### Renderer / 渲染器

None

### Game Version / 游戏版本

None

### Modifications Made to the Game / 对游戏所做的修改

None

### Game Crash Report / 游戏崩溃报告

None

### Launcher Crash Report / 启动器崩溃报告

None

### Launcher Log File / 启动器日志文件

None

**Comment by DSY-xiaoluo** [comment]
> ### Before making issue / 在发布提问之前...
> 
> - [X] I have read the content above.我已经阅读了上方的内容。
> - [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
> - [X] I have searched for existing issues.我已经搜索了现有的 issues。
> - [X] I have tried switching renderer.我已经尝试过切换渲染器。
> 
> ### Launcher Version / 启动器版本
> 
> 1.1.8.7
> 
> ### Device Information / 设备信息
> 
> Xiaomi Mi Pad 6 Pro (CN) - MIUI Pad 14.0.9 [UNLOCKED] [ROOT]
> 
> ### Problem Description / 问题描述
> 
> 更新後出現
> ![Screenshot_2024-11-03-11-48-57-512_com tungsten f](https://github.com/user-attachments/assets/877381f2-2bd1-4f51-809d-2be700220fc4)
> [fcl.log](https://github.com/user-attachments/files/17609163/fcl.log)
> 
> 
> ### Java
> 
> None
> 
> ### Renderer / 渲染器
> 
> None
> 
> ### Game Version / 游戏版本
> 
> None
> 
> ### Modifications Made to the Game / 对游戏所做的修改
> 
> None
> 
> ### Game Crash Report / 游戏崩溃报告
> 
> None
> 
> ### Launcher Crash Report / 启动器崩溃报告
> 
> None
> 
> ### Launcher Log File / 启动器日志文件
> 
> None

这是由于动画速度设置太高导致的。你可以更新至已修复的最新版本
