### ISSUE TITLE
NTM mod bug

### ISSUE THREAD

**Issue by MaKuZan** [FCL-Team/FoldCraftLauncher#696]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [ ] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

e.g. 1.1.8.7

### Device Information / 设备信息

e.g. Huawei STK-L21 pro, android 10, arm64

### Problem Description / 问题描述

在Minecraft 1.12.2（Extended）版本中使用NTM模组时，发现了一个关键错误，该错误在游戏世界中放置某些特定类型的门时出现。这些门包括："Small QE Containment Door"、"QE Containment Door"、"Sliding Metal Door"、"Large Vehicle Door"、"Round Airlock Door"、"Secure Access Door" 和 "Sideways Sliding Blast Door"。尝试放置这些门中的任何一个都会导致游戏立即崩溃，并显示由Java引起的段错误。

此崩溃仅在启用NTM 1.12.2 Extended模组时发生，目前尚不清楚经典版本的模组是否存在类似问题。以下视频展示了崩溃发生的过程：

https://github.com/user-attachments/assets/6e2aaf04-c45c-4f91-9e3d-ec56454f0ca1

### Java

Auto

### Renderer / 渲染器

VirGLRender

### Game Version / 游戏版本

1.12.2

### Modifications Made to the Game / 对游戏所做的修改

NTM Extended

**Comment by ShirosakiMio** [comment]
换gl4es
