### ISSUE TITLE
FCL1.1.8.7正式版UI显示异常

### ISSUE THREAD

**Issue by cyhcyh0430** [FCL-Team/FoldCraftLauncher#697]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.7

### Device Information / 设备信息

OPPO K10x Android14 arm64

### Problem Description / 问题描述

![Screenshot_2024-11-04-21-26-47-61_c8a66bc90793a73eafa5773962b202df](https://github.com/user-attachments/assets/fd0f23de-c6a5-4c87-ba26-4a897d96b8f7)

**Comment by DSY-xiaoluo** [comment]
> ### Before making issue / 在发布提问之前...
> 
> - [X] I have read the content above.我已经阅读了上方的内容。
> - [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
> - [X] I have searched for existing issues.我已经搜索了现有的 issues。
> - [X] I have tried switching renderer.我已经尝试过切换渲染器。
> 
> ### Launcher Version / 启动器版本
> 
> 1.1.8.7
> 
> ### Device Information / 设备信息
> 
> OPPO K10x Android14 arm64
> 
> ### Problem Description / 问题描述
> 
> ![Screenshot_2024-11-04-21-26-47-61_c8a66bc90793a73eafa5773962b202df](https://github.com/user-attachments/assets/fd0f23de-c6a5-4c87-ba26-4a897d96b8f7)
> 
> 
> ### Java
> 
> _No response_
> 
> ### Renderer / 渲染器
> 
> _No response_
> 
> ### Game Version / 游戏版本
> 
> _No response_
> 
> ### Modifications Made to the Game / 对游戏所做的修改
> 
> _No response_
> 
> ### Game Crash Report / 游戏崩溃报告
> 
> _No response_
> 
> ### Launcher Crash Report / 启动器崩溃报告
> 
> _No response_
> 
> ### Launcher Log File / 启动器日志文件
> 
> _No response_

这是由于动画速度设置太快导致的。你可以更新至已修复的最新版本
