### ISSUE TITLE
在更新时添加Github镜像站的选项

### ISSUE THREAD

**Issue by tiandan250** [FCL-Team/FoldCraftLauncher#699]
### Before making issue / 在发布提问之前...

- [X] I understand this is a request, not a wish.我明白这是在提出请求而不是在许愿。

### Description / 描述

在启动器更新页面加入如https://ghp.ci/的国内下载速度正常的github镜像站

### Why / 原因

夸克网盘限速，github源站国内很多地方也限速严重，现在我每次更新都得使用科学

**Comment by DSY-xiaoluo** [comment]
> ### Before making issue / 在发布提问之前...
> 
> - [X] I understand this is a request, not a wish.我明白这是在提出请求而不是在许愿。
> 
> ### Description / 描述
> 
> 在启动器更新页面加入如https://ghp.ci/的国内下载速度正常的github镜像站
> 
> ### Why / 原因
> 
> 夸克网盘限速，github源站国内很多地方也限速严重，现在我每次更新都得使用科学

猜你在找：[八蓝米](https://alist.8mi.tech/FCL)

**Comment by tiandan250** [comment]
同样需要打开浏览器

> > ### 在发出问题之前/在发布提问之前...
> > 
> > * [x] 我明白这是一个请求，不是一个愿望。我明白这是在提出请求而不是在许愿。
> > 
> > ### 描述/描述
> > 在启动器更新页面加入如[https://ghp.ci/的国内下载速度正常的github镜像站](https://ghp.ci/%E7%9A%84%E5%9B%BD%E5%86%85%E4%B8%8B%E8%BD%BD%E9%80%9F%E5%BA%A6%E6%AD%A3%E5%B8%B8%E7%9A%84github%E9%95%9C%E5%83%8F%E7%AB%99)
> > ### 为什么
> > 夸克网盘限速，github源站国内很多地方也限速严重，现在我每次更新都得使用科学
> 
> 猜你找的是：[八蓝米](https://alist.8mi.tech/FCL)

同样需要打开浏览器

**Comment by DSY-xiaoluo** [comment]
> > > ### 在发出问题之前/在发布提问之前...
> > > 
> > > * [x] 我明白这是一个请求，不是一个愿望。我明白这是在提出请求而不是在许愿。
> > > 
> > > ### 描述/描述
> > > 在启动器更新页面加入如[https://ghp.ci/的国内下载速度正常的github镜像站](https://ghp.ci/%E7%9A%84%E5%9B%BD%E5%86%85%E4%B8%8B%E8%BD%BD%E9%80%9F%E5%BA%A6%E6%AD%A3%E5%B8%B8%E7%9A%84github%E9%95%9C%E5%83%8F%E7%AB%99)
> > > ### 为什么
> > > 夸克网盘限速，github源站国内很多地方也限速严重，现在我每次更新都得使用科学
> > 
> > 猜你找的是：[八蓝米](https://alist.8mi.tech/FCL)
> 
> 同样需要打开浏览器

打开浏览器是什么很麻烦的事吗

**Comment by tiandan250** [comment]
> > > > ### 在发出问题之前/在发布提问之前...
> > > > 
> > > > * [x]  我明白这是一个请求，不是一个愿望。我明白这是在提出请求而不是在许愿。
> > > > 
> > > > ### 描述/描述
> > > > 在启动器更新页面加入如[https://ghp.ci/的国内下载速度正常的github镜像站](https://ghp.ci/%E7%9A%84%E5%9B%BD%E5%86%85%E4%B8%8B%E8%BD%BD%E9%80%9F%E5%BA%A6%E6%AD%A3%E5%B8%B8%E7%9A%84github%E9%95%9C%E5%83%8F%E7%AB%99)
> > > > ### 为什么
> > > > 夸克网盘限速，github源站国内很多地方也限速严重，现在我每次更新都得使用科学
> > > 
> > > 
> > > 猜你找的是：[八蓝米](https://alist.8mi.tech/FCL)
> > 
> > 
> > 同样需要打开浏览器
> 
> 打开浏览器是什么很麻烦的事吗

这难道不是一个很方便玩家的改进吗
