### ISSUE TITLE
can tap on the hotbar

### ISSUE THREAD

**Issue by FrostNovaHD** [FCL-Team/FoldCraftLauncher#70]
### Launcher Version

1.0.6-patch1

### Device Information

samsung galaxy tab a7 (2020 model) android 11

### Problem Description

with render reslution on 60% i cant tab on the hotbar only if i tab on certain way

### Java

java 8

### Renderer

holy-gl4es

### Game Version

1.12.2

### Modifications Made to the Game

optifine

**Comment by ShirosakiMio** [comment]
It's hard to auto resize the hotbar. I also tried 1.12.2 with  60% reslution on PojavLauncher.But ... Maybe add a way to resize hotbar can fix
