### ISSUE TITLE
在安装fabric和fabricapi后打开自动安装菜单显示fabricapi没有安装

### ISSUE THREAD

**Issue by 0zjn0123** [FCL-Team/FoldCraftLauncher#701]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.8

### Device Information / 设备信息

HUAWEI matepad pro13.2 Android12

### Problem Description / 问题描述

在安装fabric和fabricapi后打开自动安装菜单显示fabricapi不安装
![Screenshot_20241110_120119_com tungsten fcl](https://github.com/user-attachments/assets/7e170942-5f11-4e8e-b0a9-9bce52de987b)
![Screenshot_20241110_120124_com tungsten fcl](https://github.com/user-attachments/assets/0429ab20-7aae-47ae-bb66-15e51c7efee4)

### Java

Java21

### Renderer / 渲染器

LTW

### Game Version / 游戏版本

1.21

### Modifications Made to the Game / 对游戏所做的修改

Fabric

**Comment by hd130010** [comment]
实际安上了，只不过不显示
