### ISSUE TITLE
Failed to log in: Invalid session

### ISSUE THREAD

**Issue by Mefodiu** [FCL-Team/FoldCraftLauncher#707]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.8

### Device Information / 设备信息

Samsung s24

### Problem Description / 问题描述

I am trying to log into the server on version 1.14.4, but I get the error Failed to log in: Invalid session "Try restarting your game and the launcher. I don't use mods. The server is working properly and you can access it from other computers. I also used different network connections.
![Screenshot_20241110_211330_Fold Craft Launcher](https://github.com/user-attachments/assets/b8994ffc-08be-413b-b491-c309c95331a9)

### Java

Java 21

### Renderer / 渲染器

Holy-gles4

### Game Version / 游戏版本

1.14.4

### Game Crash Report / 游戏崩溃报告

There is no report

**Comment by hd130010** [comment]
是通过正版正版账号登录的吗

**Comment by Mefodiu** [comment]
I logged into my microsoft account in the launcher, but nothing new appeared. The only thing that came up was the requirement to log in to the xbox. Do I really need to log in to xbox again?
![Screenshot_20241111_144109_Fold Craft Launcher](https://github.com/user-attachments/assets/7af8a3a8-c56f-4656-93dd-c8cded2d2ede)

**Comment by hd130010** [comment]
> 我在启动器中登录了我的 Microsoft 帐户，但没有出现任何新内容。唯一出现的是登录 Xbox 的要求。我真的需要再次登录 Xbox 吗？ ![Screenshot_20241111_144109_Fold Craft Launcher](https://private-user-images.githubusercontent.com/180470780/384907453-7af8a3a8-c56f-4656-93dd-c8cded2d2ede.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDQ0NzksIm5iZiI6MTczMTQwNDE3OSwicGF0aCI6Ii8xODA0NzA3ODAvMzg0OTA3NDUzLTdhZjhhM2E4LWM1NmYtNDY1Ni05M2RkLWM4Y2RlZDJkMmVkZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQwOTM2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTZjN2U5YWFhZWY5ZmRmZjAwYTEwZWVmMDRlNWU1YTA0YmFlODljOTA5NWQ1NDkxNjQzNzIxNzg3NDEwZDc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nt2UqzCGXbiqq_iQ0kRPVXec7Na8IPdmKqmdTH3HiAk)

是购买正版的账号吗？并且您提供一下日志文件

**Comment by Mefodiu** [comment]
No, i just created new xbox account and linked it with my microft account. But launcher now required to login in minecraft java , but a havent a license!!

**Comment by Mefodiu** [comment]
And i cant open your screenshot
