### ISSUE TITLE
关于缺少libpthread.so.0的报告

### ISSUE THREAD

**Issue by CookieCN36** [FCL-Team/FoldCraftLauncher#709]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [ ] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.8

### Device Information / 设备信息

IQOO Z3

### Problem Description / 问题描述

我在启动Labymod-4 1.20.1的时候，发生了报错错误代码1具体报错是java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /data/data/com.tungsten.fcl/cache/fclauncher/liblwjgl.so: dlopen failed: library "libpthread.so.0" not found: needed by /data/data/com.tungsten.fcl/cache/fclauncher/liblwjgl.so in namespace classloader-namespace [in thread "Render thread"]

### Java

JAVA21（应该是的，错误日志里面看到的用的是自动选择）

### Renderer / 渲染器

LTW

### Game Version / 游戏版本

Labymod-4 1.20.1

### Game Crash Report / 游戏崩溃报告

[fcl.log](https://github.com/user-attachments/files/17704531/fcl.log)

### Launcher Log File / 启动器日志文件

[fcl-exported-logs-2024-11-11T23-44-21.log](https://github.com/user-attachments/files/17704547/fcl-exported-logs-2024-11-11T23-44-21.log)

**Comment by ShirosakiMio** [comment]
用不了
