### ISSUE TITLE
Can not run minecraft1.20.1

### ISSUE THREAD

**Issue by qwq3456** [FCL-Team/FoldCraftLauncher#71]
### Launcher Version
1.0.6

### Device Information

vivo s1 pro    Snapdragon 675 Processor  android10

### Problem Description

当我进入我的世界存档后1.几秒便会闪退

### Java

e.g. java17

### Renderer

every one

### Game Version

any version

### Game Crash Report

[latest.log](https://github.com/FCL-Team/FoldCraftLauncher/files/12261708/latest.log)

### Launcher Log File

[fcl-exported-logs-2023-08-04T22-31-27.log](https://github.com/FCL-Team/FoldCraftLauncher/files/12261724/fcl-exported-logs-2023-08-04T22-31-27.log)

**Comment by DarkAaronfox** [comment]
Yes

**Comment by VexroGitHub** [comment]
Make your ram higher and it should work!

**Comment by LegacyGamerHD** [comment]
> ### Launcher Version
> 1.0.6
> 
> ### Device Information
> vivo s1 pro Snapdragon 675 Processor android10
> 
> ### Problem Description
> 当我进入我的世界存档后1.几秒便会闪退
> 
> ### Java
> e.g. java17
> 
> ### Renderer
> houly_gl4es
> 
> ### Game Version
> 1.20.1
> 
> ### Modifications Made to the Game
> _No response_
> 
> ### Game Crash Report
> [latest.log](https://github.com/FCL-Team/FoldCraftLauncher/files/12261708/latest.log)
> 
> ### Launcher Crash Report
> _No response_
> 
> ### Launcher Log File
> [fcl-exported-logs-2023-08-04T22-31-27.log](https://github.com/FCL-Team/FoldCraftLauncher/files/12261724/fcl-exported-logs-2023-08-04T22-31-27.log)

change your download mirror and make sure your on the latest update

**Comment by qwq3456** [comment]
> 把你的公羊调高一点，它就会起作用！

I already tried it, but it doesn't work.

**Comment by didntpenguin** [comment]
> ### Launcher Version
> 1.0.6
> 
> ### Device Information
> vivo s1 pro Snapdragon 675 Processor android10
> 
> ### Problem Description
> 当我进入我的世界存档后1.几秒便会闪退
> 
> ### Java
> e.g. java17
> 
> ### Renderer
> houly_gl4es
> 
> ### Game Version
> 1.20.1
> 
> ### Modifications Made to the Game
> _No response_
> 
> ### Game Crash Report
> [latest.log](https://github.com/FCL-Team/FoldCraftLauncher/files/12261708/latest.log)
> 
> ### Launcher Crash Report
> _No response_
> 
> ### Launcher Log File
> [fcl-exported-logs-2023-08-04T22-31-27.log](https://github.com/FCL-Team/FoldCraftLauncher/files/12261724/fcl-exported-logs-2023-08-04T22-31-27.log)

r u ok? 1.17 and higher use angle renderer
