### ISSUE TITLE
Holy渲染器和LTW渲染器都有缺失libfliteWrapper.so的情况的发生

### ISSUE THREAD

**Issue by NanaAkira73** [FCL-Team/FoldCraftLauncher#714]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.9

### Device Information / 设备信息

Redmi K30Pro

### Problem Description / 问题描述

只安装了原作者的无尽贪婪以及前置，LTW和holy会有无法读取libfliteWrapper.so的情况发生
[无尽贪婪](https://www.curseforge.com/minecraft/mc-mods/avaritia-1-10/files/4406602)

### Java

Java 21

### Renderer / 渲染器

Holy-GL4ES/LTW

### Game Version / 游戏版本

1.18.2

### Modifications Made to the Game / 对游戏所做的修改

Forge，Avaritia

**Comment by ShirosakiMio** [comment]
那是mojang的文字转语音，原版也有这个报错

**Comment by NanaAkira73** [comment]
> 那是mojang的文字转语音，原版也有这个报错

该怎么解决
