### ISSUE TITLE
加载flashback模组会崩溃

### ISSUE THREAD

**Issue by XYisLucky** [FCL-Team/FoldCraftLauncher#720]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.9

### Device Information / 设备信息

荣耀P30

### Problem Description / 问题描述

1.21版本装载模组Flashback(和fabricAPI)时，使用各种渲染器(除VGPU和Zink外)，游戏在启动前(mojang界面出现前)便会崩溃
附上Holy渲染器启动日志
[Holy日志.log](https://github.com/user-attachments/files/17824858/Holy.log)

### Java

Java21

### Game Version / 游戏版本

1.21

### Modifications Made to the Game / 对游戏所做的修改

Fabric   Fabric API   Flashback

### Game Crash Report / 游戏崩溃报告

[Holy日志.log](https://github.com/user-attachments/files/17824874/Holy.log)

**Comment by ShirosakiMio** [comment]
Flashback使用了大量的平台相关c/c++库，作者未提供安卓版本支持，自行编译
