### ISSUE TITLE
安卓原生文件管理在安装fcl之后无法打开

### ISSUE THREAD

**Issue by SMlc666** [FCL-Team/FoldCraftLauncher#722]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.9

### Device Information / 设备信息

Redmi Note10Pro Android13 arm64

### Problem Description / 问题描述

我在更新系统版本后，我打算使用magisk重新修补boot文件，重新root我的手机，可是在我打开magisk之后，点击选择并修补一个文件，啪的一下，安卓原生的文件管理亮了一下图标，然后连带magisk一起闪退了，我不信邪，重复操作多次，重启手机多次，通过mt管理器打开安卓原生文件管理也是一样，在bing搜索这个问题之后，在一个视频【安卓原生文件(com.android.documentsui)打不开?无需root 快速解决!】 https://www.bilibili.com/video/BV1TksteLErU/?share_source=copy_web&vd_source=5ec8edcc901de5a52fca5b0fef0c673f评论区下找到一个评论，内容为:"其实我安装了就突然无法使用文件管理了[吃瓜]",我想到我刚好安装了fcl，于是乎我把fcl卸载之后，安卓原生管理就成功打开了

**Comment by ShirosakiMio** [comment]
自己改了包名才会这样
