### ISSUE TITLE
1.21.3版本启动后黑屏

### ISSUE THREAD

**Issue by gdxuwjwg** [FCL-Team/FoldCraftLauncher#727]
### Before making issue / 在发布提问之前...

- [x] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [ ] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.8.9

### Device Information / 设备信息

HUAWEI nova 7,HarmonyOS 4.2.0和其他设备

### Problem Description / 问题描述

不是进入界面里面好黑呀然后谁在那里直接点到退出键退出了我靠
1.21.3版本启动后出现黑屏，但游戏和启动器未崩溃，有时游戏启动后纯白等其他颜色
![Screenshot_20241123_133258_com tungsten fcl](https://github.com/user-attachments/assets/942b6376-6322-49bc-8a1a-720328552a45)

### Game Version / 游戏版本

1.21.3

**Comment by gdxuwjwg** [comment]
已解决，谢谢大家

**Comment by hd130010** [comment]
怎么又开了

**Comment by hd130010** [comment]
都说了你更新一下启动器或者用ltw渲染器

**Comment by gdxuwjwg** [comment]
@hd130010 已经解决了
