### ISSUE TITLE
Game crash with embeddium

### ISSUE THREAD

**Issue by ThundtrBY** [FCL-Team/FoldCraftLauncher#731]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.9

### Device Information / 设备信息

Redmi K50

### Problem Description / 问题描述

Game crash with embeddium,only occurs in game versions below 1.20 (tested on 1.19.2 and 1.18.2)

### Java

Java17

### Renderer / 渲染器

LTW

### Game Version / 游戏版本

1.19.2

### Modifications Made to the Game / 对游戏所做的修改

Forge 43.4.5,embeddium-0.3.18.1

### Game Crash Report / 游戏崩溃报告

[crash-2024-11-26_15.29.00-client.txt](https://github.com/user-attachments/files/17914710/crash-2024-11-26_15.29.00-client.txt)

**Comment by ShirosakiMio** [comment]
LTW是来自Pojav的，且不开源，任何bug都无法处理
