### ISSUE TITLE
1.6.1以下的版本 会考虑适配Forge吗

### ISSUE THREAD

**Issue by frygttt** [FCL-Team/FoldCraftLauncher#733]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.9.1

### Device Information / 设备信息

iQOO Z7x, Android 13, arm64

### Problem Description / 问题描述

1.6.1以下的版本 会考虑适配Forge吗

**Comment by ShirosakiMio** [comment]
那个好像要java7，手机上没办法
