### ISSUE TITLE
Folder craft Launcher crashing when i use any mod

### ISSUE THREAD

**Issue by Nichimi** [FCL-Team/FoldCraftLauncher#737]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.9.1

### Device Information / 设备信息

Samsung Galaxy S21 5G 128GB

### Problem Description / 问题描述

I've tried using the pojav launcher and now the FCL, I'm starting to think it's my device, please help me. I can play without mods, but when I install any mod, the application gives Error code 1 

### Java

JRE 8

### Renderer / 渲染器

VirgLRenderer (opengl 4.3)

### Game Version / 游戏版本

1.7.10

### Modifications Made to the Game / 对游戏所做的修改

Naruto C

### Launcher Log File / 启动器日志文件

[DOC-20241202-WA0037.txt](https://github.com/user-attachments/files/17984572/DOC-20241202-WA0037.txt)

**Comment by ShirosakiMio** [comment]
lack of this[https://www.curseforge.com/minecraft/mc-mods/jingames-jbra-client](url)
