### ISSUE TITLE
Problems with ram

### ISSUE THREAD

**Issue by Krutoyvovan821** [FCL-Team/FoldCraftLauncher#740]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.9.1

### Device Information / 设备信息

Lenovo legion tab arm64 android 14 

### Problem Description / 问题描述

For example im allocating 4 g of ram but modpack uses 2048 mb,i tried to edit arguments and etc.
![Screenshot_20241208-134010](https://github.com/user-attachments/assets/fb31a9ca-acc7-4dc9-8eca-73d4706dd247)
![Screenshot_20241208-134110](https://github.com/user-attachments/assets/f126fe04-b301-46c3-8f86-2c00e7981203)

### Java

All

### Renderer / 渲染器

All

### Game Version / 游戏版本

1.20.1

### Modifications Made to the Game / 对游戏所做的修改

Forge

### Game Crash Report / 游戏崩溃报告

==================== Basic Information ====================
FCL Version: 1.1.9.1
Architecture: arm64
Android SDK: 34
Java Version: 17
Renderer: Holy-GL4ES
Summarize: Application error, unable to launch, exit code = -1
==================== Basic Information ====================

invoke redirectStdio
invoke setLogPipeReady
[FCL Internal] /home/runner/work/FoldCraftLauncher/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_loader.c:130
Log pipe ready.
invoke setFCLNativeWindow
invoke setEventPipe
==================== Start Minecraft ====================
Device: TB320FC
Architecture: arm64
CPU:qcom
Android SDK: 34
==================== Mods ====================
Mod File: FastFurnace-1.20.1-8.0.2.jar
Mod File: EdivadLib-1.20.1-2.0.1.jar
Mod File: GunpowderLib-1.20.2-2.2.2.jar
Mod File: notrample-1.20.1-1.0.1.jar
Mod File: fuelgoeshere-1.20.0-1.0.1.jar
Mod File: refinedpolymorph-0.1.1-1.20.1.jar
Mod File: polyeng-forge-0.1.1-1.20.1.jar
Mod File: forgivingvoid-forge-1.20-10.0.1.jar
Mod File: ftb-ultimine-forge-2001.1.5.jar
Mod File: colorfulhearts-forge-1.20.1-4.3.16.jar
Mod File: itemcollectors-1.1.10-forge-mc1.20.jar
Mod File: IronJetpacks-1.20.1-7.0.7.jar
Mod File: xnetgases-1.20.1-5.1.4.jar
Mod File: Cucumber-1.20.1-7.0.13.jar
Mod File: CommonCapabilities-1.20.1-2.9.3.jar
Mod File: quartz-1.20.1-0.2.0-alpha.0.1.jar
Mod File: utilitarian-1.20.1-0.9.1.jar
Mod File: NoChatReports-FORGE-1.20.1-v2.2.2.jar
Mod File: waystones-forge-1.20-14.1.6.jar
Mod File: rftoolsstorage-1.20-5.0.3.jar
Mod File: AppliedFlux-1.20-1.1.9-forge.jar
Mod File: thermal_cultivation-1.20.1-11.0.1.24.jar
Mod File: IntegratedTerminals-1.20.1-1.6.3.jar
Mod File: mcw-trapdoors-1.1.3-mc1.20.1forge.jar
Mod File: appleskin-forge-mc1.20.1-2.5.1.jar
Mod File: showcaseitem-1.20.1-1.2.jar
Mod File: energymeter-forge-1.20.1-1.0.0.jar
Mod File: EverlastingAbilities-1.20.1-2.2.0.jar
Mod File: CBMultipart-1.20.1-3.3.0.146-universal.jar
Mod File: connectedglass-1.1.12-forge-mc1.20.1.jar
Mod File: rsrequestify-1.20.1-2.3.3.jar
Mod File: ars_elemental-1.20.1-0.6.7.7.jar
Mod File: ensorcellation-1.20.1-5.0.2.24.jar
Mod File: exmachinis-deorum-1.20.1-3.0.3.jar
Mod File: elevatorid-1.20.1-lex-1.9.jar
Mod File: alltheores-1.20.1-47.1.3-2.2.4.jar
Mod File: FastLeafDecay-32.jar
Mod File: amendments-1.20-1.2.12.jar
Mod File: DefaultWorldType-1.20.1-4.0.4.jar
Mod File: cookingforblockheads-forge-1.20.1-16.0.9.jar
Mod File: NaturesCompass-1.20.1-1.11.2-forge.jar
Mod File: Controlling-forge-1.20.1-12.0.2.jar
Mod File: thermal_expansion-1.20.1-11.0.1.29.jar
Mod File: MekanismGenerators-1.20.1-10.4.10.66.jar
Mod File: MysticalAgradditions-1.20.1-7.0.6.jar
Mod File: mcjtylib-1.20-8.0.6.jar
Mod File: modonomicon-1.20.1-forge-1.77.3.jar
Mod File: cupboard-1.20.1-2.7.jar
Mod File: Glodium-1.20-1.5-forge.jar
Mod File: xnet-1.20-6.1.6.jar
Mod File: forbidden_arcanus-1.20.1-2.2.6.jar
Mod File: glassential-forge-1.20.1-2.0.0.jar
Mod File: ae2wtlib-15.2.3-forge.jar
Mod File: crafting-on-a-stick-1.20.1-1.1.5.jar
Mod File: SkyblockBuilder-1.20.1-5.1.24.jar
Mod File: fusion-1.1.1-forge-mc1.20.1.jar
Mod File: observable-4.4.1.jar
Mod File: thermalendergy-1.20.1-1.0.0.jar
Mod File: mcw-fences-1.1.2-mc1.20.1forge.jar
Mod File: AttributeFix-Forge-1.20.1-21.0.4.jar
Mod File: SmartBrainLib-forge-1.20.1-1.15.jar
Mod File: Bookshelf-Forge-1.20.1-20.2.13.jar
Mod File: plonk-1.20.1-10.0.5-forge.jar
Mod File: curios-forge-5.11.0+1.20.1.jar
Mod File: PickleTweaks-1.20.1-8.0.5.jar
Mod File: resourcefulconfig-forge-1.20.1-2.1.2.jar
Mod File: productivebees-1.20.1-12.6.0.jar
Mod File: exdeorum-1.44.jar
Mod File: hyperbox-1.20.1-4.0.2.0.jar
Mod File: MysticalAgriculture-1.20.1-7.0.14.jar
Mod File: FastWorkbench-1.20.1-8.0.4.jar
Mod File: SkyGUIs-1.20.1-3.0.16.jar
Mod File: DarkUtilities-Forge-1.20.1-17.0.5.jar
Mod File: YouShallNotSpawn-forge-1.20.x-2.0.2.jar
Mod File: findme-3.2.1-forge.jar
Mod File: architectury-9.2.14-forge.jar
Mod File: createaddition-1.20.1-1.2.4e.jar
Mod File: cc-tweaked-1.20.1-forge-1.113.1.jar
Mod File: rubidium-extra-0.5.4.3+mc1.20.1-build.121.jar
Mod File: enderchests-forge-1.20.1-1.3.jar
Mod File: RSInfinityBooster-1.20.1-1.0+41.jar
Mod File: Jade-1.20.1-forge-11.11.1.jar
Mod File: almostunified-forge-1.20.1-0.9.4.jar
Mod File: ApothicAttributes-1.20.1-1.3.7.jar
Mod File: refinedstorage-1.12.4.jar
Mod File: Runelic-Forge-1.20.1-18.0.2.jar
Mod File: inventoryessentials-forge-1.20.1-8.2.6.jar
Mod File: valhelsia_core-forge-1.20.1-1.1.2.jar
Mod File: ExtendedAE-1.20-1.2.1-forge.jar
Mod File: ftb-chunks-forge-2001.3.3.jar
Mod File: allthemodium-1.20.1-47.1.25-2.5.1.jar
Mod File: trashcans-1.0.18b-forge-mc1.20.jar
Mod File: entityculling-forge-1.7.1-mc1.20.1.jar
Mod File: rhino-forge-2001.2.3-build.6.jar
Mod File: ponderjs-1.20.1-1.4.0.jar
Mod File: bdlib-1.27.0.8-mc1.20.1.jar
Mod File: UtilitiX-1.20.1-0.8.23.jar
Mod File: Powah-5.0.7.jar
Mod File: ftb-teams-forge-2001.3.0.jar
Mod File: reliquary-1.20.1-2.0.45.1248.jar
Mod File: LibX-1.20.1-5.0.14.jar
Mod File: angelring-1.20.1-2.3.1.jar
Mod File: rftoolsbase-1.20-5.0.5.jar
Mod File: kubejs-forge-2001.6.5-build.16.jar
Mod File: rftoolspower-1.20-6.0.2.jar
Mod File: geckolib-forge-1.20.1-4.4.9.jar
Mod File: jeiintegration_1.20.1-10.0.0.jar
Mod File: durabilitytooltip-1.1.5-forge-mc1.20.jar
Mod File: redstone_arsenal-1.20.1-8.0.1.24.jar
Mod File: alchemylib-1.20.1-1.0.30.jar
Mod File: resourcefullib-forge-1.20.1-2.1.29.jar
Mod File: mob_grinding_utils-1.20.1-1.1.0.jar
Mod File: bwncr-forge-1.20.1-3.17.1.jar
Mod File: OctoLib-FORGE-0.4.2+1.20.1.jar
Mod File: JustEnoughProfessions-forge-1.20.1-3.0.1.jar
Mod File: ironfurnaces-1.20.1-4.1.6.jar
Mod File: absentbydesign-1.20.1-1.9.0.jar
Mod File: ae2insertexportcard-1.20.1-1.3.0.jar
Mod File: default-server-properties-forge-81.1.0.jar
Mod File: supermartijn642configlib-1.1.8-forge-mc1.20.jar
Mod File: antiblocksrechiseled-0.4.4.jar
Mod File: trashslot-forge-1.20-15.1.0.jar
Mod File: FramedBlocks-9.3.1.jar
Mod File: oculus-mc1.20.1-1.7.0.jar
Mod File: JCPlugin-1.17.x-1.20.x-4.0.4-Forge.jar
Mod File: ars_nouveau-1.20.1-4.12.6-all.jar
Mod File: SimpleBackups-1.20.1-3.1.7.jar
Mod File: moredragoneggs-4.0.jar
Mod File: ars_caelum-1.20.1-2.0.1.jar
Mod File: Super Factory Manager-1.20.1-4.19.0.jar
Mod File: IntegratedCrafting-1.20.1-1.1.9.jar
Mod File: Shrink-1.20.1-1.4.5.jar
Mod File: ClickMachine-1.20.1-8.0.2.jar
Mod File: MouseTweaks-forge-mc1.20.1-2.25.1.jar
Mod File: Exchangers-1.20.1-3.5.1.jar
Mod File: CobbleForDays-1.8.0.jar
Mod File: Emojiful-Forge-1.20.1-4.2.0.jar
Mod File: buildinggadgets2-1.0.7.jar
Mod File: generatorgalore-1.20.1-1.2.4.jar
Mod File: polymorph-forge-0.49.5+1.20.1.jar
Mod File: allthetweaks-1.20.1-47.2.20-2.3.2.jar
Mod File: crashutilities-8.1.4.jar
Mod File: pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar
Mod File: BridgingMod-2.5.1+1.20.1.forge-release.jar
Mod File: modular-routers-12.1.1+mc1.20.1.jar
Mod File: kotlinforforge-4.11.0-all.jar
Mod File: refinedstorageaddons-0.10.0.jar
Mod File: IntegratedTunnels-1.20.1-1.8.32.jar
Mod File: silent-lib-1.20.1-8.0.0.jar
Mod File: PigPen-Forge-1.20.1-15.0.2.jar
Mod File: FarmersDelight-1.20.1-1.2.5.jar
Mod File: spark-1.10.53-forge.jar
Mod File: titanium-1.20.1-3.8.32.jar
Mod File: rftoolsbuilder-1.20-6.0.8.jar
Mod File: shetiphiancore-forge-1.20.1-1.4.jar
Mod File: YetAnotherConfigLib-3.6.1+1.20.1-forge.jar
Mod File: Applied-Botanics-forge-1.5.0.jar
Mod File: mcw-bridges-3.0.0-mc1.20.1forge.jar
Mod File: appliede-0.14.1.jar
Mod File: CyclopsCore-1.20.1-1.19.5.jar
Mod File: NonConflictKeys-Forge-1.19.X-1.20-1.0.0.jar
Mod File: ferritecore-6.0.1-forge.jar
Mod File: mcw-windows-2.3.0-mc1.20.1forge.jar
Mod File: creativewirelesstransmitter-1.20.1-1.1.jar
Mod File: sophisticatedstorage-1.20.1-0.10.50.955.jar
Mod File: darksmithing-forge-1.20.1-1.0.5.jar
Mod File: Croptopia-1.20.1-FORGE-3.0.4.jar
Mod File: pylons-1.20.1-4.2.1.jar
Mod File: thermal_innovation-1.20.1-11.0.1.23.jar
Mod File: sophisticatedbackpacks-1.20.1-3.20.17.1150.jar
Mod File: Apotheosis-1.20.1-7.4.3.jar
Mod File: cofh_core-1.20.1-11.0.2.56.jar
Mod File: tombstone-1.20.1-8.8.6.jar
Mod File: ScalableCatsForce-3.3.1-build-0-with-library.jar
Mod File: jei-1.20.1-forge-15.20.0.105.jar
Mod File: simplemagnets-1.1.12-forge-mc1.20.1.jar
Mod File: PackMenu-1.20.1-6.1.2.jar
Mod File: dankstorage-forge-1.20.1-13.jar
Mod File: comforts-forge-6.4.0+1.20.1.jar
Mod File: entangled-1.3.20-forge-mc1.20.4.jar
Mod File: Applied-Mekanistics-1.4.2.jar
Mod File: SolarGeneration-1.20.1-6.0.2.jar
Mod File: IntegratedDynamics-1.20.1-1.23.13.jar
Mod File: Placebo-1.20.1-8.6.2.jar
Mod File: CodeChickenLib-1.20.1-4.4.0.516-universal.jar
Mod File: rechiseled-1.1.6-forge-mc1.20.jar
Mod File: canary-mc1.20.1-0.3.3.jar
Mod File: Clumps-forge-1.20.1-12.0.0.4.jar
Mod File: embeddium-0.3.31+mc1.20.1.jar
Mod File: Not Enough Recipe Book-FORGE-0.4.1+1.20.1.jar
Mod File: EpheroLib-1.20.1-FORGE-1.2.0.jar
Mod File: torchmaster-20.1.9.jar
Mod File: occultism-1.20.1-1.140.2.jar
Mod File: ThermalExtra-3.2.0-1.20.1.jar
Mod File: moonlight-1.20-2.13.33-forge.jar
Mod File: phosphophyllite-1.20.1-0.7.0-alpha.0.1.jar
Mod File: aecapfix-0.9.jar
Mod File: connectivity-1.20.1-6.1.jar
Mod File: modernfix-forge-5.19.5+mc1.20.1.jar
Mod File: WitherSkeletonTweaks-1.20.1-9.1.0.jar
Mod File: JadeAddons-1.20.1-Forge-5.3.1.jar
Mod File: DefaultSettings-1.20.x-4.0.7-Forge.jar
Mod File: rftoolsutility-1.20-6.0.6.jar
Mod File: balm-forge-1.20.1-7.3.9-all.jar
Mod File: Patchouli-1.20.1-84-FORGE.jar
Mod File: reap-forge-1.20.1-1.1.2.jar
Mod File: FluxNetworks-1.20.1-7.2.1.15.jar
Mod File: item-filters-forge-2001.1.0-build.59.jar
Mod File: mcw-doors-1.1.1forge-mc1.20.1.jar
Mod File: endertanks-forge-1.20.1-1.4.jar
Mod File: biggerreactors-1.20.1-0.6.0-beta.10.4.jar
Mod File: teamprojecte-1.20.1-1.1.4.jar
Mod File: megacells-forge-2.4.5-1.20.1.jar
Mod File: configured-forge-1.20.1-2.2.3.jar
Mod File: Searchables-forge-1.20.1-1.0.3.jar
Mod File: Iceberg-1.20.1-forge-1.1.25.jar
Mod File: constructionwand-1.20.1-2.11.jar
Mod File: Draconic-Evolution-1.20.1-3.1.2.598-universal.jar
Mod File: invtweaks-1.20.1-1.2.0.jar
Mod File: ExtremeSoundMuffler-3.48-forge-1.20.1.jar
Mod File: packetfixer-forge-1.4.2-1.19-to-1.20.1.jar
Mod File: lootr-forge-1.20-0.7.34.89.jar
Mod File: JustEnoughResources-1.20.1-1.4.0.247.jar
Mod File: ftb-library-forge-2001.2.6.jar
Mod File: XyCraft Override-0.6.22.jar
Mod File: thermal_dynamics-1.20.1-11.0.1.23.jar
Mod File: advgenerators-1.6.0.6-mc1.20.1.jar
Mod File: pipez-forge-1.20.1-1.2.16.jar
Mod File: MythicBotany-1.20.1-4.0.3.jar
Mod File: ImmersiveEngineering-1.20.1-10.1.0-171.jar
Mod File: ars_ocultas-1.20.1-1.2.2-all.jar
Mod File: MekanismTools-1.20.1-10.4.10.66.jar
Mod File: laserio-1.6.8.jar
Mod File: cosmeticarmorreworked-1.20.1-v1a.jar
Mod File: functionalstorage-1.20.1-1.2.12.jar
Mod File: craftingtweaks-forge-1.20.1-18.2.5.jar
Mod File: athena-forge-1.20.1-3.1.2.jar
Mod File: ftb-ranks-forge-2001.1.3.jar
Mod File: mcw-furniture-3.3.0-mc1.20.1forge.jar
Mod File: kubejs_enderio-forge-1.20.1-0.6.0.jar
Mod File: MysticalCustomization-1.20.1-5.0.2.jar
Mod File: merequester-forge-1.20.1-1.1.5.jar
Mod File: OreBerries-Replanted-1.20.1-0.5.2.jar
Mod File: FlowerPatch-forge-1.20.1-3.1.0.jar
Mod File: AE2-Things-1.2.1.jar
Mod File: ftb-quests-forge-2001.4.9.jar
Mod File: ftb-xmod-compat-forge-2.1.1.jar
Mod File: XyCraft Machines-0.6.22.jar
Mod File: craftingstation-1.20.1-1.2.3.jar
Mod File: supermartijn642corelib-1.1.17a-forge-mc1.20.1.jar
Mod File: easy-villagers-forge-1.20.1-1.1.23.jar
Mod File: ProjectE-1.20.1-PE1.0.1.jar
Mod File: squatgrow-forge-5.3.0+mc1.20.1.jar
Mod File: forcecraft-1.20.1-4.2.0.jar
Mod File: ftb-essentials-forge-2001.2.2.jar
Mod File: Measurements-forge-1.20.1-2.0.0.jar
Mod File: AdvancedAE-0.9.0-1.20.1-beta.jar
Mod File: EnchantmentDescriptions-Forge-1.20.1-17.1.19.jar
Mod File: cloth-config-11.1.136-forge.jar
Mod File: arseng-1.2.0.jar
Mod File: summoningrituals-forge-1.20.1-2.0.8.jar
Mod File: allthecompressed-1.20.1-3.0.2.jar
Mod File: XyCraft Core-0.6.22.jar
Mod File: supplementaries-1.20-3.1.10.jar
Mod File: industrial-foregoing-1.20.1-3.5.19.jar
Mod File: productivetrees-1.20.1-0.2.6.jar
Mod File: create-1.20.1-0.5.1.j.jar
Mod File: smoothchunk-1.20.1-3.8.jar
Mod File: time-in-a-bottle-4.0.4-mc1.20.1.jar
Mod File: XyCraft World-0.6.22.jar
Mod File: StructureCompass-1.20.1-2.1.0.jar
Mod File: tempad-forge-1.20.1-2.3.4.jar
Mod File: HostileNeuralNetworks-1.20.1-5.3.3.jar
Mod File: Translocators-1.20.1-2.6.0.86-universal.jar
Mod File: sophisticatedcore-1.20.1-0.7.11.799.jar
Mod File: FastSuite-1.20.1-5.0.1.jar
Mod File: flib-1.20.1-0.0.14.jar
Mod File: silent-gear-1.20.1-3.6.6.jar
Mod File: GatewaysToEternity-1.20.1-4.2.6.jar
Mod File: YeetusExperimentus-Forge-2.3.1-build.6+mc1.20.1.jar
Mod File: farmingforblockheads-forge-1.20.1-14.0.2.jar
Mod File: BrandonsCore-1.20.1-3.2.1.302-universal.jar
Mod File: thermal_foundation-1.20.1-11.0.6.70.jar
Mod File: appliedenergistics2-forge-15.2.13.jar
Mod File: Mekanism-1.20.1-10.4.10.66.jar
Mod File: alchemistry-1.20.1-2.3.4.jar
Mod File: Botania-1.20.1-446-FORGE.jar
Mod File: mcw-roofs-2.3.1-mc1.20.1forge.jar
Mod File: simplylight-1.20.1-1.4.6-build.50.jar
Mod File: smoothboot(reloaded)-mc1.20.1-0.0.4.jar
Mod File: matc-1.6.0.jar
Mod File: Necronomicon-Forge-1.6.0+1.20.1.jar
Mod File: moreoverlays-1.22.7-mc1.20.2.jar
Mod File: sound-physics-remastered-forge-1.20.1-1.4.5.jar
Mod File: ExtraStorage-1.20.1-4.0.7.jar
Mod File: morered-1.20.1-4.0.0.4.jar
Mod File: bloodmagic-1.20.1-3.3.3-45.jar
Mod File: EnderIO-1.20.1-6.2.2-beta-all.jar
Mod File: chemlib-1.20.1-2.0.19.jar
Mod File: chipped-forge-1.20.1-3.0.7.jar
==================== Env Map ====================
Env: PATH=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Env: POJAV_RENDERER=opengles2
Env: POJAV_NATIVEDIR=/data/app/~~Va47lSjxArRKIE8q-GgMRQ==/com.tungsten.fcl-qO1Pvf8miKlUglHxHm9TUw==/lib/arm64
Env: JSP=/data/app/~~Va47lSjxArRKIE8q-GgMRQ==/com.tungsten.fcl-qO1Pvf8miKlUglHxHm9TUw==/lib/arm64/libjsph17.so
Env: LIBGL_NOINTOVLHACK=1
Env: FORCE_VSYNC=false
Env: JAVA_HOME=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17
Env: LIBGL_MIPMAP=3
Env: TMPDIR=/data/user/0/com.tungsten.fcl/cache
Env: LIBGL_ES=2
Env: FCL_NATIVEDIR=/data/app/~~Va47lSjxArRKIE8q-GgMRQ==/com.tungsten.fcl-qO1Pvf8miKlUglHxHm9TUw==/lib/arm64
Env: LD_LIBRARY_PATH=/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~Va47lSjxArRKIE8q-GgMRQ==/com.tungsten.fcl-qO1Pvf8miKlUglHxHm9TUw==/lib/arm64
Env: LIBGL_NOERROR=1
Env: HOME=/storage/emulated/0/FCL/log
Env: LIBGL_NORMALIZE=1
==================== Env Map ====================
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16384
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is Qualcomm
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
Working directory: /storage/emulated/0/FCL/.minecraft/versions/atm9sky
==================== Minecraft Arguments ====================
Java argument: /data/user/0/com.tungsten.fcl/app_runtime/java/jre17/bin/java
Java argument: -Djava.awt.headless=false
Java argument: -Dcacio.managed.screensize=2560x1600
Java argument: -Dcacio.font.fontmanager=sun.awt.X11FontManager
Java argument: -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler
Java argument: -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel
Java argument: -Dawt.toolkit=com.github.caciocavallosilano.cacio.ctc.CTCToolkit
Java argument: -Djava.awt.graphicsenv=com.github.caciocavallosilano.cacio.ctc.CTCGraphicsEnvironment
Java argument: -Djava.system.class.loader=com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader
Java argument: --add-exports=java.desktop/java.awt=ALL-UNNAMED
Java argument: --add-exports=java.desktop/java.awt.peer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.java2d=ALL-UNNAMED
Java argument: --add-exports=java.desktop/java.awt.dnd.peer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.event=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.awt.datatransfer=ALL-UNNAMED
Java argument: --add-exports=java.desktop/sun.font=ALL-UNNAMED
Java argument: --add-exports=java.base/sun.security.action=ALL-UNNAMED
Java argument: --add-opens=java.base/java.util=ALL-UNNAMED
Java argument: --add-opens=java.desktop/java.awt=ALL-UNNAMED
Java argument: --add-opens=java.desktop/sun.font=ALL-UNNAMED
Java argument: --add-opens=java.desktop/sun.java2d=ALL-UNNAMED
Java argument: --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
Java argument: --add-opens=java.base/java.net=ALL-UNNAMED
Java argument: -Xbootclasspath/a:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
Java argument: -Xmx2048m
Java argument: -Dfile.encoding=UTF-8
Java argument: -Dsun.stdout.encoding=UTF-8
Java argument: -Dsun.stderr.encoding=UTF-8
Java argument: -Djava.rmi.server.useCodebaseOnly=true
Java argument: -Dcom.sun.jndi.rmi.object.trustURLCodebase=false
Java argument: -Dcom.sun.jndi.cosnaming.object.trustURLCodebase=false
Java argument: -Dlog4j2.formatMsgNoLookups=true
Java argument: -Dlog4j.configurationFile=/storage/emulated/0/FCL/.minecraft/versions/atm9sky/log4j2.xml
Java argument: -Dminecraft.client.jar=/storage/emulated/0/FCL/.minecraft/versions/atm9sky/atm9sky.jar
Java argument: -Dfml.ignoreInvalidMinecraftCertificates=true
Java argument: -Dfml.ignorePatchDiscrepancies=true
Java argument: -Dext.net.resolvPath=/data/user/0/com.tungsten.fcl/app_runtime/java/jre17/resolv.conf
Java argument: -Djava.io.tmpdir=/data/user/0/com.tungsten.fcl/cache/fclauncher
Java argument: -Dos.name=Linux
Java argument: -Dos.version=Android-14
Java argument: -Dorg.lwjg

**Comment by gggn9375-alt** [comment]
hkfn

**Comment by gggn9375-alt** [comment]
gj
