### ISSUE TITLE
无法登录微软账户

### ISSUE THREAD

**Issue by shuTwT** [FCL-Team/FoldCraftLauncher#745]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [ ] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.9.3

### Device Information / 设备信息

Honor magic 6, android 15, arm64

### Problem Description / 问题描述

在账户管理点击微软账户尝试登录，在打开的应用内网页中完成微软账户的登录后会显示：
大功告成！
你现在已登陆到 Fold Craft Launcher。现在可以安全的关闭此窗口。
此时尝试返回，fcl会显示：
⚠️警告
无法连接认证服务器，请检查网络

已在科学上网和未科学上网的情况下测试

**Comment by Weileqian123456789** [comment]
他回复的是:**你的账户尚未获取 Minecraft : Java Edition**我应该怎么解决

<img width="2400" height="1080" alt="Image" src="https://github.com/user-attachments/assets/a069a285-e15e-4b65-ade4-064d2f424b3d" />
