### ISSUE TITLE
模组选项页面无法看到已安装模组，刷新也不出，点击更新崩溃

### ISSUE THREAD

**Issue by TOYBOXSM** [FCL-Team/FoldCraftLauncher#750]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [X] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.9.5

### Device Information / 设备信息

1+8t，安卓11，氢os11.0.14.14.kb05，骁龙865

### Problem Description / 问题描述

模组选项页面无法看到已安装模组，刷新也不出，点击更新崩溃，另外一部手机1+5无此问题

### Java

由启动器自动选择

### Renderer / 渲染器

holy-gl4es(其他渲染器已更换，均无效)

### Game Version / 游戏版本

1.20.1,1.21,1.21.1

### Modifications Made to the Game / 对游戏所做的修改

fabric

### Launcher Crash Report / 启动器崩溃报告

[crash_report2229512736401402165.txt](https://github.com/user-attachments/files/18244334/crash_report2229512736401402165.txt)

**Comment by ShirosakiMio** [comment]
试试这个https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/12499321696/artifacts/2362436950
