### ISSUE TITLE
angle渲染器

### ISSUE THREAD

**Issue by Xiaona-UwU** [FCL-Team/FoldCraftLauncher#751]
### Before making issue / 在发布提问之前...

- [X] I understand this is a request, not a wish.我明白这是在提出请求而不是在许愿。

### Description / 描述

Zalith Launcher都加回来了,FCL要不也加回来？

### Why / 原因

🙃

**Comment by ShirosakiMio** [comment]
FCL可以以插件的方式自己添加渲染器

**Comment by Xiaona-UwU** [comment]
> FCL可以以插件的方式自己添加渲染器

我也想整啊，但是我不会🤔

**Comment by ShirosakiMio** [comment]
https://github.com/FCL-Team/FCLRendererPlugin/releases/tag/Renderer

**Comment by ShirosakiMio** [comment]
用这个https://github.com/FCL-Team/FoldCraftLauncher/actions/runs/12499583764

**Comment by Xiaona-UwU** [comment]
> https://github.com/FCL-Team/FCLRendererPlugin/releases/tag/Renderer

谢谢大佬\(  ͯω  ͯ)/
