### ISSUE TITLE
Forge无法正常安装更新

### ISSUE THREAD

**Issue by 2017MCcat** [FCL-Team/FoldCraftLauncher#754]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [ ] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.9.6

### Device Information / 设备信息

vivo Y76S v2156a

### Problem Description / 问题描述

1.20.1现forge版本为47.3.12，今天尝试直接更新至47.3.22时出现问题，下载阶段全部完成，但是卡在了安装Forge阶段。切换数据网络及Wifi，切换下载源皆无法解决
![Screenshot_20241226_160425_c8a66bc90793a73eafa5773962b202df](https://github.com/user-attachments/assets/8ad9989c-2076-4636-80e0-8a7d41412d44)

### Java

Java21

### Renderer / 渲染器

LTW

### Game Version / 游戏版本

1.20.1

### Modifications Made to the Game / 对游戏所做的修改

OptFine HD_U_I6 Forge 47.3.12

### Launcher Log File / 启动器日志文件

[fcl-exported-logs-2024-12-26T16-04-58.log](https://github.com/user-attachments/files/18251021/fcl-exported-logs-2024-12-26T16-04-58.log)
[fcl-exported-logs-2024-12-26T16-15-12.log](https://github.com/user-attachments/files/18251064/fcl-exported-logs-2024-12-26T16-15-12.log)

**Comment by YihaiNalu** [comment]
我今天重置我的手機,剛剛載回來也1.20.1也卡在Forge安裝...但是我的會提示應用程式停止回應！

**Comment by ning-g-mo** [comment]
手动安装试逝吧
貌似服务器问题
此外forge安装需要时间

**Comment by ShirosakiMio** [comment]
在修了
