### ISSUE TITLE
mod管理页面的mod图标

### ISSUE THREAD

**Issue by Xiaona-UwU** [FCL-Team/FoldCraftLauncher#757]
### Before making issue / 在发布提问之前...

- [X] I have read the content above.我已经阅读了上方的内容。
- [X] I understand what I'm asking is not about modpack.我明白我询问的不是整合包相关的问题。
- [X] I have searched for existing issues.我已经搜索了现有的 issues。
- [ ] I have tried switching renderer.我已经尝试过切换渲染器。

### Launcher Version / 启动器版本

1.1.9.7

### Device Information / 设备信息

vivo y100i mt3833

### Problem Description / 问题描述

把在线联网显示图标去了吧，这玩意儿特别容易误识别。把钠的图标显示一个毫不相关的模组...

### Launcher Log File / 启动器日志文件

![Screenshot_20241228_085044_com tungsten fcl](https://github.com/user-attachments/assets/57422ee9-35e0-48c0-8571-0d9952045439)

**Comment by Xiaona-UwU** [comment]
滑动模组列表图标还会乱窜

**Comment by ShirosakiMio** [comment]
安卓Listview异步加载的问题,你滑动一下就正常了,目前还没好办法解决.滑动太快了就有概率这样
