### ISSUE TITLE
Add function to blur the key

### ISSUE THREAD

**Issue by 2young2care** [FCL-Team/FoldCraftLauncher#762]
### Before making issue / 在发布提问之前...

- [X] I understand this is a request, not a wish.我明白这是在提出请求而不是在许愿。

### Description / 描述

![Screenshot_2024-12-29-08-05-57-436_com tungsten fcl](https://github.com/user-attachments/assets/6f9a1c80-64c8-47ba-b254-9baa7c2e68c5)
The key blocking the view is annoying for cpvp people so I request to add a key blur function like pojavlauncher .

### Why / 原因

Reduces visibility when adding too many keys

**Comment by ShirosakiMio** [comment]
![8db79564207376bd4faaf00ef7670bb4](https://github.com/user-attachments/assets/3171048b-5ee3-44e5-b4a2-b3ddc4445683)
![e6ea0e14014889610b309c0a4da37fea](https://github.com/user-attachments/assets/92301aa6-fbf9-4a83-88bc-11a17155bd32)
You can change style. This is transparency.

**Comment by 2young2care** [comment]
Thank you
