### ISSUE TITLE
when Activating shaders in Shaderpacks it crashes pls fix:(

### ISSUE THREAD

**Issue by rawflesh233** [FCL-Team/FoldCraftLauncher#79]
### Launcher Version

1.0.1

### Device Information

Andriod 13

### Problem Description

so i was downloading Shader for Holy renderer 
and going to try it and then when activating it it crashes not just with the shader and when you press "Internal" render it crashes as well i tested on the other shaders it still crashes please fix this :(

### Java

Java 17

### Renderer

Holy-gl4es

### Game Version

1.20

### Modifications Made to the Game

Optifine and Forge

### Game Crash Report

https://github.com/FCL-Team/FoldCraftLauncher/assets/141497672/547e7f0a-bd5a-4e12-90c4-787f9a1ad8a4

this is the crash video

### Launcher Crash Report

...vsgsgss

### Launcher Log File

jsjdhdzhxuux

**Comment by LegacyGamerHD** [comment]
Not our issue
