### ISSUE TITLE
When it launch at least a beta?

### ISSUE THREAD

**Issue by padamchauhan** [FCL-Team/FoldCraftLauncher#8]

**Comment by LegacyGamerHD** [comment]
no eta

**Comment by HEROBRINE31853** [comment]
Shat te fuk?

**Comment by tigerbrocode** [comment]
💀

**Comment by LegacyGamerHD** [comment]
> Shat te fuk?

you got that to me

**Comment by HEROBRINE31853** [comment]
**_When will the beta test be released?_**

**Comment by LegacyGamerHD** [comment]
> **_When will the beta test be released?_** want to play it

not any time soon

**Comment by HEROBRINE31853** [comment]
> > **_When will the beta test be released?_** want to play it
> 
> not any time soon
Which do you think is better?, HMCL-PE, POJAV LAUNCHER, MCINABOX, OR, FOLDCRAFT LAUNCHER?
