### ISSUE TITLE
添加手柄支持

### ISSUE THREAD

**Issue by LIPiston** [FCL-Team/FoldCraftLauncher#83]
### Description

对mc内做到手柄支持
类似pojav那种手柄每个键映射一个字符
开菜单或者游戏外就用摇杆控制鼠标

### Why

需要使用手柄来游玩mc
手机上使用mod并不能适配手柄

**Comment by root-S7** [comment]
按键太少，不适合mod整合包使用。我也不太清楚适配有啥用

**Comment by LIPiston** [comment]
> 按键太少，不适合mod整合包使用。我也不太清楚适配有啥用

给原版用啊（，按键是刚刚好的
