### ISSUE TITLE
鼠标点击出错

### ISSUE THREAD

**Issue by LIPiston** [FCL-Team/FoldCraftLauncher#84]
### Description

希望能做到类似pojav的鼠标

### Why

因为目前的按下点击无法做到批量合成
也无法选中物品归类
物品栏使用体验很差

**Comment by didntpenguin** [comment]
u can select between slide mode and click mode bro?

**Comment by LIPiston** [comment]
> u can select between slide mode and click mode bro?

那有可能是我的问题（？
因为我没法批量分解物品
也没法批量合成物品
（原版逻辑应该是按住 shift+left 就可以全部分解/合成

That could be my problem(?
Because I can't bulk disenchant items
Can't bulk synthesize items
(The original logic should be to hold down shift+left to decompose/synthesize all
----Google Translate

**Comment by LIPiston** [comment]
确认了是我这边鼠标点击有毛病
不清楚是什么情况
我没法批量合成

**Comment by didntpenguin** [comment]
> > u can select between slide mode and click mode bro?
> 
> 那有可能是我的问题（？ 因为我没法批量分解物品 也没法批量合成物品 （原版逻辑应该是按住 shift+left 就可以全部分解/合成
> 
> That could be my problem(? Because I can't bulk disenchant items Can't bulk synthesize items (The original logic should be to hold down shift+left to decompose/synthesize all ----Google Translate

u can try hold shift button and right click or left click it

**Comment by LIPiston** [comment]
我怀疑的脑子不好了
之前不知道什么时候开的触屏模式忘记关了
问题解决了

I'm out of my mind doubting
I don’t know when I turned on the touch screen mode and forgot to turn it off
The problem is solved
-Google
