### ISSUE TITLE
Bug with design.

### ISSUE THREAD

**Issue by remix5050** [FCL-Team/FoldCraftLauncher#85]
### Launcher Version

1.0.6 patch1

### Device Information

Redmi Note 10 Pro, Android 13 (Pixel Experience), Arm64

### Problem Description

The design of the launcher is so badly made that I will describe it as a mistake.  Hope you fix this problem.

**Comment by zkitefly** [comment]
please describe in detail

**Comment by LegacyGamerHD** [comment]
> ### Launcher Version
> 1.0.6 patch1
> 
> ### Device Information
> Redmi Note 10 Pro, Android 13 (Pixel Experience), Arm64
> 
> ### Problem Description
> The design of the launcher is so badly made that I will describe it as a mistake. Hope you fix this problem.
> 
> ### Java
> _No response_
> 
> ### Renderer
> _No response_
> 
> ### Game Version
> _No response_
> 
> ### Modifications Made to the Game
> _No response_
> 
> ### Game Crash Report
> _No response_
> 
> ### Launcher Crash Report
> _No response_
> 
> ### Launcher Log File
> _No response_

Not really helpful as your saying it's bad but you don't even tell what's bad

**Comment by remix5050** [comment]
I am writing to you about the design of the launcher in general. The design is very bad. I can make you a concept of what the launcher design would look like if you had a designer on your team..

**Comment by LegacyGamerHD** [comment]
> I am writing to you about the design of the launcher in general. The design is very bad. I can make you a concept of what the launcher design would look like if you had a designer on your team..

funy as am not the owner and your pointing your finger to me if you dont like go and play pojav

**Comment by LegacyGamerHD** [comment]
@ShirosakiMio @Tungstend close this or do someting with it
