### ISSUE TITLE
Fix shader crashing when activating

### ISSUE THREAD

**Issue by rawflesh233** [FCL-Team/FoldCraftLauncher#87]
### Launcher Version

1.0.1

### Device Information

Andriod 11

### Problem Description

bruh fix it please i beg you all

### Java

Java 17

### Renderer

Holy G4les

### Game Version

1.20

### Modifications Made to the Game

Optifine

### Game Crash Report

when activating  a shader it crashes and sends you back to the Launcher Home

### Launcher Crash Report

.

### Launcher Log File

.

**Comment by didntpenguin** [comment]
log where?

**Comment by rawflesh233** [comment]
![Uploading Screenshot_20230815_194725_Fold Craft Launcher.jpg…]()

**Comment by rawflesh233** [comment]
> log where?

![Uploading Screenshot_20230815_194725_Fold Craft Launcher.jpg…]()

**Comment by rawflesh233** [comment]
![Screenshot_20230815_195054_File Manager +](https://github.com/FCL-Team/FoldCraftLauncher/assets/141497672/4c096542-16d5-483e-9bdd-f901094f1a92)

**Comment by rawflesh233** [comment]
> log where?

.

**Comment by rawflesh233** [comment]
im trying the Open4Es shader made for HolyG4les
it worked on Pojavlauncher but ut crashes on Foldcraft :3

**Comment by rawflesh233** [comment]
not just the Open4es shader if i click the "Internal render" in shaderpacks option it crashes too please fix it
