### ISSUE TITLE
is everything okay why it is delaying 

### ISSUE THREAD

**Issue by padamchauhan** [FCL-Team/FoldCraftLauncher#9]

**Comment by padamchauhan** [comment]
reply this comment seriously not on fun or ignoring

**Comment by LegacyGamerHD** [comment]
Just be patient

**Comment by Davicoderliner** [comment]
> 

Is all okay the devs is removing lags crash and more and fixing some thing YouTubers will warn too

**Comment by LegacyGamerHD** [comment]
> > 
> 
> Is all okay the devs is removing lags crash and more and fixing some thing YouTubers will warn too

i dont think there doing anyting tungsten has school and dont forget that for  them they are close to the new year
