### ISSUE TITLE
Dynamic Surrounding

### ISSUE THREAD

**Issue by didntpenguin** [FCL-Team/FoldCraftLauncher#90]
### Launcher Version

latest

### Device Information

Redmi K40

### Problem Description

i guess fcl have same error with pojav, because when i install dynamic Surrounding on 1.12.2,it have bug like white water, white item,idk but can your team fix that?

### Java

Java 8

### Renderer

Gl4es

### Game Version

1.12.2

**Comment by LdragoLegendOP** [comment]
@didntpenguin  bro I think solution set render holy to virglrenderer I think it fix and, foldcraftLauncher team use, holy gl4es 1.1.5 and pojav use holy gl4es 1.1.4 and 1.1.5 render so bug and texture problem
