### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by zybzbk** [FCL-Team/FoldCraftLauncher#92]
### Launcher Version

1.0.7

### Device Information

vivo y52s，V2057A，Android10

### Problem Description

我在启动器中收到更新后，使用了网盘更新后，重新进入启动器，启动器却提示让我更新。

Uploading Screenrecording_20230820_141922.mp4…

### Java

无

### Renderer

无

### Game Version

无

### Modifications Made to the Game

无

**Comment by zkitefly** [comment]
我也遇到了

**Comment by ShirosakiMio** [comment]
之前没改versioncode
