### ISSUE TITLE
强制Unicode字体设置失效

### ISSUE THREAD

**Issue by BallonAirr** [FCL-Team/FoldCraftLauncher#93]
### Launcher Version

1.0.0至今

### Device Information

OPPOA93S,Android11,arm64

### Problem Description

强制Unicode字体设置重新启动游戏后失效

### Java

都有

### Renderer

都有

### Game Version

都有

### Modifications Made to the Game

都有

**Comment by ShirosakiMio** [comment]
启动器启动时强制修改forceUnicodeFont:false
