### ISSUE TITLE
原默认样式被删除后新生成的默认样式会与下一个创建的按键样式同步

### ISSUE THREAD

**Issue by block13566** [FCL-Team/FoldCraftLauncher#95]
### Launcher Version

1.0.7

### Device Information

MI 9, Android11(MIUI12.5),Arm64

### Problem Description

按键样式里所有样式被删除后会新创建一个默认按键样式，如果再创建一个按键样式新创建的默认样式会同步这个按键样式

**Comment by 2022001111** [comment]
我也遇到了
