### ISSUE TITLE
离线皮肤选项

### ISSUE THREAD

**Issue by tazixa** [FCL-Team/FoldCraftLauncher#97]
### Launcher Version

1.0.7

### Device Information

VIVO Y97

### Problem Description

我创建离线账号后，点击第2个按钮，但是它只显示了皮肤，确定，取消。正确显示应该是有本地皮肤文件选择等，我不能确定这是手机问题

### Launcher Log File

https://www.123pan.com/s/bX75Vv-IkJZh.html这是当时的图片

**Comment by Fishheadrabbit** [comment]
你可以先应外置登录皮肤站网址https://littleskin.cn/user
认证服务器地址
https://littleskin.cn/api/yggdrasil
