### ISSUE TITLE
fabric loader and fabric api is not working for armeabi-v7a piz fix

### ISSUE THREAD

**Issue by Rakib12345yb** [FCL-Team/FoldCraftLauncher#98]
### Launcher Version

e.g. 1.0.7

### Device Information

e.g. samsung galaxy A13,android 13,armeabi-v7a

### Problem Description

fabric loader and fabric api game not launch
game v.1.20.1
java 17
samsung galaxy A13
android 13
`armeabi-v7a`

### Java

e.g. 17

### Renderer

e.g. Holy-GL4ES

### Game Version

e.g. 1.20.1

### Modifications Made to the Game

e.g. fabric 0.14.22,fabric api 0.87.0+1.20.1

**Comment by didntpenguin** [comment]
1.20 not support 32bit device

**Comment by Rakib12345yb** [comment]
> only 32bit 1024MB You need run 1.6-1.12 vanilla

My optifine is working my device 1.20.1
