### ISSUE TITLE
Sudden heating issues 

### ISSUE THREAD

**Issue by MoonKnightBhai** [FCL-Team/FoldCraftLauncher#99]
### Launcher Version

1.0.7

### Device Information

Realme5

### Problem Description

Game is heating on all version after the last 2 updates for reach same performance plz fix the issue during 1.0.6 used to heat upto 38°c on Snapdragon 665 when playing on 1.12.2 for 30-40 minutes now it heats in 15 minutes and sometimes reaches 40°C wich isn't the idle temperature even 1.20.1 heats in 2-3 minutes wich used to take 15 minutes in old version of Launcher

### Renderer

Holygl4es 

### Game Version

All

### Modifications Made to the Game

All

**Comment by LegacyGamerHD** [comment]
> ### Launcher Version
> 1.0.7
> 
> ### Device Information
> Realme5
> 
> ### Problem Description
> Game is heating on all version after the last 2 updates for reach same performance plz fix the issue during 1.0.6 used to heat upto 38°c on Snapdragon 665 when playing on 1.12.2 for 30-40 minutes now it heats in 15 minutes and sometimes reaches 40°C wich isn't the idle temperature even 1.20.1 heats in 2-3 minutes wich used to take 15 minutes in old version of Launcher
> 
> ### Java
> _No response_
> 
> ### Renderer
> Holygl4es
> 
> ### Game Version
> All
> 
> ### Modifications Made to the Game
> All
> 
> ### Game Crash Report
> _No response_
> 
> ### Launcher Crash Report
> _No response_
> 
> ### Launcher Log File
> _No response_

Its a pc game what do you expext

**Comment by MoonKnightBhai** [comment]
I don't mean like that pojavaluncher is running without much heating even at 38°C in 1.20.1 for 20-30 minutes HMCLPE is also working with less heating FCL started heating in version 1.0.7 reaching 40°c to 42°C  in all version a bit quickly then usually which wasn't the issue in V1.0.1 to V1.0.6

**Comment by root-S7** [comment]
这是游戏问题跟启动器无关，还有就是你觉得温度高可以去设置内锁定60fps而不是在这抱怨

**Comment by MoonKnightBhai** [comment]
> 这是游戏问题跟启动器无关，还有就是你觉得温度高可以去设置内锁定60fps而不是在这抱怨

I rechecked and saw that holygl4es is hearing and VGPU is working fine 37.5°C after 30-40 minutes of 1.12.2 :)

**Comment by BallonAirr** [comment]
但是这是渲染器问题，启动器能做到的优化不是很大
